### ISSUE TITLE
Support cloud functions for firebase

### ISSUE THREAD

**Issue by markgoho** [maciejtreder/ng-toolkit#243]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[X] Feature request
[ ] Documentation issue or request
</code></pre>

## Current behavior
Deployment is done via gcloud config/script

## Expected behavior
We should be able to run `firebase init` add Functions to the project and deploy that way

## What is the motivation / use case for changing the behavior?
Cloud functions for firebase seems like a more intuitive way to deploy SSR with Google

**Comment by maciejtreder** [comment]
As far as I understand we are speaking about automating this solution:

https://towardsdatascience.com/go-serverless-with-firebase-5348dedb70e9

**Comment by markgoho** [comment]
I think the user could be responsible for installing firebase and running
the initial command. I was hoping to see scripts set up and the angular
workspace file set up for easy deployment. This would include where the
dist folders end up, etc.

**Comment by maciejtreder** [comment]
@markgoho Published yesterday. Could you verify?

Documentation can be found here: https://github.com/maciejtreder/ng-toolkit/tree/master/schematics/serverless 

Also, it would be great if you could retweet: https://twitter.com/MaciejTreder/status/998439897403977728 

:)

**Comment by maciejtreder** [comment]
Ok. I assume from the icon that everything works as expected :)

**Comment by markgoho** [comment]
@maciejtreder that would be a false assumption 😢 

I haven't had a chance to test this yet. I was just celebrating the update. I'll test this tonight after work!!

**Comment by maciejtreder** [comment]
@markgoho Ok. Let me know how it works. If something is still wrong just reopen this issue.

PS: Don't forget to share this project with your friends and ask them for stars and share with others and any other support. Today we have a big day: First recurring backer! https://opencollective.com/ng-toolkit

**Comment by markgoho** [comment]
Was not able to successfully deploy. Opened #283
