### ISSUE TITLE
The application is not Rendering Server Side

### ISSUE THREAD

**Issue by ansaries** [maciejtreder/ng-toolkit#260]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[*] Documentation issue or request
</code></pre>

## Current behavior
SSR not working. I have deployed the app here: https://my-serverless-fixonclick-1234.firebaseapp.com
Documentation missing major deployment steps.

## Expected behavior
Serverless SSR Should work. but it isn't.
It would be great if you could mention the steps to create the credentials key.json for google and aws.
Also links to more detail about serverless to serverless website like https://serverless.com/framework/docs/providers/google/guide/intro
as it would save a lot of time of the newbies like me.

## Minimal reproduction of the problem with instructions
To deploy the app, I used the command
`npm run build:deploy`
It deployed the HelloWorld Function on google cloud, the following was my console: 
<pre><code>
serverless deploy

Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Compiling function "helloWorld"...
Serverless: Creating deployment...
Serverless: Checking deployment create progress...
.
Serverless: Done...
Serverless: Uploading artifacts...
Serverless: Artifacts successfully uploaded...
Serverless: Updating deployment...
Serverless: Checking deployment update progress...
..
Serverless: Done...
Service Information
service: fixonclickapp
project: my-serverless-fixonclick-1234
stage: dev
region: us-central1

Deployed functions
helloWorld
  https://us-central1-my-serverless-fixonclick-1234.cloudfunctions.net/http
</code></pre>
But now when I browsed this link: https://my-serverless-fixonclick-1234.firebaseapp.com/
nothing happened so I had to use firebase tools to deploy i.e firebase deploy and use hosting.

Please tell me what am I missing here.

## Environment
Angular version: 6.0.0
For Tooling issues:
- Node version: 8.10.0
- Platform:  Windows 

</code></pre>

**Comment by maciejtreder** [comment]
@ansaries 

Few things needs to be mentioned here:

1. There is no official support for firebase yet. In fact you deployed **google cloud function** (it will come really soon - be patient),

2. I just navigated to the URL from the serverless output (https://us-central1-my-serverless-fixonclick-1234.cloudfunctions.net/http) and there is a problem with base path (please, change it in the `src/index.html` to ```<base href="/http/">```

3. I will do my best to find environment automatically on the server side, and render proper base path based on that (if you will be switching to production, you would need to change base path again - that's not really efficient ;) )

**Comment by ansaries** [comment]
thanks @maciejtreder for pointing out the mistake.
However can you please check once again the same link as it is giving CORS and Script Redirect errors in console.

Please review console output:
![angular universal pwa starter -- console](https://user-images.githubusercontent.com/19625307/40265826-c96c34e6-5b50-11e8-822c-a519647b5236.png)

**Comment by maciejtreder** [comment]
@ansaries Could you verify the latest feature in @ng-toolkit/serverless? Just added a firebase support explicitly. https://github.com/maciejtreder/ng-toolkit/tree/master/schematics/serverless 

Regarding redirects issues. I believe that it occurs, because of 'private mode' of the firebase app. As far as I know (I am not firebase-guru) you are running it in some kind of 'sandbox'. In other words, it is available only to you (firebase verifies if you are logged in into same Google Account which is connected with the firebase project).

Please open a new bug, so we could focus on that in a different place :)

**Comment by maciejtreder** [comment]
Also you can check this article, on deeper overview of usage `@ng-toolkit/serverless`. I am going to attach it into README soon:
https://medium.com/@maciejtreder/angular-serverless-a713e86ea07a

**Comment by ansaries** [comment]
thanks @maciejtreder

**Comment by maciejtreder** [comment]
@ansaries I assume that it works. Am I right?
