### ISSUE TITLE
serverless issue

### ISSUE THREAD

**Issue by itranga** [maciejtreder/ng-toolkit#265]
I try deploy app to aws serverless 

 
https://cge149bt26.execute-api.eu-central-1.amazonaws.com/production is working 
https://cge149bt26.execute-api.eu-central-1.amazonaws.com/donors got error ( {"message":"Forbidden"}  )

**Comment by maciejtreder** [comment]
@itranga Thanks for this report. How did you set up your project?

Cloning the repo or by using CLI (`ng init --collection @ng-toolkit/init myApp`)?

**Comment by itranga** [comment]
I used ng new --collection @ng-toolkit/init myApp

**Comment by itranga** [comment]
Sorry I used ng new --collection @ng-toolkit/init myApp

**Comment by maciejtreder** [comment]
I updated your comment. If you are using the `@` sign you need to use `<pre>` or ``` in your comment.

What command did you use to deploy?

```npm run build:prod:deploy```
or
```npm run build:serverless:deploy```
?

**Comment by itranga** [comment]
Thank you so much 

npm run build:serverless:deploy  is working

**Comment by maciejtreder** [comment]
You're welcome.

You should use `npm run build:prod:deploy` when you use a custom domain.

Take a look at this article (deep overview of `@ng-toolkit/serverless`):
https://medium.com/@maciejtreder/angular-serverless-a713e86ea07a

And this one, to get know how to setup custom domain in AWS API  Gateway:
https://medium.com/@maciejtreder/custom-domain-in-aws-api-gateway-a2b7feaf9c74

**Comment by jkon** [comment]
Is there a way to set up multiple stages? I want to be able to deploy my app to a 'qa', 'uat' and 'prod' stage. Also, does this play nice with the serverless-domain-manager plugin that is great for handling custom domain deployments?
