### ISSUE TITLE
There was an error in @ng-toolkit/universal@1.1.4

### ISSUE THREAD

**Issue by kexxxfeng** [maciejtreder/ng-toolkit#294]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-tookit/universal
</code></pre>

## Current behavior

```
+ @ng-toolkit/universal@1.1.4
updated 2 packages in 6.069s
Installed packages for tooling via npm.
Invalid regular expression flags
/MyAPP/Demo/node_modules/@ng-toolkit/_utils/index.js:381
            .replace(/([A-Za-z]+(\.[A-z]+\((.*?)\))*)/gs, `"$1"`));
                     ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/MyAPP/Demo/node_modules/@ng-toolkit/universal/src/index.js:4:18)
```

## Environment

<pre><code>
Angular version: 6.0.3
Angular CLI: 6.0.7

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: v8.9.1
- Platform:  darwin x64 10.13.3
- npm: v5.6.0

Others:

</code></pre>

**Comment by maciejtreder** [comment]
Thank you for this report. Fix should be shipped soon :)

**Comment by maciejtreder** [comment]
@kexxxfeng Please verify with the latest build (1.1.8).

**Comment by kexxxfeng** [comment]
Another error has been throw:
```
+ @ng-toolkit/universal@1.1.10
added 9 packages from 4 contributors in 10.227s
Installed packages for tooling via npm.
cli config { '$schema': './node_modules/@angular/cli/lib/config/schema.json',
  version: 1,
  newProjectRoot: 'projects',
  projects:
   { Demo:
      { root: '',
        sourceRoot: 'src',
        projectType: 'application',
        prefix: 'app',
        schematics: {},
        architect: [Object] },
     'Demo-e2e': { root: 'e2e/', projectType: 'application', architect: [Object] } },
  defaultProject: 'Demo' }
distFolder dist
ERROR: Invalid flags supplied to RegExp constructor 's'
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.
```
Have you tested this tool? It even doesn't work in new angular project.

**Comment by maciejtreder** [comment]
@kexxxfeng Unfortunately on my machine (mac) I don't have a problem with the 's' flag. So I could left something accidentally. Please verify now.

**Comment by maciejtreder** [comment]
Uhh Gimme sec. Found another issue :/

**Comment by maciejtreder** [comment]
@kexxxfeng Now :)

**Comment by MdShuaib** [comment]
> if you are using angular-cli: 6.1.1

> Downgrade to lower version of angular-cli

`npm uninstall -g @angular/cli `
`npm cache verify`
`npm install -g @angular/cli@6.0.8`
`ng add @ng-toolkit/universal`

> And it works for me!

**Comment by mahe7star** [comment]
npm ERR! addLocal Could not install /home/mahesh/Development/Test/@ng-toolkit/_utils@^1.1.40
I am having this error while installing @ng-toolkit/universal

**Comment by mohakp** [comment]
> npm ERR! addLocal Could not install /home/mahesh/Development/Test/@ng-toolkit/_utils@^1.1.40

Downgrade your ```@angular/cli``` version to ```6.0.8``` as mentioned above.
I had the same problem, but removing ng-toolkit/universal dependency from ```package.json``` and running ```npm i``` and then again ```ng add @ng-toolkit/universal``` worked for me.

**Comment by playground** [comment]
I'm getting this error, running ng cli 6.2.5
 
npm install --save @ng-toolkit/universal@1.1.41-beta.110
npm ERR! code E400
npm ERR! 400 Bad Request: @ng-toolkit/pwa@^1.1.40
