### ISSUE TITLE
Error: Cannot match any routes.

### ISSUE THREAD

**Issue by dyatesupnorth** [maciejtreder/ng-toolkit#304]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[X] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
</code></pre>

## Current behavior

Running `npm run build:prod && npm run server` 

Navigating to `http://localhost:8080`
Get following mesage in terminal 👍 
`Cannot match any routes. URL Segment: 'ngsw_worker.es6.js.map'`

## Expected behavior
The application should serve pre rendered HTML before the Angular application kicks in.

## Minimal reproduction of the problem with instructions

*STEPS TO REPRODUCE*
`mkdir newProject && cd newProject`

`ng new --collection @ng-toolkit/init newProject`

'npm run build:prod && npm run server'

Open an incognito tab, go to `http://localhost:8080`

`Right-click` -> `View Page Source`

Error appears in terminal.

## What is the motivation / use case for changing the behavior?
This error occurs when adding Angular Universal to existing app as well as beginning a new project with `ng-toolkit`

## Environment

<pre><code>
Angular version: 6.0.3 (same error in another project running 6.0.0)

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: `v8.11.2`
- Platform:  Mac

**Comment by maciejtreder** [comment]
Hello, thank you for reporting this bug. Take a look at this one: https://github.com/maciejtreder/ng-toolkit/issues/307

You shouldn't check app 'universality' by using 'view source' option in the browser. Try to use `curl` command i.e.:
```
curl -i http://localhost:8080
```

You can ignore the error message thrown by nodeJS, it doesn't have impact on server-side rendering functionality.
