### ISSUE TITLE
Angular Universal PWA site is not Universal

### ISSUE THREAD

**Issue by neonguru** [maciejtreder/ng-toolkit#307]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X?] @ng-toolkit/universal
</code></pre>

## Current behavior

https://www.angular-universal-pwa.maciejtreder.com/
That site claims to be universal but &lt;app-root&gt; is empty

## Expected behavior

&lt;app-root&gt; should have contents of the page.

## Minimal reproduction of the problem with instructions

Open:
https://www.angular-universal-pwa.maciejtreder.com/
Do view source.
Notice defect.

## What is the motivation / use case for changing the behavior?

to be a universal app

## Environment

<pre><code>
Angular version: N/A

Browser:
- [X] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: N/A  
- Platform: Windows 

Others:

</code></pre>

**Comment by maciejtreder** [comment]
I am affraid that using 'view source' method is not the best way to check if app is universal or not.

Try to use `curl` command:
```
curl -i https://www.angular-universal-pwa.maciejtreder.com/
```

I performed it on my end, and got rendered html as a response.


For more info about angular universal check this article: https://medium.com/@maciejtreder/angular-server-side-rendering-with-ng-toolkit-universal-c08479ca688

**Comment by neonguru** [comment]
I looked at response of call and it was empty as well.

**Comment by maciejtreder** [comment]
Hi,

It’s impossible that curl on my end, works differently then on yours :)

Try with this tool: https://onlinecurl.com
