### ISSUE TITLE
Unexpected token ] in JSON at position 537 @ng-toolkit/universal

### ISSUE THREAD

**Issue by juadiga** [maciejtreder/ng-toolkit#313]
## I'm submitting a...

<pre><code>
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x ] @ng-toolkit/universal
</code></pre>

## Current behavior

ng add @ng-toolkit/universal

## Expected behavior

+ @ng-toolkit/universal@1.1.16
updated 1 package in 107.688s
Installed packages for tooling via npm.
ERROR: Unexpected token ] in JSON at position 537

## Environment
<pre><code>
Angular version: 6.0.4
</code></pre>

Browser:
- [x ] Chrome (desktop) version 66.0.3359.181

 
For Tooling issues:
- Node version: 10.1.0  
- Platform:  Windows 10

**Comment by maciejtreder** [comment]
@juadiga Could you also provide me with the full log and link to your repository? Or you just used?:

```
ng new someApp
cd someApp
ng add @ng-toolki/universal
```

**Comment by juadiga** [comment]
I'm trying from an existing project and it did not work. But from a new one, it works well. Thank you

**Comment by maciejtreder** [comment]
Ok. Let’s fix ur project. Did you host it somewhere? Can you share with me ur GIT repository?

**Comment by maciejtreder** [comment]
@juadiga Hello! please verify with the latest version

**Comment by juadiga** [comment]
It works thank you

**Comment by maciejtreder** [comment]
Yw

**Comment by NDelbiaggio** [comment]
I got the following error which seems to be  the same kind, any idea how to fix it?
Unexpected token } in JSON at position 1815

**Comment by XMalatji** [comment]
I updated my Node js then this started happening
