### ISSUE TITLE
deployment in iis

### ISSUE THREAD

**Issue by kannan-psibertech** [maciejtreder/ng-toolkit#315]
hi,
i have created a project using ng-toolkit/universal angular seo project. i did server build, it working fine in local. i have published in iis ,its not working. that folder contains 2 folders (server and browser) and server.js file. could you please tell me how to publish in iis?

**Comment by Dariuosh** [comment]
You must first install  [iisnode](https://github.com/Azure/iisnode) Module for IIS,
and then you need to install the  [URL ReWrite](https://www.iis.net/downloads/microsoft/url-rewrite) Module for IIS,
and finally add the  'web.config'  like this  [tempale](https://gist.github.com/pbaio/f63918181d8d7f8ee1d2).

**Comment by ingluca888** [comment]
I execute: npm run build:prod which creates a dist folder with browser folder, server folder, server.js, how do I deploy the app on a shared hosting which uses iisnode and how do I need to set up the web.config file?

**Comment by KingDarBoja** [comment]
@ingluca888 No idea how to do it, better post it on StackOverflow as these schematics doesn't take into account `iisnode` as deployment target.
