### ISSUE TITLE
Lazy loading module do not work.

### ISSUE THREAD

**Issue by javsal** [maciejtreder/ng-toolkit#318]
I created a module which throw following error.

ERROR in Could not resolve module app/detail/detail.module relative to D:/ngstatetransfer/src/app/app-routing.module.ts

In app-routing.module.ts I defined routing following:
<pre><code>
const routes: Routes = [
    { path: '', component: HomeComponent },
    {path: 'product/:slug', loadChildren:'app/detail/detail.module#DetailModule' }
]; 
</code></pre>
If routing is defined like following:

<pre><code>
const routes: Routes = [
    { path: '', component: HomeComponent },
    {path: 'product/:slug', loadChildren:'./detail/detail.module#DetailModule' }
]; 
</code></pre>

Its compile with error free and when I navigate to the lazy loaded module its load successfully but If refresh the browser or directly copy the url and paste in another tab its throw following error in server console  not in browser:

ERROR { Error: Uncaught (in promise): Error: Cannot find module "./detail/detail.module.ngfactory".
Error: Cannot find module "./detail/detail.module.ngfactory".
    at D:\ngstatetransfer\dist\server.js:86966:11
 
Angular Cli version "@angular/cli": "~6.0.0",
Node versaion: 8.11.1

**Comment by maciejtreder** [comment]
What stuff fron `@ng-toolkit` did you apply? `@ng-toolkit/init`? `@ng-toolkit/universal`?

**Comment by javsal** [comment]
@maciejtreder  I added @ng-toolkit/universal with ng add @ng-toolkit/universal  command. I didn't execute @ng-toolkit/init. But my server side rendering works good with state transfer and seo meta data loading correctly in all component of app module. When I attempt to add a module and tried to load with lazy loading its throwing error.

**Comment by maciejtreder** [comment]
@javsal Just reproduced this issue in your repo, and looking for the reason. So far - found nothing. If you will have time, please help me.

Here you have a working example of an app with lazy-loaded module with SSR:
https://github.com/maciejtreder/ng-toolkit/tree/master/application

What I am doing is just comparing tsconfig files etc. etc.

When you will find the root-cause please let me know, so I would be able to fix `@ng-toolkit/universal` :)

**Comment by maciejtreder** [comment]
I reproduced this issue for fresh project as well:

```
ng new myApp
cd myApp
ng add @ng-toolkit/universal
```
 
+ add lazy-loaded module.

**Comment by maciejtreder** [comment]
@javsal It's unbelievable... The issue occurs because `AppModule` is imported after `ModuleMapLoaderModule`!

Already fixed. Please verify with the latest version.
