### ISSUE TITLE
ng-toolkit/universal can't find bootstrap

### ISSUE THREAD

**Issue by clagos4** [maciejtreder/ng-toolkit#322]
## I'm submitting a...

<pre><code>
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x ] @ng-toolkit/universal
</code></pre>

## Current behavior

I am trying to install the @ng-toolkit/universal package using npm and it throws the following error.

+ @ng-toolkit/universal@1.1.19
updated 2 packages and audited 31842 packages in 15.392s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
INFO: Project property is set to 'ly-l'.
ERROR: Can't find bootstrap component entry in ./src/./app/app.module.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

## Expected behavior

I expect it to install the package without errors

## Minimal reproduction of the problem with instructions

I ran npm install @ng-toolkit/universal

## Example repository

I can't because it is a private project, but I can share the app.module:
import { BrowserModule } from '@angular/platform-browser';
import { HttpClientModule } from '@angular/common/http'
import { NgModule } from '@angular/core';
import { RouterModule } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { RecaptchaModule, RECAPTCHA_SETTINGS } from 'ng-recaptcha';
import {RecaptchaFormsModule} from 'ng-recaptcha/forms';
import {NgbModule} from '@ng-bootstrap/ng-bootstrap';
import {NgbActiveModal} from '@ng-bootstrap/ng-bootstrap';

import { AppComponent } from './app.component';
import { NavBarComponent } from './nav-bar/nav-bar.component';
import { CarouselComponent } from './carousel/carousel.component';
import { CentralLogoComponent } from './central-logo/central-logo.component';
import { FlyerTipsComponent } from './flyer-tips/flyer-tips.component';
import { AboutUsComponent } from './about-us/about-us.component';
import { HomeComponent } from './home/home.component';
import { ContactUsComponent } from './contact-us/contact-us.component';
import { FlyerComponent } from './flyer/flyer.component';

import { FlyersService } from './flyer-tips/flyers.service';
import { MethodologyComponent } from './methodology/methodology.component';
import { ResultsComponent } from './results/results.component';
import { ContactFormComponent } from './contact-form/contact-form.component';
import { RegisterFormComponent } from './register-form/register-form.component';
import { FooterComponent } from './footer/footer.component';
import { ImageFormComponent } from './image-form/image-form.component';

import { MailerService } from './mailer.service';
import { LineMessageComponent } from './line-message/line-message.component';
import { MessageConfirmDialogComponent } from './message-confirm-dialog/message-confirm-dialog.component';
import { environment } from '../environments/environment';

const routes = [
  { path:'', component: HomeComponent },
  { path:'about-us', component: AboutUsComponent },
  { path:'contact-us', component: ContactUsComponent },
  { path:'methodology', component: MethodologyComponent },
  { path:'results', component: ResultsComponent },
]

@NgModule({
  declarations: [
    AppComponent,
    NavBarComponent,
    CarouselComponent,
    CentralLogoComponent,
    FlyerTipsComponent,
    AboutUsComponent,
    HomeComponent,
    ContactUsComponent,
    FlyerComponent,
    MethodologyComponent,
    ResultsComponent,
    ContactFormComponent,
    RegisterFormComponent,
    FooterComponent,
    ImageFormComponent,
    LineMessageComponent,
    MessageConfirmDialogComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    HttpClientModule,
    RouterModule.forRoot(routes),
    RecaptchaModule.forRoot(), // Keep in mind the "forRoot"-magic nuances!
    RecaptchaFormsModule,
    NgbModule.forRoot()
  ],
  providers: [
    FlyersService,
    MailerService,
    {
      provide: RECAPTCHA_SETTINGS,
      useValue: { 
        siteKey: environment.siteKey,
      }
    },
    NgbActiveModal
  ],
  bootstrap: [
    AppComponent,
    MessageConfirmDialogComponent
  ]
})
export class AppModule { }

## Environment

<pre><code>
Angular version: 6.0.8

Browser:
- [ x] Chrome (desktop) version 67.0.3396.79
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2  
- Platform: Windows 

Others:

</code></pre>

**Comment by maciejtreder** [comment]
Please verify with the latest build.

**Comment by clagos4** [comment]
Apparently, the last issue was solved, but it throws another error now. I will make another issue with the new error. Thanks for the assistance!

**Comment by clagos4** [comment]
Apparently, it goes a little further now, as it is printing other properties in the command line, although it still can't find the bootstrap module. I am receiving the following message now:


+ @ng-toolkit/universal@1.1.21
updated 1 package and audited 31842 packages in 17.743s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
INFO: Project property is set to 'ly-l'.
component
    AppComponent
component
    MessageConfirmDialogComponent

ERROR: Can't find bootstrap component (
    MessageConfirmDialogComponent
  ) file path in ./src/./app/app.module.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by maciejtreder** [comment]
Could you verify again?

**Comment by clagos4** [comment]
I verified it again and I am still receiving the same message.

+ @ng-toolkit/universal@1.1.24
updated 2 packages and audited 26952 packages in 39.608s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
INFO: Project property is set to 'ly-l'.
ERROR: Can't find bootstrap component (
    MessageConfirmDialogComponent
  ) file path in ./src/./app/app.module.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

Thank you !

**Comment by maciejtreder** [comment]
That's really weird. What is your OS? node version? Angular CLI version?

**Comment by clagos4** [comment]
I made some changes in my app. I took off the MessageConfirmDialogComponent from the bootstrap section in app.module.ts, and now it is throwing the same error, but now refering to the AppComponent:

INFO: Project property is set to 'ly-l'.
ERROR: Can't find bootstrap component (
    AppComponent
  ) file path in ./src/./app/app.module.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

I have tried using windows 10 and Ubuntu 16.04 and the error is the same for both.
My angular version is 6.0.4. The log I get for my DevKit is:

Angular CLI: 6.0.8
Node: 8.1.0
OS: linux x64
Angular: 6.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.2.1
@angular/cli                      6.0.8
@angular/material                 6.2.1
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.0
typescript                        2.7.2
webpack                           4.8.3

I am using the 8.1.0 version of node

**Comment by maciejtreder** [comment]
Lol. That's crazy. When I am checking your app.module.ts everything works on my end. Can you somehow give me access to that project?

**Comment by clagos4** [comment]
Okay, I made another repository with the project. Please enter to https://github.com/clagos4/bootstrap-error.

**Comment by maciejtreder** [comment]
@clagos4 I have rewritten some methods, from analyzing file by regex, to analyze them by tsc. On my end ng-toolkit works on repository provided by you.

Plase verify one more time:

Before applying, please remove `ng-toolkit` entry from `package.json`.
```
rm -rf node_modules/\@ng-toolkit
rm -rf package-lock.json
ng add @ng-toolkit/universal
```

**Comment by clagos4** [comment]
It woorks!! Thank you so much for your help!!

**Comment by maciejtreder** [comment]
Your welcome. :)

**Comment by nikhilthakur001** [comment]
I am facing the same issue. I installed ng-toolkit earlier in a project, then I removed ng-toolkit and other files which were created by ng-toolkit. Now, when I'm trying to `ng add @ng-toolkit/universal` I'm getting this issue `Bootstrap not found in ./src/.././src/app/app.browser.module.ts.`

**Comment by hmvmpire** [comment]
> I am facing the same issue. I installed ng-toolkit earlier in the project, then I removed ng-toolkit and other files which were created by ng-toolkit. Now, when I'm trying to `ng add @ng-toolkit/universal` again in the same project, I'm getting this issue `Bootstrap not found in ./src/.././src/app/app.browser.module.ts.`

Same issue facing

**Comment by egiev** [comment]
> > I am facing the same issue. I installed ng-toolkit earlier in the project, then I removed ng-toolkit and other files which were created by ng-toolkit. Now, when I'm trying to `ng add @ng-toolkit/universal` again in the same project, I'm getting this issue `Bootstrap not found in ./src/.././src/app/app.browser.module.ts.`
> 

Same here

**Comment by dalibor-sanzeru** [comment]
Same here...

**Comment by fysp11** [comment]
Same here

**Comment by DerKarim** [comment]
This worked for me.
https://stackoverflow.com/a/55167210/9530936

**Comment by abelokon** [comment]
@DerKarim Helped me a lot, thank you!

**Comment by Mds92** [comment]
Same here ....

**Comment by thanhdevapp** [comment]
Same here 

Angular CLI: 7.2.4
Node: 10.15.0
OS: darwin x64
Angular: 7.2.15
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.2.4
@angular/cdk                      6.4.7
@angular/cli                      7.2.4
@ngtools/webpack                  7.0.7
@schematics/angular               7.2.4
@schematics/update                0.12.4
rxjs                              6.5.2
typescript                        3.1.6
webpack                           4.19.1
