### ISSUE TITLE
Module not found: Error: Can't resolve './/server/main' 

### ISSUE THREAD

**Issue by LegolasTheElves** [maciejtreder/ng-toolkit#325]
Any idea why I am getting this error I dont have any additional changes on this I just install ng-toolkit after npm run build:prod the result is this. Thanks in advance

WARNING in ./node_modules/@angular/core/fesm5/core.js
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./server.ts 4826:15-36 5:13-37

WARNING in ./node_modules/@angular/core/fesm5/core.js
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./server.ts 4838:15-102 5:13-37

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./server.ts
Module not found: Error: Can't resolve './/server/main' in 'd:\tosh-wot-angular'
 @ ./server.ts 19:9-34
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! wot@0.0.0 build:server:prod: `ng run wot:server && webpack --config webpack.server.config.js --progress --colors`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the wot@0.0.0 build:server:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2018-06-13T09_42_06_176Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! wot@0.0.0 build:prod: `npm run build:server:prod && npm run build:browser:prod`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the wot@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Lenovo\AppData\Roaming\npm-cache\_logs\2018-06-13T09_42_06_441Z-debug.log

**Comment by maciejtreder** [comment]
@LegolasTheElves Hello,

Thank you for this report. Could you provide some additional data?

What package are you using? ng-toolkit/serverless? ng-toolkit/universal? ng-toolkit/init?

Link to your repository is more than welcome!

Thanks in advance.

**Comment by LegolasTheElves** [comment]
I'm am using ng-toolkit/universal?

**Comment by LegolasTheElves** [comment]
This is the debug log

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build:server:prod' ]
2 info using npm@5.6.0
3 info using node@v8.11.1
4 verbose run-script [ 'prebuild:server:prod',
4 verbose run-script   'build:server:prod',
4 verbose run-script   'postbuild:server:prod' ]
5 info lifecycle wot@0.0.0~prebuild:server:prod: wot@0.0.0
6 info lifecycle wot@0.0.0~build:server:prod: wot@0.0.0
7 verbose lifecycle wot@0.0.0~build:server:prod: unsafe-perm in lifecycle true
8 verbose lifecycle wot@0.0.0~build:server:prod: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\tosh-wot-angular\node_modules\.bin;C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\tosh-wot-angular\node_modules\.bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Lenovo\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Git\cmd;C:\Program Files\dotnet;C:\Program Files\nodejs;C:\WINDOWS\System32\OpenSSH;C:\Users\Lenovo\AppData\Local\Microsoft\WindowsApps;C:\Program Files\Microsoft VS Code\bin;C:\Users\Lenovo\AppData\Roaming\npm
9 verbose lifecycle wot@0.0.0~build:server:prod: CWD: D:\tosh-wot-angular
10 silly lifecycle wot@0.0.0~build:server:prod: Args: [ '/d /s /c',
10 silly lifecycle   'ng run wot:server && webpack --config webpack.server.config.js --progress --colors' ]
11 silly lifecycle wot@0.0.0~build:server:prod: Returned: code: 2  signal: null
12 info lifecycle wot@0.0.0~build:server:prod: Failed to exec build:server:prod script
13 verbose stack Error: wot@0.0.0 build:server:prod: `ng run wot:server && webpack --config webpack.server.config.js --progress --colors`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid wot@0.0.0
15 verbose cwd D:\tosh-wot-angular
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:server:prod"
18 verbose node v8.11.1
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 2
22 error wot@0.0.0 build:server:prod: `ng run wot:server && webpack --config webpack.server.config.js --progress --colors`
22 error Exit status 2
23 error Failed at the wot@0.0.0 build:server:prod script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

**Comment by maciejtreder** [comment]
Thanks. What about repository? Do you have any? Can you share it with me?

**Comment by LegolasTheElves** [comment]
Please refer to this https://github.com/LegolasTheElves/worfoftravel

**Comment by LegolasTheElves** [comment]
Please refer to this https://github.com/LegolasTheElves/wordoftravel/tree/wotWithToolkit

**Comment by maciejtreder** [comment]
@LegolasTheElves There is lack of `angular.json` file in your repository. Please, push it. Thanks in advance!

**Comment by LegolasTheElves** [comment]
this is the code for angular.json 
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "wot": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "/browser",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/assets",
              "src/favicon.ico"
            ],
            "styles": [
              "src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "wot:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "wot:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "wot:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "./karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [],
            "styles": [
              "src/styles.css"
            ],
            "assets": [
              "src/assets",
              "src/favicon.ico"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "/server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          }
        }
      }
    },
    "wot-e2e": {
      "root": "",
      "sourceRoot": "e2e",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "./protractor.conf.js",
            "devServerTarget": "wot:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "e2e/tsconfig.e2e.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "wot",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "app",
      "styleext": "css"
    },
    "@schematics/angular:directive": {
      "prefix": "app"
    }
  }
}`

**Comment by LegolasTheElves** [comment]
I can't find any solution on this please help me out

**Comment by maciejtreder** [comment]
Hey. Your project is not in latest Angular. `@ng-toolkit` supports Angular 6+. Please update to the latest Angular version :)

**Comment by Schrall** [comment]
Same Issue in an Angular 7 Project. 

Angular CLI: 7.0.4
Node: 10.13.0
OS: darwin x64
Angular: 7.0.0
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.4
@angular-devkit/build-angular     0.10.4
@angular-devkit/build-optimizer   0.10.4
@angular-devkit/build-webpack     0.10.4
@angular-devkit/core              7.0.4
@angular-devkit/schematics        7.0.4
@angular/cli                      7.0.4
@angular/language-service         7.0.3
@angular/service-worker           7.0.3
@ngtools/webpack                  7.0.4
@schematics/angular               7.0.5
@schematics/update                0.10.4
rxjs                              6.3.3
typescript                        3.1.3
webpack                           4.19.1



Here my Angular.json
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "Bandbee": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "/browser",
            "index": "src/index.html",
            "main": "src/main.ts",
            "tsConfig": "src/tsconfig.app.json",
            "polyfills": "src/polyfills.ts",
            "assets": [
              "src/assets",
              "src/favicon.ico",
              "src/manifest.json"
            ],
            "styles": [
              "node_modules/primeicons/primeicons.css",
              "node_modules/primeng/resources/themes/nova-light/theme.css",
              "node_modules/primeng/resources/primeng.min.css",
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fontawesome.css",
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fa-solid.css",
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fa-regular.css",
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fa-brands.css",
              "node_modules/font-awesome/css/font-awesome.min.css",
              "node_modules/quill/dist/quill.core.css",
              "node_modules/quill/dist/quill.snow.css",
              "node_modules/primeflex/primeflex.css",
              "src/styles.css"
            ],
            "scripts": [
              "node_modules/quill/dist/quill.js",
              "node_modules/chart.js/dist/Chart.js"
            ]
          },
          "configurations": {
            "production": {
              "optimization": true,
              "serviceWorker": true,
              "ngswConfigPath": "ngsw-config.json",
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "Bandbee:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "Bandbee:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "Bandbee:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "karmaConfig": "karma.conf.js",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "scripts": [
              "node_modules/quill/dist/quill.js"
            ],
            "styles": [
              "src/styles.css",
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fontawesome.css",
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fa-solid.css",
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fa-regular.css",
              "node_modules/@fortawesome/fontawesome-free-webfonts/css/fa-brands.css",
              "node_modules/font-awesome/css/font-awesome.min.css",
              "node_modules/primeng/resources/themes/omega/theme.css",
              "node_modules/primeng/resources/primeng.min.css",
              "node_modules/quill/dist/quill.core.css",
              "node_modules/quill/dist/quill.snow.css"
            ],
            "assets": [
              "src/assets",
              "src/favicon.ico"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "/server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          }
        },
        "app-shell": {
          "builder": "@angular-devkit/build-angular:app-shell",
          "options": {
            "browserTarget": "Bandbee:build",
            "serverTarget": "Bandbee:server",
            "route": "home"
          },
          "configurations": {
            "production": {
              "browserTarget": "Bandbee:build:production"
            }
          }
        }
      }
    },
    "Bandbee-e2e": {
      "root": "",
      "sourceRoot": "",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "protractor.conf.js",
            "devServerTarget": "Bandbee:serve"
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.e2e.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "Bandbee",
  "schematics": {
    "@schematics/angular:component": {
      "prefix": "bandbee",
      "styleext": "css"
    },
    "@schematics/angular:directive": {
      "prefix": "bandbee"
    }
  }
}


Any Solution?

**Comment by kmanimca2008** [comment]
I'm also facing the same issue with @ng-toolkit/universal.

![image](https://user-images.githubusercontent.com/41321169/51227668-605ead00-197b-11e9-8d55-4642a261e9a5.png)

**Comment by Aviking88** [comment]
I am also facing the same issue with Angular-6

**Comment by ganolmc** [comment]
+1

**Comment by Lahciin** [comment]
+1

**Comment by BovineEnthusiast** [comment]
Angular 8 here, same issue. Not sure if it matters, but when I ran `ng add @ng-toolkit/universal` I had a ton of ts errors (mostly implicit `any`s and unused references) in the generated `server.ts` and `prerender.ts` files.

**Comment by Sumanta9x9** [comment]
This module is useless

**Comment by atul2210** [comment]
I am also facing same issue. Any solution, please suggest.  Thanks in advance. :)

**Comment by ankit5577** [comment]
everything worked fine with me. I got rid of the error -
`Cannot find module 'require("./server/main")'`
 by correcting code in the 'server.js' file.

`module.exports = require("require(\"./server/main\")");`
to

`module.exports = require('./server/main');`
i used 'ng-toolkit/universal' and after running 'npm run server' i got same error.

**Comment by nicholas-davis** [comment]
+1

**Comment by nicholas-davis** [comment]
In your `webpack.server.config.js` 

**replace**
```
  externals: {
    './dist/server/main': 'require("./server/main")'
  },
```
**with this**
```
  externals: {
    './dist/server/main': './server/main'
  },
```
