### ISSUE TITLE
install ngtoolkit/universal to existing app without removing .firebasesrc and functions package.json fails

### ISSUE THREAD

**Issue by JamesDevGit** [maciejtreder/ng-toolkit#326]
## I'm submitting a...

<pre><code>
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x ] @ng-toolkit/universal
</code></pre>

## Current behavior

ng add ngtoolkit/serverless with firebase then ng add ngtoolkit/universal to existing app - fails install due to existing firebase setup 

removing these files allows install but dist/browser and dist/server paths get extra "/"  

eg local.js this const server = require('./dist/server'); changed to const server = require('./dist///server');

Also noted that custom tsconfig.ts paths fail on build --prod
ERROR in src\app\app.module.ts(27,64): Error during template compile of 'AppModule'
  Could not resolve @sp-env/environment relative to C:/xampp/htdocs/sp_dev_angular/dev-core/src/app/app.module.ts..

although a ng serve still works ok.

## Expected behavior

Either clarity on which order these should be installed in or check to see if files exist and update rather than try to create and fail if exists. not overwriting existing setup of .firebasesrc would be helpful, just add to.

## Minimal reproduction of the problem with instructions

existing a6 app deployed to firebase  
ng add @ng-toolkit/serverless --provider firebase --firebaseProject myname
ng add ngtoolkit/universal 

## Environment
production build
<pre><code>
Angular version: 
Angular CLI: 6.0.7
Node: 8.11.1
OS: win32 x64
Angular: 6.0.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router
... service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.0
@angular-devkit/build-optimizer   0.6.0
@angular-devkit/core              0.6.7
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.0.1
@angular/cli                      6.0.7
@angular/flex-layout              6.0.0-beta.15
@angular/material                 6.0.1
@angular/pwa                      0.6.8
@ngtools/webpack                  6.0.0
@schematics/angular               0.6.8
@schematics/update                0.6.7
rxjs                              6.1.0
typescript                        2.7.2
webpack                           4.6.0

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by maciejtreder** [comment]
Hello. Thank you for this report.

Did you install set up your firebase project with `@ng-toolkit/serverless` or you have this setup done in other way/manually?

**Comment by JamesDevGit** [comment]
No, project setup already has firebase added prior to running any ng-toolkit commands.

**Comment by maciejtreder** [comment]
@JamesDevGit Ok. Could you provide an url to your repository? It would be really helpful in reproducing this issue :)

**Comment by JamesDevGit** [comment]
Sure, as this repo is private, I sent you a skype message.
