### ISSUE TITLE
Angular Google Maps ReferenceError: window is not defined

### ISSUE THREAD

**Issue by mumpitzman** [maciejtreder/ng-toolkit#327]
I'm submitting a...

<pre><code>
[ x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ x ] @ng-toolkit/universal
</code></pre>

## Current behavior
I'm trying to add angular google maps for browser version only. It looks like app.browser.module.ts is ignoring my imports. While importing it in app.module.ts everything is fine in the browser but I'm getting the following error trying to start the server:

window['MarkerClusterer'] = MarkerClusterer;
ReferenceError: window is not defined

## Expected behavior
```

import { AgmCoreModule } from '@agm/core';
import { AgmJsMarkerClustererModule } from '@agm/js-marker-clusterer';

imports: [
         AgmCoreModule.forRoot({apiKey: 'xxx'}),
         AgmJsMarkerClustererModule
]

<agm-map *ngIf="isBrowser"></agm-map>
```

Is this even possible with app.browser.module.ts? I can exclude code for the server with isPlatformBrowser but I can not find any solution to only import the map for the browser version. Thanks for your help!

**Comment by maciejtreder** [comment]
Hello,

Could you provide a link to example repository?

**Comment by mumpitzman** [comment]
Here you are: [https://github.com/mumpitzman/ng-toolkit-sandbox](https://github.com/mumpitzman/ng-toolkit-sandbox)
Thanks

**Comment by maciejtreder** [comment]
@mumpitzman This issue is related to Angular Google Maps (https://github.com/SebastianM/angular-google-maps/issues/668) not ng-toolkit itself. 

What you can do to work-around this problem is creation of mockup object for Angular Google Maps and import it in the `app.server.module.ts`, while importing original one into `app.browser.module.ts`.

If you would choose this path, let me know. Such solution would be more then welcome in ng-toolkit (I am working on making such mockups for the most popular libraries, but as you probably know, there are millions of those ;) )

**Comment by dannyschmitt** [comment]
You can try to add the following code to **server.ts** right before **enableProdMode();**

```
const DIST_FOLDER = join(process.cwd(), 'dist');
const domino = require('domino');
const fs = require('fs');
const template = fs.readFileSync(join(DIST_FOLDER, 'browser', 'index.html')).toString();
const win = domino.createWindow(template);

global['window'] = win;
global['document'] = win.document;
global['DOMTokenList'] = win.DOMTokenList;
global['Node'] = win.Node;
global['Text'] = win.Text;
global['HTMLElement'] = win.HTMLElement;
global['HTMLCanvasElement'] = win.HTMLCanvasElement;
global['navigator'] = win.navigator;
global['MutationObserver'] = getMockMutationObserver();

function getMockMutationObserver() {
   return class {
     observe(node, options) {
     }
     disconnect() {
     }
     takeRecords() {
       return [];
     }
   };
}
```
