### ISSUE TITLE
All bundles contain same index.html content in /production/ giving error 'Unexpected token <'

### ISSUE THREAD

**Issue by ciarancourtney** [maciejtreder/ng-toolkit#328]
## I'm submitting a...

<pre><code>
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ x] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
</code></pre>

## Current behavior
All bundles contain the same index.html content

## Expected behavior
bundles should contain js code

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [x] Chrome (desktop) version 67
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.10  
- Platform:  Windows

Others:

</code></pre>

**Comment by maciejtreder** [comment]
Hello. Can you provide me an URL to your repo?

**Comment by ciarancourtney** [comment]
I'm afraid not, its a private repo. Its a pretty standard ng6 app, lambda deploy also just results in 'internal server error' not the ng 'Loading ....' and console error as per local serve

**Comment by ciarancourtney** [comment]
RE lamdba not working, in lambda.js I see `const server = require('./dist/server');` but there is no `server.js` in `dist`. HTML and main.js are there and look fine

**Comment by maciejtreder** [comment]
Unfortunately, without the repository, I am unable to reproduce this issue. Running ng-toolkit on brand new project works:
```
ng new someApp
cd someApp
ng add @ng-toolkit/serverless
```
