### ISSUE TITLE
Invalid regular expression in ng-universal

### ISSUE THREAD

**Issue by gunjan008** [maciejtreder/ng-toolkit#339]
when running the command 'ng add @ng-toolkit/universal' I am getting the error which says
'Invalid regular expression: /class.*{[\s\S]*?((?<![\.'"])window)/: Invalid group'

**Comment by mattcoll** [comment]
@maciejtreder I am receiving this error as well. 
@gunjan008 Have you found a workaround or anything yet?

**Comment by rathahin** [comment]
@maciejtreder I am receiving the same error. I starting the new project and got the same error when try to add "ng add @ng-toolkit/universal" 
Hope to receive solution soon!

**Comment by maciejtreder** [comment]
Hello folks. I’ll try to do my best to fix it ASAP. Sorry for inconvenience.

**Comment by mattcoll** [comment]
@maciejtreder Thanks for your prompt reply. You are doing a great job with this feature. Keep us updated! Thanks

**Comment by rathahin** [comment]
@maciejtreder Thank you very much for fast response

**Comment by maciejtreder** [comment]
@mattcoll @rathahin @gunjan008 

Could you verify with the actual build?

**Comment by mattcoll** [comment]
@maciejtreder I have manage to `ng build --prod` without error, but it doesn't seem to be working correctly. I have uploaded my build here : 
http://ng-toolkit-universal.s3-website-ap-southeast-2.amazonaws.com 
Here is following terminal error:
`git:(master) ✗ ng add @ng-toolkit/universal
Installing packages for tooling via npm.
INFO: Project property is set to 'awesome-seo'.
ERROR: Invalid regular expression: /class.*{[\s\S]*?((?<![\.'"])window)/: Invalid group
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.`

**Comment by maciejtreder** [comment]
Try to remove it from node_modules:

`rm -rf node_modules/\@ng-toolkit`

Probably Angular CLI is trying with the version which you have already installed.

**Comment by mattcoll** [comment]
@maciejtreder Wow, why didn't I think of that. When I cloned the project and npm installed it was already there, so removing it and adding it again fixed my issue. It works perfect now. Again thanks for your prompt reply and help fixing this issue! Hope this helped everyone else as well.

**Comment by maciejtreder** [comment]
You won't achieve Server-Side rendering with S3. Check out `@ng-toolkit/serverless`:

https://github.com/maciejtreder/ng-toolkit/tree/master/schematics/serverless
https://medium.com/@maciejtreder/angular-serverless-a713e86ea07a

Feel welcome to support project via OpenCollective or other ways:
https://opencollective.com/ng-toolkit

**Comment by mattcoll** [comment]
@maciejtreder Cool thanks. I use serverless already for some other projects. I wonder if I can use lambda or something. I'm trying to utilise cloud solutions as much as possible and avoid EC2 or server. I appreciate all your help and will make a contribution towards the project. Thanks again, your work is awesome!
