### ISSUE TITLE
ERROR: Can't parse NgModule settings in ./src/./app/app.module.ts. Please verify trailing commas.

### ISSUE THREAD

**Issue by khalidsheikhs** [maciejtreder/ng-toolkit#340]
My app.module.ts file code is given below.

<pre><code>
import { NgModule } from '@angular/core';
import { BrowserModule, Title, Meta } from '@angular/platform-browser';
import { FormsModule } from '@angular/forms';
import { AppRoutingModule } from './app-routing.module';
import { HttpClientModule, HttpClientJsonpModule } from '@angular/common/http';
import { CollapseModule } from 'ngx-bootstrap/collapse';
import { BsDropdownModule } from 'ngx-bootstrap/dropdown';
import { ModalModule } from 'ngx-bootstrap/modal';
import { InfiniteScrollModule } from './infinite-scroll/infinite-scroll.module';
import { ShareModule } from '@ngx-share/core';
import { YoutubePlayerModule } from 'ngx-youtube-player';
import { NguCarouselModule } from '@ngu/carousel';

import { AppComponent } from './app.component';
import { HomeComponent } from './components/home/home.component';
import { BannerComponent } from './components/home/banner/banner.component';
import { CategoryComponent } from './components/category/category.component';
import { ArticleComponent } from './components/article/article.component';
import { PageComponent } from './components/page/page.component';
import { SearchComponent } from './components/search/search.component';
import { PageNotFoundComponent } from './components/page-not-found/page-not-found.component';
import { ArticleBoxHSmComponent } from './components/shared/article-box-h-sm/article-box-h-sm.component';
import { ArticleBoxHMdComponent } from './components/shared/article-box-h-md/article-box-h-md.component';
import { ArticleBoxHLgComponent } from './components/shared/article-box-h-lg/article-box-h-lg.component';
import { ArticleBoxVSmComponent } from './components/shared/article-box-v-sm/article-box-v-sm.component';
import { ArticleBoxVMdComponent } from './components/shared/article-box-v-md/article-box-v-md.component';
import { ArticleBoxVLgComponent } from './components/shared/article-box-v-lg/article-box-v-lg.component';
import { AdLeaderboardComponent } from './components/shared/ad-leaderboard/ad-leaderboard.component';
import { SocialShareComponent } from './components/shared/social-share/social-share.component';

import { MenuService } from './services/shared/menu.service';
import { HomeService } from './services/home/home.service';
import { CategoryService } from './services/category/category.service';
import { TagService } from './services/tag/tag.service';
import { ArticleService } from './services/article/article.service';
import { PageService } from './services/page/page.service';
import { UtilityService } from './services/shared/utility.service';

@NgModule({
  declarations: [
    AppComponent,
    HomeComponent,
    BannerComponent,
    CategoryComponent,
    ArticleComponent,
    PageComponent,
    SearchComponent,
    PageNotFoundComponent,
    ArticleBoxHSmComponent,
    ArticleBoxHMdComponent,
    ArticleBoxHLgComponent,
    ArticleBoxVSmComponent,
    ArticleBoxVMdComponent,
    ArticleBoxVLgComponent,
    AdLeaderboardComponent,
    SocialShareComponent
  ],
  imports: [
    BrowserModule,
    FormsModule,
    AppRoutingModule,
    HttpClientModule,      // Social share counts and many other data services
    HttpClientJsonpModule,  // Tumblr share counts
    CollapseModule.forRoot(),
    BsDropdownModule.forRoot(),
    ModalModule.forRoot(),
    InfiniteScrollModule,
    ShareModule.forRoot(),
    YoutubePlayerModule,
    NguCarouselModule
  ],
  providers: [
    Title,
    Meta,
    MenuService,
    HomeService,
    CategoryService,
    TagService,
    ArticleService,
    PageService,
    UtilityService
  ],
  bootstrap: [ AppComponent ]
})
export class AppModule {}

</code></pre>

**Comment by Kalpesh300** [comment]
+1

**Comment by khalidsheikhs** [comment]
Issue resolved. Thanks

**Comment by biancamenacho94** [comment]
wait! how you solved your problem!!??

I got tha same issue :(
