### ISSUE TITLE
 Can't parse NgModule settings in ./src/./app/app.module.ts. Please verify trailing commas.

### ISSUE THREAD

**Issue by mohittanwani** [maciejtreder/ng-toolkit#342]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by maciejtreder** [comment]
Hello. There was a problem with comments in the decorators. Please verify again with version `1.1.26`:

```
rm -rf node_modules/\@ng-toolkit
ng add @ng-toolkit/universal
```
