### ISSUE TITLE
Cannot run server when using ng2-materialize

### ISSUE THREAD

**Issue by blizarazu** [maciejtreder/ng-toolkit#344]
## I'm submitting a...

<pre><code>
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x ] @ng-toolkit/universal
</code></pre>

## Current behavior

If you use ng2-materialize in the project, you get an error in dist/server.js when running the server:
```
if ("Event" in window) {

ReferenceError: window is not defined
```
It may be a ng2-materialize problem. There is a newer package called ngx-materialize, but I couldn't test if it also gives the same error.

## Expected behavior

The server runs and the application is available at http://localhost:8080

## Minimal reproduction of the problem with instructions

- Add ng2-materialize module to the project
- run `npm run build:prod`
- run `npm run server`

## Environment

<pre><code>
Angular version: 6.0.3

Browser:
- [] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [x ] Firefox version 60.0.2
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.11.2
- Platform:  Linux

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Closing now for housekeeping purposes.

Please open a new issue in case you still dealing with this.

Cheers!
