### ISSUE TITLE
How to use PWA with existing app

### ISSUE THREAD

**Issue by Kalpesh300** [maciejtreder/ng-toolkit#348]
I have an existing app in Angular-6. I have a question about how to use this library for PWA, Universal and serverless together for my existing app.

**Comment by maciejtreder** [comment]
Hello Kalpesh. So far, you can use following ng-toolkit functionalities with the existing app:

server-side-rendering:
https://github.com/maciejtreder/ng-toolkit/tree/master/schematics/universal
https://medium.com/@maciejtreder/angular-server-side-rendering-with-ng-toolkit-universal-c08479ca688

serverless support:
https://github.com/maciejtreder/ng-toolkit/tree/master/schematics/serverless
https://medium.com/@maciejtreder/angular-serverless-a713e86ea07a


If you want to add PWA support, you can use one provided by the Angular team: `ng add @angular/pwa`. I am going to implement an extension for this functionality soon.

You can become a backer on opencollective, to get news about ng-toolkit on your e-mail:
https://opencollective.com/ng-toolkit?referral=14134
