### ISSUE TITLE
Error adding: ng add @ng-toolkit/universal

### ISSUE THREAD

**Issue by biancamenacho94** [maciejtreder/ng-toolkit#353]
PS D:\Proyectos\maraton2018> ng add @ng-toolkit/universal
![errrrr](https://user-images.githubusercontent.com/28678341/42048534-88a0196e-7ad1-11e8-94be-7c054362575d.png)

Installing packages for tooling via npm.
INFO: Project property is set to 'maraton2018'.
ERROR: Can't parse NgModule settings in ./src/./app/app.module.ts. Please verify trailing commas.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.
PS D:\Proyectos\maraton2018>

**Comment by maciejtreder** [comment]
Do you have your project hosted somewhere? GitHub ie?
