### ISSUE TITLE
Cannot add ngtoolkit/universal

### ISSUE THREAD

**Issue by Thangamh** [maciejtreder/ng-toolkit#360]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/universal
</code></pre>

## Current behavior

INFO: Project property is set to 'rush'.
ERROR: Can't find decorator NgModule in ./src/app/app.server.module.ts
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

## Environment

<pre><code>
Angular version: X.Y.Z

    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.0.8
Node: 8.11.1
OS: win32 x64
Angular: 5.2.9
... common, compiler, compiler-cli, core, forms, http
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/animations               5.2.11
@angular/cdk                      5.2.4
@angular/cli                      6.0.8
@angular/flex-layout              5.0.0-beta.14
@angular/material                 5.2.4
@angular/platform-server          6.0.6
@angular/tsc-wrapped              4.4.7
@ngtools/json-schema              1.2.0
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
ng-packagr                        1.7.0
rxjs                              5.5.8
typescript                        2.4.2
webpack                           4.8.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by maciejtreder** [comment]
Hello. Could you provide me code of your project? GitHub? GitLab? Bitbucket? :)
