### ISSUE TITLE
i could not deploy app to firebase after i install ngtoolkit for SEO of my angular app. can you please help with this.

### ISSUE THREAD

**Issue by ajaykumarReddy** [maciejtreder/ng-toolkit#362]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by maciejtreder** [comment]
Verified on my end. Everything works:

```
ng new myApp;cd myApp;ng add @ng-toolkit/serverless --provider firebase;npm run build:serverless:deploy
```

Successfully deployed app on the firebase.

Please provide more details if this issue still occurs.

**Comment by ajaykumarReddy** [comment]
thank you so much for quick response . will get back you after try once again.

**Comment by maciejtreder** [comment]
Ahh gimme sec. I forgot to add ng-toolkit/universal :D

**Comment by maciejtreder** [comment]
@ajaykumarReddy Just verified with Universal. Everything works on my end. Maybe something is not working on your particular project. Do you host it somewhere? GitHub? GitLab? BitBucket?

More info about ng-toolkit/serverless and ng-toolkit/universal can be found [here](https://github.com/maciejtreder/ng-toolkit/blob/master/schematics/serverless/README.md), [here](https://medium.com/@maciejtreder/angular-serverless-a713e86ea07a), [here](https://github.com/maciejtreder/ng-toolkit/blob/master/schematics/universal/README.md) and [here](https://medium.com/@maciejtreder/angular-server-side-rendering-with-ng-toolkit-universal-c08479ca688)

**Comment by ajaykumarReddy** [comment]
@maciejtreder I am really appreciate and thankfull for response . i have hosted in firebase with ng-toolkit and serverless approach. when i started integrating this ngtoolkit and then when i give deploy it was saying some error. i will post that error in more details. if you want i can give my repo url

**Comment by ajaykumarReddy** [comment]
@maciejtreder after doing ng add @ng-toolkit/universal this command to my project what should i do for deploy . do i require to change firebase.json ???

**Comment by maciejtreder** [comment]
The best way would be to use following set:

ng add @ng-toolkit/universal
ng add @ng-toolkit/serverless —provider firebase
npm run build:serverless:deploy

**Comment by ajaykumarReddy** [comment]
![image](https://user-images.githubusercontent.com/8911392/42466738-66ca8874-83cd-11e8-95c2-2682d86543fd.png)

**Comment by ajaykumarReddy** [comment]
@maciejtreder  , I am doing the following commends with brand new angular 6 project using cli.
its going to deploy but not able to access site with index.html.
please let me know anything i am missing......

ng add @ng-toolkit/universal
ng add @ng-toolkit/serverless —provider firebase
npm run build:serverless:deploy

**Comment by ajaykumarReddy** [comment]
final its got successes . thanks a lot . Much appreciated response and help from you @maciejtreder

**Comment by AlejandroTorresR** [comment]
I´m having this same issue

"its going to deploy but not able to access site with index.html"

How you fixed it?
Please help!
