### ISSUE TITLE
ng-toolkit/serverless error in local.js

### ISSUE THREAD

**Issue by markgoho-EDT** [maciejtreder/ng-toolkit#370]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[X] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
</code></pre>

## Current behavior
`const server = require('./dist//server');`
Two forward slashes in the require path

**Comment by maciejtreder** [comment]
I am quite sure, that I was checking it on my end... What provider did you specify?

**Comment by markgoho-EDT** [comment]
firebase

It also removed the comment at the top of the file and changed the console.log message from a template string literal to string concatenation

**Comment by maciejtreder** [comment]
@markgoho-EDT I am unable to reproduce this on my end. Do you have your project in public available repository? GitHub? GitLab? Bitbucket?

**Comment by markgoho-EDT** [comment]
@maciejtreder I was following the directions in [this thread comment](https://github.com/maciejtreder/ng-toolkit/issues/362#issuecomment-403391392)

so I ran add universal, then add serverless, and that's how the file ended up....

Coincidentally, this is the first time that I've gotten the SSR to actually work. Is this command "chaining" documented anywhere?

**Comment by maciejtreder** [comment]
@markgoho-EDT I successfully reproduced this issue. I think, that tomorrow fix will be ready :)

**Comment by maciejtreder** [comment]
@markgoho-EDT Could you verify with the latest build (1.1.39)?
