### ISSUE TITLE
Duplicate identifier 'platformId'

### ISSUE THREAD

**Issue by thewriterl** [maciejtreder/ng-toolkit#373]
Hey there, 

Just did a 'ng new --collection etc etc' on the init package and I'm getting 'duplicate identifier 'platformId' on app component. Any ideas?

**Comment by maciejtreder** [comment]
Just fixed :) In 1.1.37. Please try it again:

```
npm install -g @ng-toolkit/init
ng new --collection @ng-toolkit/init yourAppName
```
