### ISSUE TITLE
Firebase not adding to project

### ISSUE THREAD

**Issue by Shubedobedo** [maciejtreder/ng-toolkit#375]
## In package
[ ] @ng-toolkit/init

## Current behavior
I run:
ng new --collection @ng-toolkit/init myApp --provider firebase --firebaseProject myappproject
cd myApp
npm run build:prod:deploy

## Expected behavior
for it to work

## Work around
firebase use --add
Then select myappproject
Then re-run npm run build:prod:deploy

## Error Message
![image](https://user-images.githubusercontent.com/22240748/42728578-25210d46-878b-11e8-89f0-38c21ab1bd79.png)

**Comment by maciejtreder** [comment]
@Shubedobedo Thanks for the report. Could you verify with the latest build (1.1.39)?

**Comment by Shubedobedo** [comment]
@maciejtreder that has revolved the issue. Thanks for the quick resolution.
