### ISSUE TITLE
Error while trying to build universal

### ISSUE THREAD

**Issue by HenryKenya** [maciejtreder/ng-toolkit#381]
Hello,

I get this error when trying to build using the angular universal toolkit:
Cannot find module '@nguniversal/module-map-ngfactory-loader'

**Comment by maciejtreder** [comment]
@HenryKenya Do you have your project hosted in some public available git repository?
Which version of ng-toolkit you have installed?

As a try:
```
rm -fr node_modules/\@ng-toolkit
ng add @ng-toolkit/universal
```

**Comment by HenryKenya** [comment]
Hello @maciejtreder ...thank you for the reply.
No, the project is not hosted on a public git repo. It's hosted on bitbucket.

Let me give your suggestion a try and then get back to you.

Thank you so much for the quick response.

**Comment by maciejtreder** [comment]
@HenryKenya If you do not hestitate, you could give me an access to it, so I would be able to reproduce this issue on your codebase. My BitBucket login is: contact@maciejtreder.com

**Comment by HenryKenya** [comment]
Let me add you on bitbucket

**Comment by KingDarBoja** [comment]
Closing now for housekeeping purposes.
