### ISSUE TITLE
ng add @ng-toolkit/universal not working properly

### ISSUE THREAD

**Issue by harjit-neo** [maciejtreder/ng-toolkit#383]
## I am trying to create Angular Universal but when execute below command

<pre>ng add @ng-toolkit/universal<code>
it added the import statement like import { @ng-toolkit/universal } from 'any';
Which need to be like import { LOCAL_STORAGE , WINDOW} from '@ng-toolkit/universal';

Constructor code added as constructor(@Inject(@ng-toolkit/universal) private LOCAL_STORAGE: localStorage) { }

Which need to be like below code
constructor(@Inject(LOCAL_STORAGE) private localStorage: any)

**Comment by maciejtreder** [comment]
You're definitely right. Thank you for pointing this out!

**Comment by empystudio** [comment]
Hi,
same issue here.
I hope you can fix it easily

**Comment by maciejtreder** [comment]
It should be fixed now (version 1.1.40)
