### ISSUE TITLE
Firebase Deploy - Specified public directory does not exist, can't deploy hosting

### ISSUE THREAD

**Issue by SvenBudak** [maciejtreder/ng-toolkit#384]
## I'm submitting a...
<pre><code>
[ X ] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ X ] @ng-toolkit/universal
</code></pre>

## Minimal reproduction of the problem with instructions
$ ng add @ng-toolkit/universal
$ firebase deploy

Error Log:
```
i  deploying storage, firestore, functions, hosting
i  storage: checking storage.rules for compilation errors...
+  storage: rules file storage.rules compiled successfully
i  firestore: checking firestore.rules for compilation errors...
+  firestore: rules file firestore.rules compiled successfully
i  functions: ensuring necessary APIs are enabled...
!  functions: missing necessary APIs. Enabling now...
+  functions: all necessary APIs are enabled

Error: Specified public directory does not exist, can't deploy hosting
```

## Example repository
https://gitlab.com/DevMonkeys/expense-calculator

**Comment by Neelaka-Rupun** [comment]
Hi All,
I had faced same issue when deploying the project to firebase and bellow 
the firbase.json as 
```
{
  "hosting": {
    "public": "dist/",
    "ignore": [
      "firebase.json",
      "**/.*",
      "**/node_modules/**"
    ],
    "rewrites": [
      {
        "source": "**",
        "destination": "/index.html"
      }
    ]
  }
}
```

**Comment by shaikshoeb48** [comment]
hi , i think ng build --prod will work.
then you can go for firebase deploy

**Comment by EliseiNicolae** [comment]
Hi, try `ng build --prod` and, after that `firebase deploy`.

If you are using Github-auto-deploy:
put  `"public": "dist/X",` in your firebase.json
where X=your project name, and delete '/dist' from gitignore.

**Comment by shareef99** [comment]
Facing this issue now.

It says, 

> "status": "error",
    "error": "Specified \"public\" directory \"build\" does not exist, can't deploy hosting to site \"projectId\""

What is the workaround?
