### ISSUE TITLE
[Feature Request] Support for gh-pages 

### ISSUE THREAD

**Issue by oleersoy** [maciejtreder/ng-toolkit#385]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[X ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ X] @ng-toolkit/universal
</code></pre>

Hi - Thank you for making this awesome project.  Saw the review on Coursetro and it looks really amazing.  Wondering if it currently supports deployment to GH pages?  There is [a project here that seems to do the trick](https://github.com/rafrex/spa-github-pages), but it would be really cool if it were integrated into this project.

**Comment by KingDarBoja** [comment]
@oleersoy No, Angular Universal requires you to run NodeJS on the server. Github pages are static files only.

Closing now for housekeeping purposes.
