### ISSUE TITLE
SCSS tilde imports causes build errors

### ISSUE THREAD

**Issue by mruknowme** [maciejtreder/ng-toolkit#388]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
</code></pre>

## Current behavior

Using `@import '~src/styles/variables'` (tilde imports for scss) fails. But worked for build before.
Error: `File to import not found or unreadable: ~src/styles/variables.`

## Minimal reproduction of the problem with instructions

Try importing any scss file from created folder 'styles' at `src/`

## What is the motivation / use case for changing the behavior?

Easier imports to avoid something like this: `./../../../../../../../../../../../../../../../../filename`

## Environment

<pre><code>
Angular version: X.Y.Z

Angular CLI: 6.0.8
Node: 10.2.1

</code></pre>

**Comment by nishanth919** [comment]
Any updates on this @mruknowme

**Comment by KingDarBoja** [comment]
Closed as not related to the package itself.

It is a know bug on Angular as far as I know, please take a look at this [StackOverflow post](https://stackoverflow.com/questions/53086593/angular-cli-scss-file-to-import-not-found-or-unreadable).

Cheers!
