### ISSUE TITLE
Running ng add @ng-toolkit/universal fails: ERROR: Path "/local.js" already exist.

### ISSUE THREAD

**Issue by proeben** [maciejtreder/ng-toolkit#390]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
</code></pre>

## Current behavior

Run ng add @ng-toolkit/universal on any newly created project (used angular-cli 6.1.0)

## Expected behavior

Finishing without errors

## Minimal reproduction of the problem with instructions

See above.

## What is the motivation / use case for changing the behavior?

Bug

## Environment
Windows 10
Node 8.11
<pre><code>
Angular version: 6.1.0

yes
Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 Any browser, not browser related
For Tooling issues:
- Node version: 8.11  
- Platform:  Windows

Others:

</code></pre>
+ @ng-toolkit/universal@1.1.40
added 17 packages from 5 contributors and audited 44345 packages in 13.225s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
ERROR: Path "/local.js" already exist.

**Comment by C00kieMonsta** [comment]
I'm having the same problem when running:

`ng add @ng-toolkit/universal`

Maybe it's because I first upgraded my project to Angular 6. Any useful thoughts about this issue?
