### ISSUE TITLE
ng add @ng-toolkit/universal - Wrong path app.component.ts 

### ISSUE THREAD

**Issue by nansCabanac** [maciejtreder/ng-toolkit#393]
## I'm submitting a...

<pre><code>
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X ] @ng-toolkit/universal
</code></pre>

## Current behavior

I have a project with angular 6.
I have try to execute instruction of https://coursetro.com/posts/code/155/Angular-6-SEO-Tutorial-from-Scratch---It's-Super-Simple-Now!

But on "ng add @ng-toolkit/universal" i have this error. 
It search on "./src/app/app/app.component.ts" but  is locate at "./src/app/app.component.ts"

![image](https://user-images.githubusercontent.com/27103011/43333558-d4d46546-91ca-11e8-9571-a3517d230670.png)

![image](https://user-images.githubusercontent.com/27103011/43333315-94b1e98e-91ca-11e8-98c5-5bb44a94c847.png)

I don't know if it have a impact but i have this in my tsconfig.json
"compilerOptions": {
    "baseUrl": "./src/"

Any idea ?

## Environment

For Tooling issues:

Npm : 5.5.1
![image](https://user-images.githubusercontent.com/27103011/43332787-79ff3eb2-91c9-11e8-96a8-9c5c67018388.png)

- Node version:v 8.9.1
- Platform: Windows

**Comment by nimatullah** [comment]
@maciejtreder I have a project based on angular 6 

ng -v

![ng -v](https://user-images.githubusercontent.com/3712526/44944937-f80c9600-adf4-11e8-91f5-b88ec4e2ad2c.png)

The error 

![error](https://user-images.githubusercontent.com/3712526/44944943-0ce92980-adf5-11e8-9ceb-bf0d930df2c3.png)
