### ISSUE TITLE
Cannot read property 'statements' of undefined when installing @ngtoolkit/universal

### ISSUE THREAD

**Issue by lee-wilkins** [maciejtreder/ng-toolkit#398]
## I'm submitting a...

<pre><code>
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
</code></pre>

## Current behavior
Trying to install @ng-toolkit/universal in an existing Angular 6 project. 
I get the following error when installing - Cannot read property 'statements' of undefined.
The modules are not installed. 
I then have tried installing with Yarn. however this only installs the modules and doensn't run the post install scripts.

## Expected behavior
Should install completely with no errors. 

## Environment

<pre><code>
Angular CLI version 6.0.0
NPM 6.1.0
@angular-devkit/architect         0.6.0
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/pwa                      0.6.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.0
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by wylanosorio** [comment]
I encountered the same error. 

My environment is:
_Angular CLI: 6.0.8
Node: 8.11.2
OS: win32 x64
Angular: 5.2.11
... animations, common, compiler, compiler-cli, core, forms
... http, platform-browser, platform-browser-dynamic
... platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@angular/language-service         4.4.6
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              5.5.5
typescript                        2.9.2
webpack                           4.8.3_

**Comment by lee-wilkins** [comment]
@maciejtreder - be great to get some help on this.

**Comment by Ryssa** [comment]
Same here!

**Comment by Drunkenpilot** [comment]
Same error.

Angular CLI: 6.0.8
Node: 8.9.3
OS: darwin x64
Angular: 6.0.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cdk                      6.3.3
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.2.1
typescript                        2.7.2
webpack                           4.8.3
