### ISSUE TITLE
ERROR: Path "/local.js" already exist.

### ISSUE THREAD

**Issue by sauravrath** [maciejtreder/ng-toolkit#399]
## I'm submitting a 

[ ] Bug report  
> ng add @ng-toolkit/universal
Installing packages for tooling via npm.

> @ng-toolkit/serverless@1.1.40 postinstall C:\Data\Angular\sr-ng6-seo\node_modules\@ng-toolkit\serverless
> node postinstall.js

Do you ❤️ @ng-toolkit/serverless?

Star it on GitHub!
https://github.com/maciejtreder/ng-toolkit

Become a donor:
 > https://www.angular-universal-pwa.maciejtreder.com/donors

npm WARN @ng-toolkit/pwa@1.1.40 requires a peer of @angular/service-worker@^6.0.5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @ng-toolkit/universal@1.1.40
added 17 packages from 5 contributors, updated 1 package and audited 44351 packages in 47.053s
found 13 vulnerabilities (9 low, 4 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
ERROR: Path "/local.js" already exist.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

## In package
> ng -v

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 6.1.2
Node: 10.7.0
OS: win32 x64
Angular: 6.1.0
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect                 0.7.2
@angular-devkit/build-angular         0.7.2
@angular-devkit/build-optimizer      0.7.2
@angular-devkit/build-webpack       0.7.2
@angular-devkit/core                        0.7.2
@angular-devkit/schematics             0.7.2
@angular/cli                                      6.1.2
@ngtools/webpack                           6.1.2
@schematics/angular                        0.7.2
@schematics/update                        0.7.2
rxjs                                                    6.2.2
typescript                                         2.7.2
webpack                                           4.9.2

## Expected behavior
No bugs.
Added xxx packages

## Environment
Angular CLI: 6.1.2

Browser:
- Chrome (desktop) version 67.0.3396.79
 
For Tooling issues:
- Node version: 10.7.0
- Platform:  Windows 7+

Others:
IDE: Visual Studio

Is there a fix for the issue with versions higher than 6.0.7 for angular

**Comment by lucasdantasnd** [comment]
npm uninstall -g @angular/cli
npm install -g @angular/cli@6.0.8

**Comment by maciejtreder** [comment]
Duplicate of #395
