### ISSUE TITLE
ng-toolkit/universal installation issues

### ISSUE THREAD

**Issue by satyawanyadav** [maciejtreder/ng-toolkit#407]
When i run command 'ng add @ng-toolkit/universal', following error occurs

Installing packages for tooling via npm.
ERROR: Path "/local.js" already exist.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by maciejtreder** [comment]
@BoDaly Which version of CLI are you using?

**Comment by BoDaly** [comment]
@maciejtreder 
Angular CLI: 6.1.2
Node: 10.7.0
OS: win32 x64
Angular: 6.1.1

**Comment by KingDarBoja** [comment]
Closing now for housekeeping purposes.
