### ISSUE TITLE
How to run server on production machine?

### ISSUE THREAD

**Issue by kardynalek3** [maciejtreder/ng-toolkit#413]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
</code></pre>

## Current behavior

When I run <code>npm run server</code> on my server (production machine not localy) everything is ok. Server listening on port 8080 and page source is visible correct. I need to use something to run script or something which will run application and work continuously in the background. I try to use pm2 (pm2 start dist/server.js) but server is not listening on port 8080.

## Expected behavior

Execute something to run server continuously in the background.

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by maciejtreder** [comment]
What about:
`npm run server >> output.log &`?
