### ISSUE TITLE
Issue with Properties and Objects

### ISSUE THREAD

**Issue by JustClickzMedia** [maciejtreder/ng-toolkit#418]
## I'm submitting a...

<pre><code>
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
</code></pre>

## Current behavior

ran npm run build:prod
Received Error

![image](https://user-images.githubusercontent.com/42504825/44304664-787cc280-a330-11e8-9ea0-0e15eef2761a.png)

![image](https://user-images.githubusercontent.com/42504825/44304670-8fbbb000-a330-11e8-88b6-963abdd1138c.png)

details.components.html
<h1>{{ user$.name }}</h1>

<ul>
  <li><strong>Username:</strong> {{ user$.username }}</li>
  <li><strong>Email:</strong> {{ user$.email }}</li>
  <li><strong>Phone:</strong> {{ user$.phone }}</li>
</ul>

details.components.ts
import { Component, OnInit } from '@angular/core';
import { DataService } from '../data.service';
import { Observable } from 'rxjs';
import { ActivatedRoute } from "@angular/router";

@Component({
  selector: 'app-details',
  templateUrl: './details.component.html',
  styleUrls: ['./details.component.scss']
})
export class DetailsComponent implements OnInit {

  user$: Object;

  constructor(private route: ActivatedRoute, private data: DataService) { 
    this.route.params.subscribe( params => this.user$ = params.id );
  }

  ngOnInit() {
    this.data.getUser(this.user$).subscribe(
      data => this.user$ = data 
    );
  }

}

## Expected behavior

Expected to compile

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by maciejtreder** [comment]
Which ng-toolkit part you used? serverless? universal?

**Comment by JustClickzMedia** [comment]
The project started off as a serverless project.  I was testing if I could transform the project to a universal project mid stream.

Would I have to do a part manually to do this?

**Comment by maciejtreder** [comment]
@JustClickzMedia Nope. Everything should work without any manual changes.

Do you have your project hosted somewhere? GitHub? Gitlab?

**Comment by spodeniuk** [comment]
@JustClickzMedia I have the same issues. Just update webpack-cli from 2.1.4 to 3.1.1 :)
