### ISSUE TITLE
Problem with translations in source code

### ISSUE THREAD

**Issue by kardynalek3** [maciejtreder/ng-toolkit#421]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
</code></pre>

## Current behavior

I use ngx-translate and have problem with translation in source code (only in source). On front I have all translation correct but when I open source code I see something like that:
<code>
<p _ngcontent-sc1="" translate="">shared.header.offer_special_text</p><p _ngcontent-sc1="" class="subheader search" translate="">shared.header.saved_searches</p>
</code>

## Expected behavior

|I need to see translated words in source code not e.g "shared.header.saved_searches"

## Environment

<pre><code>
Angular version: X.Y.Z

Browser:
- [ ] Chrome (desktop) version XX
- [ ] Chrome (Android) version XX
- [ ] Chrome (iOS) version XX
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] Safari (iOS) version XX
- [ ] IE version XX
- [ ] Edge version XX
 
For Tooling issues:
- Node version: 8.9.4  
- Platform:  

Others:

</code></pre>

**Comment by kardynalek3** [comment]
Mr @maciejtreder ? Any help?

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
