### ISSUE TITLE
ERROR: Can't find decorator Component in ./index.ts

### ISSUE THREAD

**Issue by gerardogrimaldi** [maciejtreder/ng-toolkit#425]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[x] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
$ ng add @ng-toolkit/universal

ERROR: Can't find decorator Component in ./src/app/pages/index.ts
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

the file has this lines alone its an index for the components

the file in question has this lines:
<pre><code>
export * from './core/core.component';
export * from './show/show.component';
export * from './home/home.component';
export * from './genre/genre.component';
export * from './video/video.component';
export * from './show-videos/show-videos.component';
export * from './search/search.component';
export * from './pagenotfound/pagenotfound.component';
</code></pre>

## Expected behavior
install tooolkit by ng add @ng-toolkit/universal

## Minimal reproduction of the problem with instructions
ng add @ng-toolkit/universal on a project with an index file for some components 

## Example repository
the repository is private, sorry

## Environment

<pre><code>
Angular version: 6.1.0

- Node version: 7.8.0
- Platform:  Mac

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Closing now for housekeeping purposes.
