### ISSUE TITLE
just a quick question about how Serverless works with AWS

### ISSUE THREAD

**Issue by draytond** [maciejtreder/ng-toolkit#433]
What services in AWS are actually being used here, aside from IAM?  I see the Lamba service referenced a bunch of times, but I'm not sure how it's actually being used, since I thought Lambda was mostly just for running functions when they're triggered.  It doesn't sound like an EC2 instance is being created... but where is the code?  Is it going to an S3 bucket or something?  Maybe EFS?  And is any security set up, like an NACL or VPC?

Thanks for the insight.  I'd love to use this, but I just need to know what's going on under the hood first.  Figured I'd just ask before I dove into the source for several hours :-)

**Comment by maciejtreder** [comment]
It is using Lambda, as a back-end.

http requests goes throw the API GW and triggers Lambda to generate server-side rendered content.
