### ISSUE TITLE
deploy on asp .net core

### ISSUE THREAD

**Issue by madibi** [maciejtreder/ng-toolkit#438]
do you have any plan to deploy on asp.net core (angular template)?

**Comment by sk29110** [comment]
I have the same question. Is it supposed to work with asp.net?

**Comment by KingDarBoja** [comment]
I can be done but would require writing out code to properly use some packages like as **Universal** for .NET as the current implementation uses NodeJS/Express for the server stuff.

Closing now for housekeeping purposes.
