### ISSUE TITLE
INIT: ERROR: sink._addParentTeardownLogic is not a function

### ISSUE THREAD

**Issue by JonasJW** [maciejtreder/ng-toolkit#439]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[x] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

I entred this command:

`ng new --collection @ng-toolkit/init myApp --provider firebase --firebaseProject MyProjectID`

then I get this:

`{ provider: 'firebase',
  firebaseProject: 'MyProjectID',
  version: '6.0.8',
  skipGit: false,
  skipInstall: false,
  linkCli: false,
  commit: true,
  newProjectRoot: 'projects',
  inlineStyle: false,
  inlineTemplate: false,
  routing: false,
  prefix: 'app',
  style: 'css',
  skipTests: false,
  firebug: false,
  name: 'myApp',
  directory: 'myApp',
  viewEncapsulation: undefined,
  gaTrackingCode: undefined }
ERROR: sink._addParentTeardownLogic is not a function
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.`

## Expected behavior

I hoped that it creates a template with SSR for firebase hosting setup

## Minimal reproduction of the problem with instructions

Explained above

## Environment

<pre><code>
Angular version: 6.0.8

- Node version: 8.11.2  
- Platform:  Mac

Others:

</code></pre>

**Comment by collinclarke** [comment]
+1
