### ISSUE TITLE
ERROR: Browser build not found (lack of entry with build-angular:browser builder) in angular.json

### ISSUE THREAD

**Issue by gg-gg-v1** [maciejtreder/ng-toolkit#441]
## I'm submitting a...

<pre><code>
[* ] Bug report  
 
</code></pre>

## In package
<pre><code>
 
[ ] @ng-toolkit/universal
 
</code></pre>

## Current behavior

+ @ng-toolkit/universal@1.1.40
added 5 packages from 2 contributors, removed 4 packages, updated 1 package and audited 45016 packages in 69.861s
found 0 vulnerabilities

## Expected behavior

my purpose is to create angular universal app

## Environment
Angular CLI: 6.2.1
Node: 8.11.3
OS: win32 x64
Angular: 6.1.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.1
@angular-devkit/build-angular     0.8.1
@angular-devkit/build-optimizer   0.8.1
@angular-devkit/build-webpack     0.8.1
@angular-devkit/core              0.8.1
@angular-devkit/schematics        0.8.1
@angular/cli                      6.2.1
@ngtools/webpack                  6.2.1
@schematics/angular               0.8.1
@schematics/update                0.8.1
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.17.2

My angular.json

{
"$schema": "./node_modules/@angular/cli/lib/config/schema.json",
"version": 1,
"newProjectRoot": "projects",
"projects": {
"ntt-v1": {
"root": "",
"sourceRoot": "src",
"projectType": "application",
"prefix": "app",
"schematics": {},
"targets": {
"build": {
"builder": "@angular-devkit/build-angular:browser",
"options": {
"outputPath": "dist/ntt-v1",
"index": "src/index.html",
"main": "src/main.ts",
"polyfills": "src/polyfills.ts",
"tsConfig": "src/tsconfig.app.json",
"assets": [
"src/favicon.ico",
"src/assets"
],
"styles": [
"src/styles.css"
],
"scripts": []
},
"configurations": {
"production": {
"fileReplacements": [
{
"replace": "src/environments/environment.ts",
"with": "src/environments/environment.prod.ts"
}
],
"optimization": true,
"outputHashing": "all",
"sourceMap": false,
"extractCss": true,
"namedChunks": false,
"aot": true,
"extractLicenses": true,
"vendorChunk": false,
"buildOptimizer": true
}
}
},
"serve": {
"builder": "@angular-devkit/build-angular:dev-server",
"options": {
"browserTarget": "ntt-v1:build"
},
"configurations": {
"production": {
"browserTarget": "ntt-v1:build:production"
}
}
},
"extract-i18n": {
"builder": "@angular-devkit/build-angular:extract-i18n",
"options": {
"browserTarget": "ntt-v1:build"
}
},
"test": {
"builder": "@angular-devkit/build-angular:karma",
"options": {
"main": "src/test.ts",
"polyfills": "src/polyfills.ts",
"tsConfig": "src/tsconfig.spec.json",
"karmaConfig": "src/karma.conf.js",
"styles": [
"src/styles.css"
],
"scripts": [],
"assets": [
"src/favicon.ico",
"src/assets"
]
}
},
"lint": {
"builder": "@angular-devkit/build-angular:tslint",
"options": {
"tsConfig": [
"src/tsconfig.app.json",
"src/tsconfig.spec.json"
],
"exclude": [
"/node_modules/"
]
}
}
}
},
"ntt-v1-e2e": {
"root": "e2e/",
"projectType": "application",
"targets": {
"e2e": {
"builder": "@angular-devkit/build-angular:protractor",
"options": {
"protractorConfig": "e2e/protractor.conf.js",
"devServerTarget": "ntt-v1:serve"
},
"configurations": {
"production": {
"devServerTarget": "ntt-v1:serve:production"
}
}
},
"lint": {
"builder": "@angular-devkit/build-angular:tslint",
"options": {
"tsConfig": "e2e/tsconfig.e2e.json",
"exclude": [
"/node_modules/"
]
}
}
}
}
},
"defaultProject": "ntt-v1"
}

My package.json

{
"name": "ntt-v1",
"version": "0.0.0",
"scripts": {
"ng": "ng",
"start": "ng serve",
"build": "ng build",
"test": "ng test",
"lint": "ng lint",
"e2e": "ng e2e"
},
"private": true,
"dependencies": {
"@angular/animations": "^6.1.0",
"@angular/common": "^6.1.0",
"@angular/compiler": "^6.1.0",
"@angular/core": "^6.1.0",
"@angular/forms": "^6.1.0",
"@angular/http": "^6.1.0",
"@angular/platform-browser": "^6.1.0",
"@angular/platform-browser-dynamic": "^6.1.0",
"@angular/router": "^6.1.0",
"@ng-toolkit/universal": "^1.1.40",
"core-js": "^2.5.4",
"rxjs": "~6.2.0",
"zone.js": "~0.8.26"
},
"devDependencies": {
"@angular-devkit/build-angular": "~0.8.0",
"@angular/cli": "^6.2.1",
"@angular/compiler-cli": "^6.1.0",
"@angular/language-service": "^6.1.0",
"@types/jasmine": "~2.8.8",
"@types/jasminewd2": "~2.0.3",
"@types/node": "~8.9.4",
"codelyzer": "~4.3.0",
"jasmine-core": "~2.99.1",
"jasmine-spec-reporter": "~4.2.1",
"karma": "~3.0.0",
"karma-chrome-launcher": "~2.2.0",
"karma-coverage-istanbul-reporter": "~2.0.1",
"karma-jasmine": "~1.1.2",
"karma-jasmine-html-reporter": "^0.2.2",
"protractor": "~5.4.0",
"ts-node": "~7.0.0",
"tslint": "~5.11.0",
"typescript": "~2.9.2"
}
}
 

 Error that I am getting is 

**INFO: Project property is set to 'ntt-v1'.
ERROR: Browser build not found (lack of entry with build-angular:browser builder) in angular.json
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.**

Could someone please provide some solution ? I have already tried the solution which is given in https://github.com/maciejtreder/ng-toolkit/issues/317
my github link https://github.com/gg-gg-v1/ntt-v1

I tried following solutions:

1. ng add @ng-toolkit/universal.
2. ng add @ng-toolkit/universal --project ntt-v1
3. ng add @ng-toolkit/universal@latest
4. ng add @ng-toolkit/universal@1.1.18

**Comment by ttma1046** [comment]
same issue.

**Comment by ttma1046** [comment]
Is it because no more "architect" in the angular.json file anymore ?

**Comment by ttma1046** [comment]
By looking into the 'index.ts' in @ng-toolkit/schematics/_utils, missing "architect" in angular.json is the cause of the problem. 
@angular/cli@6.2.1 change the "architect" to be "targets" in angular.json.

**Comment by ttma1046** [comment]
`ng add @ng-toolkit/universal` works fine for a ng app 'ng new'ed by @angular/cli@6.1.5.

**Comment by gg-gg-v1** [comment]
@ttma1046 
That error is resolved but now I am getting this error if I use the command 
_ng add @ng-toolkit/universal or ng add @ng-toolkit/universal@latest_

**Installed packages for tooling via npm.
INFO: Project property is set to 'srvup'.
ERROR: Bootstrap not found in ./src/.././src/app/app.browser.module.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.**

Thanks for the reply !! :+1:

**Comment by yaashaswi** [comment]
I am getting same error @gg-gg-v1 DId you find any solution?

**Comment by RohithKP** [comment]
Hi,

I got the same error. But I just followed warning message that I got with this error. 

> WARNING: This command may not execute successfully. The package/collection may not support the 'targets' field within 'C:\Users\Rohith K P\Documents\eazylog\angular.json'. This can be corrected by renaming the following 'targets' fields to 'architect':
> 1) Line: 12; Column: 7
> 2) Line: 102; Column: 7

Basically, we need to change the 'targets' attribute inside angular.json to 'architect' then try again

**Comment by gg-gg-v1** [comment]
Thanks RohithKP but now I am not working on this.
