### ISSUE TITLE
Angular 6 SEO in legacy J2EE Apps - Suggestions are appreciated

### ISSUE THREAD

**Issue by swamytalam** [maciejtreder/ng-toolkit#453]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[x ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Hi, Thank you very much for this toolkit, it works amazing and providing SEO benefits for Angular apps for newly built apps or the Angular only apps. We have situation where we had homegrown Application build with J2EE and we are migrating to Angular on UI side but based on how its designed we cant convert the entire app as Angular so we are using hybrid approach which is main JSPs are bundled with Angular Apps. Its working great from the feature perspective. We are generating the /dist folder from angular app and copying the the resources of legacy ui/js code base, however we lost the SEO as we don't use NODE/ Express in the PROD run time.  Can you recommend some options to achieve SEO here without writing entire UI layer in Angular at a time. Thanks a lot !!

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Hello @swamytalam,

Even though the Angular documentation states at [Universal Web Server](https://angular.io/guide/universal#universal-web-servers) section:
>_Any web server technology can serve a Universal app as long as it can call Universal's renderModuleFactory() function. The principles and decision points discussed here apply to any web server technology._

The reality is that we depend on Angular Universal and its core features to support SEO. So far, looks like it is only supported on NodeJS/Express and ASP.NET as you can check at the [official repo](https://github.com/angular/universal).

But don't panic! The Angular Universal team is working on bringing this feature for different  languages [as seen in this issue](https://github.com/angular/universal/issues/1000)
