### ISSUE TITLE
Server side rendering not working on remote server

### ISSUE THREAD

**Issue by thecoconutstudio** [maciejtreder/ng-toolkit#458]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
<app-root> is being populated with the content as expected when viewing locally only(view-source:http://localhost:8080/) However when I upload it to my server <app-root> remains empty, there are no errors browser or server side. In the browser, the site appears to work correctly.

## Expected behavior
Server-side rendering should render the page so <app-root> is populated with HTML content as it is locally. And can be viewed via Page Source. 

## Minimal reproduction of the problem with instructions
shorturl.at/buKR2

## Environment

<pre><code>
Angular version: 6.0.3
- Node version: 9.10.1  
- Platform:  Linux

**Comment by freehuoshan** [comment]
i was also ecounted same problem, local environment is good but production environment not. it's may be your production firewall block, my problem is , ng-toolkit no have config server environment config replace.
resolve: edist angular.json server segment

"server": {
          "builder": "@angular-devkit/build-angular:server",
          "options": {
            "outputPath": "dist/server",
            "main": "src/main.server.ts",
            "tsConfig": "src/tsconfig.server.json"
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ]
            }
          }
        }

**Comment by abovetempo** [comment]
I am having this same problem as well. Below are my angular dependencies: I'm on angular 7

"@angular/animations": "^7.0.1",
    "@angular/cdk": "^7.0.1",
    "@angular/common": "^7.0.1",
    "@angular/compiler": "^7.0.1",
    "@angular/core": "^7.0.1",
    "@angular/forms": "^7.0.1",
    "@angular/http": "^7.0.1",
    "@angular/platform-browser": "^7.0.1",
    "@angular/platform-browser-dynamic": "^7.0.1",
    "@angular/platform-server": "^7.0.1",
    "@angular/router": "^7.0.1",
    "@ng-bootstrap/ng-bootstrap": "^3.3.1",
    **"@ng-toolkit/universal": "^1.1.41-beta.110",**
    "@nguniversal/express-engine": "^6.0.0",
    "@nguniversal/module-map-ngfactory-loader": "^6.0.0",
    "bootstrap": "^4.1.3",
    "core-js": "^2.5.4",
    "cors": "~2.8.4",
    "font-awesome": "^4.7.0",

Local Setup:
Server side rendering works fine on my local computer on localhost but it does not work when i deploy it to an ubuntu 18.04 server. All of the pages render and show fine however. Here is my local setup: I am running WAMP with apache on port 80. nodejs on localhost:8080 which is the url I use to see my local site. My api calls are all going to http://127.0.0.1:8000 which is where i have my backend rest api calls running which are running on Laravel.

Server Setup:
On my server i have apache setup to run laravel on port 81 for my api calls. I have nodejs running on localhost:80. I also have the domain http://abovetempo-laravel.localhost.com. I can go to http://abovetempo-laravel.localhost.com (which defaults to port 80) and the site loads fine and i can see everything. However nodejs throws this error on every SSR call:

ERROR HttpErrorResponse {
  headers: HttpHeaders { normalizedNames: Map {}, lazyUpdate: null, headers: Map {} },
  status: 0,
  statusText: 'Unknown Error',
  url: null,
  ok: false,
  name: 'HttpErrorResponse',
  message: 'Http failure response for (unknown url): 0 Unknown Error',
  error:
   ProgressEvent {
     type: 'error',
     target:
      XMLHttpRequest {
        onloadstart: null,
        onprogress: null,
        onabort: null,
        onerror: null,
        onload: null,
        ontimeout: null,
        onloadend: null,
        _listeners: [Object],
        onreadystatechange: null,
        _anonymous: undefined,
        readyState: 4,
        response: null,
        responseText: '',
        responseType: 'text',
        responseURL: '',
        status: 0,
        statusText: '',
        timeout: 0,
        upload: [Object],
        _method: 'GET',
        _url: [Object],
        _sync: false,
        _headers: [Object],
        _loweredHeaders: [Object],
        _mimeOverride: null,
        _request: null,
        _response: null,
        _responseParts: null,
        _responseHeaders: null,
        _aborting: null,
        _error: null,
        _loadedBytes: 0,
        _totalBytes: 0,
        _lengthComputable: false },
     currentTarget:
      XMLHttpRequest {
        onloadstart: null,
        onprogress: null,
        onabort: null,
        onerror: null,
        onload: null,
        ontimeout: null,
        onloadend: null,
        _listeners: [Object],
        onreadystatechange: null,
        _anonymous: undefined,
        readyState: 4,
        response: null,
        responseText: '',
        responseType: 'text',
        responseURL: '',
        status: 0,
        statusText: '',
        timeout: 0,
        upload: [Object],
        _method: 'GET',
        _url: [Object],
        _sync: false,
        _headers: [Object],
        _loweredHeaders: [Object],
        _mimeOverride: null,
        _request: null,
        _response: null,
        _responseParts: null,
        _responseHeaders: null,
        _aborting: null,
        _error: null,
        _loadedBytes: 0,
        _totalBytes: 0,
        _lengthComputable: false },
     lengthComputable: false,
     loaded: 0,
     total: 0 } }


I have tried other setups like running nodejs on port 8080 and laravel on port 80 with apache but that didn't show any server side rendering as well even though the site worked fine.

Another thing I noticed is after copying my angular code to my ubuntu 18.04 server if I run npm install i get this error:

npm install
loadDep:@schematics/angul ▀ ╢█████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @schematics/angular@7.0.4: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: {"node":"8.10.0","npm":"3.5.2"})
WARN engine @angular-devkit/schematics@7.0.4: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (curloadDep:@schematics/angul ▌ ╢█████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
WARN engine @angular-devkit/core@7.0.4: wanted: {"node":">= 8.9.0","npm":">= 5.5.1"} (current: npm ERR! addLocal **Could not install /var/www/html/abovetempo-angular/@ng-toolkit/_utils@^1.1.45**
npm ERR! Linux 4.15.0-38-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /var/www/html/abovetempo-angular/@ng-toolkit/_utils@^1.1.45
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/var/www/html/abovetempo-angular/@ng-toolkit/_utils@^1.1.45'
npm ERR! enoent ENOENT: no such file or directory, open '/var/www/html/abovetempo-angular/@ng-toolkit/_utils@^1.1.45'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
npm ERR! enoent


Please let me know what I can do to solve this so I can get SSR working!

**Comment by abovetempo** [comment]
This has been open for a month now. Any idea when it might get looked at?

**Comment by heavenchains** [comment]
Have you guys solved this issue ?

**Comment by abovetempo** [comment]
> Have you guys solved this issue ?

No, I have not. I have it implemented in my site but it only works when I run locally and not on my ubuntu server. I'm still waiting for help as I've had this problem since October of last year.

**Comment by KingDarBoja** [comment]
Closing now for housekeeping purposes.

Please open a new issue after trying the latest version in order to keep track of what could be causing your issue.

Cheers!
