### ISSUE TITLE
What is the meaning of this line in angular universal?

### ISSUE THREAD

**Issue by hsajwan** [maciejtreder/ng-toolkit#462]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**EDIT FROM COLLABORATOR**
_What is the meaning of this line in angular universal. and how to achieve it.You won't be able reference browser-only native objects such as window, document, navigator or location. If you don't need them on the server-rendered page, side-step them with conditional logic. Is there any way to implement angular universal on specific components or if we can make two modules and implement seo on only one or how to avoid browser-only native which are not in my app but comes from node modules in server.js while compiling._

**Comment by ishan123456789** [comment]
Well phrased question though.
But that simply means that you won't be able to access window variable like `window.localStorage` `window.innerHeight` and You can make two module one app.browser.module.ts and app.server.module.ts this way your server-side code won't break due to client-side dependencies.

**Comment by StefanKern** [comment]
> Well phrased question though.
> But that simply means that you won't be able to access window variable like `window.localStorage` `window.innerHeight` and You can make two module one app.browser.module.ts and app.server.module.ts this way your server-side code won't break due to client-side dependencies.

Do you have an example for this? I created two moduels, one for borwser, one for client and declared the components inside this modules. Now I get the error

````Uncaught Error: Template parse errors:
'xxx-test' is not a known element:
1. If 'xxx-test' is an Angular component, then verify that it is part of this module.
2. If 'xxx-test' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("
````

This SO question describes the problem pretty well, I just don't know how to resolve it.

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
