### ISSUE TITLE
Could not resolve @ng-toolkit/universal relative to app.module.ts..

### ISSUE THREAD

**Issue by Eusse** [maciejtreder/ng-toolkit#466]
## I'm submitting a...

<pre><code>
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
running `ng add @ng-toolkit/universal` will only create `utils` and `serverless` folders inside `node_modules/@ng-toolkit` on an existing project.

## Expected behavior

running  `ng add @ng-toolkit/universal` should install all dependencies required in `app.module.ts`

## Minimal reproduction of the problem with instructions

1. run `ng add @ng-toolkit/universal` on an existing angular 6 project
2. run `npm run build:prod`
3. This error will pop up:
```
ERROR in app/app.module.ts(121,1): Error during template compile of 'AppModule'
  Could not resolve @ng-toolkit/universal relative to /project/path/src/app/app.module.ts..
src/app/pages/post/post.component.ts(1,24): error TS2307: Cannot find module '@ng-toolkit/universal'.
src/app/layouts/header-nav/header-nav.component.ts(1,24): error TS2307: Cannot find module '@ng-toolkit/universal'.
src/app/layouts/slider-home/slider-home.component.ts(1,24): error TS2307: Cannot find module '@ng-toolkit/universal'.
src/app/layouts/header-nav-post/header-nav-post.component.ts(1,24): error TS2307: Cannot find module '@ng-toolkit/universal'.
src/app/directives/scrollable.directive.ts(1,24): error TS2307: Cannot find module '@ng-toolkit/universal'.
src/app/app.module.ts(1,36): error TS2307: Cannot find module '@ng-toolkit/universal'.
```

## Example repository
I cannot provide this because company privacy policies, but i will send individual resources as requested

## What is the motivation / use case for changing the behavior?
The simpliest workaround is to manually installing it with `npm install --save @ng-toolkit/universal`, but i think you should know this is happening.

## Environment

<pre><code>
Angular CLI: 6.2.3
Node: 8.11.3
OS: linux x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Others:

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5

@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.8.3
@angular/cdk                      6.4.7
@angular/cdk-experimental         6.2.0
@angular/cli                      6.2.3
@angular/fire                     5.0.2
@angular/material                 6.4.7
@ngtools/webpack                  6.1.5
@schematics/angular               0.8.3
@schematics/update                0.8.3
rxjs                              6.3.3
typescript                        2.9.2
webpack                           4.9.2

</code></pre>

**Comment by Grv90** [comment]
i am getting the same issue, any leads will be helpful.

**Comment by valentinoPereira** [comment]
Yes.. we need a resolution quick

**Comment by SwapnilSoni1999** [comment]
anyone got solution?

**Comment by psenechal** [comment]
I started receiving this error after updating from 8.0.1 => 8.0.2
Is there some breaking change in the 8.0.2 version that would cause this?

**Comment by IgorKurkov** [comment]
the same here/ Any ideas?

```
Angular CLI: 8.3.17
Node: 10.15.3
OS: win32 x64
Angular: 8.2.13
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... platform-server, router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.17
@angular-devkit/build-angular              0.803.17
@angular-devkit/build-optimizer            0.803.17
@angular-devkit/build-webpack              0.803.17
@angular-devkit/core                       8.3.17
@angular-devkit/schematics                 8.3.17
@angular/cdk                               8.2.3
@angular/cli                               8.3.17
@angular/material                          8.2.3
@ngtools/webpack                           8.3.17
@nguniversal/common                        8.1.0
@nguniversal/express-engine                8.1.1
@nguniversal/module-map-ngfactory-loader   8.1.1
@schematics/angular                        8.3.17
@schematics/update                         0.803.17
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.39.2
```

**Comment by SwapnilSoni1999** [comment]
> the same here/ Any ideas? Used only `@ng-toolkit/universal`
> `ERROR in src/app/app.module.ts(23,5): Error during te Could not resolve @ng-toolkit/universal relative to src/app/app.module.ts(23,5): `
> 
> ```
> Angular CLI: 8.3.17
> Node: 10.15.3
> OS: win32 x64
> Angular: 8.2.13
> ... animations, common, compiler, compiler-cli, core, forms
> ... language-service, platform-browser, platform-browser-dynamic
> ... platform-server, router
> 
> Package                                    Version
> --------------------------------------------------------------------
> @angular-devkit/architect                  0.803.17
> @angular-devkit/build-angular              0.803.17
> @angular-devkit/build-optimizer            0.803.17
> @angular-devkit/build-webpack              0.803.17
> @angular-devkit/core                       8.3.17
> @angular-devkit/schematics                 8.3.17
> @angular/cdk                               8.2.3
> @angular/cli                               8.3.17
> @angular/material                          8.2.3
> @ngtools/webpack                           8.3.17
> @nguniversal/common                        8.1.0
> @nguniversal/express-engine                8.1.1
> @nguniversal/module-map-ngfactory-loader   8.1.1
> @schematics/angular                        8.3.17
> @schematics/update                         0.803.17
> rxjs                                       6.4.0
> typescript                                 3.5.3
> webpack                                    4.39.2
> ```

Same here

**Comment by sudhir7890** [comment]
Same here, any one has a solution. it worked fine 1 week ago, After updating. am getting error.

<img width="991" alt="Screen Shot 2019-11-02 at 7 48 05 PM" src="https://user-images.githubusercontent.com/22940553/68078705-c81aa300-fda9-11e9-80a6-8347bad3f290.png">

**Comment by psenechal** [comment]
I just rolled back to 8.0.1 and everything is fine. Can’t imagine there are too many changes in 8.0.2, so if you need a working environment, just roll back to 8.0.1 until the issue is resolved.

**Comment by KingDarBoja** [comment]
> I just rolled back to 8.0.1 and everything is fine. Can’t imagine there are too many changes in 8.0.2, so if you need a working environment, just roll back to 8.0.1 until the issue is resolved.

To be fair, there weren't changes on the `8.0.2` version as you can check #709. The version was more like a deployment fix but for some reason, you guys are getting those errors.

I am checking it right now in a fresh test project to check out what's going on.

**Comment by KingDarBoja** [comment]
**UPDATE** After making an quick check, looks like the module isn't properly resolved as I had to use `/dist` on the import statement as seen below;

![Universal import](https://user-images.githubusercontent.com/30560560/68079577-b8a35600-fdb9-11e9-90c9-68a13674a4af.png)

@maciejtreder Any ideas what would be causing this behaviour?

**Comment by SwapnilSoni1999** [comment]
> **UPDATE** After making an quick check, looks like the module isn't properly resolved as I had to use `/dist` on the import statement as seen below;
> 
> ![Universal import](https://user-images.githubusercontent.com/30560560/68079577-b8a35600-fdb9-11e9-90c9-68a13674a4af.png)
> 
> @maciejtreder Any ideas what would be causing this behaviour?

I had tried with dist folder but it gives error while compiling, not in IDE

**Comment by KingDarBoja** [comment]
@psenechal @sudhir7890 @SwapnilSoni1999 A new version has been released, this should fix the build issue once for all 🙏

**Comment by SwapnilSoni1999** [comment]
Awesome :tada:
