### ISSUE TITLE
ng add @ng-toolkit/universal

### ISSUE THREAD

**Issue by dbarochia** [maciejtreder/ng-toolkit#468]
Installing packages for tooling via npm.
npm WARN @ng-toolkit/pwa@1.1.41 requires a peer of @angular/service-worker@^6.0.5 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @ng-toolkit/universal@1.1.41-beta.110
updated 1 package in 56.744s
Installed packages for tooling via npm.
INFO: Project property is set to 'tn-angcli'.
ERROR: Bootstrap not found in ./src/./app/app.browser.module.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.

This bug already been adressed on other issues and been fixed within the next release.
