### ISSUE TITLE
window is not defined (metronic themes)

### ISSUE THREAD

**Issue by aliBlaybel** [maciejtreder/ng-toolkit#471]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

I tried to convert this theme (https://keenthemes.com/metronic/preview/angular/demo2/) to angular universal. and I got this error. 

\dist\server.js:210612
})(window, document, 'Hammer');
   ^
ReferenceError: window is not defined

## Expected behavior

Run without error on npm run server

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
