### ISSUE TITLE
window.location is undefined..

### ISSUE THREAD

**Issue by alishakhullar** [maciejtreder/ng-toolkit#475]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

1. Added "@ng-toolkit/universal": "^1.1.41-beta.110" module.
2. Injected Window Dependency in the service.

import { WINDOW} from '@ng-toolkit/universal';

constructor(
    @Inject(WINDOW) private window: Window
  ) {
    console.log('Window' + JSON.stringify(this.window));
    console.log('location' + JSON.stringify(this.window.location));
  this.preview =  this.window.location.pathname.includes('private') || this.window.location.origin.includes('localhost'); }
}

Output:
"this.window" gives me [Window{"navigator":{"userAgent":"fakeAgent"}}]
"this.window.location" gives me "undefined"

I'm unable to access any property inside the window object.

## Expected behavior

Should be able to access the window object and its properties in the code as the window dependency has been injected.

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
