### ISSUE TITLE
npm run build:prod showing error TS2307: Cannot find module 'src/app/app.service'.

### ISSUE THREAD

**Issue by BattiniSantthosh** [maciejtreder/ng-toolkit#476]
App service is working fine on "ng serve" command and when running build it is showing error. like blow.
Note: AppSerive is using in lazy module.

ERROR in : Can't resolve all parameters for HomeComponent in D:/Angular/awesome-seo/src/app/home/home/home.component.ts: (?).
src/app/home/home/home.component.ts(2,28): error TS2307: Cannot find module 'src/app/app.service'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! awesome-seo@0.0.0 build:server:prod: `ng run awesome-seo:server && webpack --config webpack.server.config.js --progress --colors`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the awesome-seo@0.0.0 build:server:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\santh\AppData\Roaming\npm-cache\_logs\2018-10-13T11_25_06_480Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! awesome-seo@0.0.0 build:prod: `npm run build:server:prod && npm run build:browser:prod`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the awesome-seo@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

Am using the below versions

"webpack": "^4.20.2",
"webpack-cli": "^3.1.1",
"webpack-dev-server": "^3.1.9",

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
