### ISSUE TITLE
Bootstrap not found in ./src/.././src/app/app.browser.module.ts. error

### ISSUE THREAD

**Issue by abhinesh128** [maciejtreder/ng-toolkit#479]
Installing packages for tooling via npm.
INFO: Project property is set to 'admitkard-v2'.
ERROR: Bootstrap not found in ./src/.././src/app/app.browser.module.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by Lekhulal** [comment]
Same issue : 
> ng add @ng-toolkit/universalInstalling packages for tooling via npm.
INFO: Project property is set to 'ev'.
ERROR: Bootstrap not found in ./src/.././src/app/app.browser.module.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
