### ISSUE TITLE
not able to access any window objects after using @Inject(WINDOW) private window: Window

### ISSUE THREAD

**Issue by venukumarvk** [maciejtreder/ng-toolkit#481]
Not able to use window objects after using @Inject(WINDOW) private window: Window on constructor

this.router.events.subscribe(event => {
      if (event instanceof NavigationEnd) {
         this.window.ga('set', 'page', event.urlAfterRedirects);
         this.window.ga('send', 'pageview');
      }
    });

Showing error as window is not defined.

**Comment by KingDarBoja** [comment]
Closing now for housekeeping purposes.
