### ISSUE TITLE
ERROR: Bootstrap not found in ./src/.././src/app/app.browser.module.ts.

### ISSUE THREAD

**Issue by cathycheng2001** [maciejtreder/ng-toolkit#485]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

when ran, ng add @ng-toolkit/universal, I got 
INFO: Project property is set to 'awesome-seo'.
ngular CLI: 7.0.3
Node: 9.9.0
OS: darwin x64
Angular: 6.1.8
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.0.3
@angular/cli                      7.0.3
@angular/platform-server          6.1.10
@ngtools/webpack                  6.0.8
@schematics/angular               7.0.3
@schematics/update                0.10.3
rxjs                              6.3.2
typescript                        2.7.2
webpack                           4.8.3

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Bodeclas** [comment]
@cathycheng2001 Hello! Your app.browser.module.ts must be similar to this:

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { AppModule } from './app.module';

@NgModule({
  bootstrap: [AppComponent], // <-- this is important
  imports: [
    BrowserModule.withServerTransition({ appId: 'app-root' }),
    AppModule
  ]
})
export class AppBrowserModule {}
```

**Comment by DerKarim** [comment]
Hey!
This solution worked for me: https://stackoverflow.com/a/55167210/9530936 .
