### ISSUE TITLE
ERROR: Bootstrap not found in ./src/.././src/app/app.browser.module.ts.

### ISSUE THREAD

**Issue by rakeshanexpert** [maciejtreder/ng-toolkit#490]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by Bodeclas** [comment]
@rakeshanexpert Hello! Your app.browser.module.ts must be similar to this

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { AppModule } from './app.module';

@NgModule({
  bootstrap: [AppComponent], // <-- this is important
  imports: [
    BrowserModule.withServerTransition({ appId: 'app-root' }),
    AppModule
  ]
})
export class AppBrowserModule {}
```

**Comment by pritamcb** [comment]
My app.browser.module.ts looks the same but still getting the same error again and again.

```
import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { AppModule } from './app.module';

@NgModule({
       bootstrap: [AppComponent],
       imports: [
              BrowserModule.withServerTransition({appId: 'app-root'}),
              AppModule
       ]
})
export class AppBrowserModule {}
```

Error received after executing 

> ng add @ng-toolkit/universal

> Installing packages for tooling via npm.
> INFO: Project property is set to 'angular-landing'.
> ERROR: Bootstrap not found in ./src/.././src/app/app.browser.module.ts.
> ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
> INFO: stacktrace has been sent to tracking system.
> Nothing to be done.

**Comment by stijnwesterhof** [comment]
Any fix?

**Comment by Mds92** [comment]
Any fix?
