### ISSUE TITLE
Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by COLTstreet** [maciejtreder/ng-toolkit#493]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[X] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Installed @ngToolkit with npm install. Tried to create a new project with the following command: 
ng new --collection @ng-toolkit/init requestPWA

## Expected behavior

New application boilerplate would be produced

## Error Message
![image](https://user-images.githubusercontent.com/1413857/47671427-de35c800-db85-11e8-97e8-9098459ac3d6.png)

## Environment

<pre><code>
Angular version: 6.2.6

- Node version: v8.12.0
- Platform:  Windows

**Comment by maks7777a21** [comment]
have the same problem(
did you found the solution ?

**Comment by Sangarllo** [comment]
Same for me. :(

**Comment by nolafs** [comment]
Use Node version v10.8.0 or above and that should fix it for you
