### ISSUE TITLE
Property 'null' does not exist on type 'AppComponent' with @ng-toolkit/universal

### ISSUE THREAD

**Issue by muthufmass** [maciejtreder/ng-toolkit#508]
## I'm submitting a...

<pre><code>
[x] Bug report  

ERROR in src/app/app.component.ts(12,18): error TS2339: Property 'null' does not exist on type 'AppComponent'.
src/app/app.component.ts(13,18): error TS2339: Property 'null' does not exist on type 'AppComponent'.
src/app/app.component.ts(17,18): error TS2339: Property 'null' does not exist on type 'AppComponent'.
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/universal
</code></pre>

## Current behavior
On kickstarter project following these steps, it throws error on first time build.

## Expected behavior
App should smoothly run with npm run build:prod

## Minimal reproduction of the problem with instructions
*STEPS TO REPRODUCE*
<pre><code>
ng new book
cd book
ng add @angular/pwa
ng add @ng-toolkit/universal
ng add @ng-toolkit/pwa --serverModule src/app/app.server.module.ts
npm run build:prod
</code></pre>

## What is the motivation / use case for changing the behavior?
Smooth creation of project

## Environment
<pre><code>
Angular version: 7.0.6
- Node version: v10.3.0
- Platform:  Mac
</code></pre>

**Comment by muthufmass** [comment]
### Code auto created after the step ng add @ng-toolkit/universal at src/app/app.component.ts

```
import { SwUpdate } from '@angular/service-worker';
import { Component , OnInit} from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent implements OnInit {
  title = 'book';
public ngOnInit():void {
        if (this.null && this.null.isEnabled) {
            this.null.available.subscribe((evt) => {
                console.log('service worker updated');
            });
    
            this.null.checkForUpdate().then(() => {
                // noop
            }).catch((err) => {
                console.error('error when checking for update', err);
            });
        }}


 constructor(private swUpdate: SwUpdate) {}
}
```

**Comment by Daaron3** [comment]
Change nulll to swUpdate

    public ngOnInit():void {
        if (this.swUpdate.isEnabled) {
            this.swUpdate.available.subscribe((evt) => {
                console.log('service worker updated');
            });

            this.swUpdate.checkForUpdate().then(() => {
                // noop
            }).catch((err) => {
                console.error('error when checking for update', err);
            });
        }
    }

**Comment by muthufmass** [comment]
got fixed in the next version release. changed the same, thanks for the reply!
