### ISSUE TITLE
Bootstrap not found in ./src/.././src/app/app.browser.module.ts.

### ISSUE THREAD

**Issue by pritamgb** [maciejtreder/ng-toolkit#510]
## I'm submitting a...

<pre>
ng add @ng-toolkit/universal
Installing packages for tooling via npm.
INFO: Project property is set to 'angular-landing'.
ERROR: Bootstrap not found in ./src/.././src/app/app.browser.module.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.
<code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Minimal reproduction of the problem with instructions
When executing `ng add @ng-toolkit/universal` on my existing project.

## Environment

<pre><code>
Angular version: 7.0.2

- Node version: v10.11.0  
- Platform: Mac 
</code></pre>

**Comment by stijnwesterhof** [comment]
Any fix?

**Comment by rsjonnalagadda** [comment]
Running into the same issue. Not able to find a solution. Any help is appreciated.

**Comment by JasonDeLierre** [comment]
Can't find solution. Help pls

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
