### ISSUE TITLE
Unable to inject window into component 

### ISSUE THREAD

**Issue by calbear47** [maciejtreder/ng-toolkit#515]
## I'm submitting a...

<pre><code>
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

I have successfully installed the universal toolkit. I can also run the server locally with node, and my homepage renders correctly. 

However, in the server logs and the chrome devtools I see this error: 

```
ERROR { Error: Uncaught (in promise): Error: StaticInjectorError(AppServerModule)[HomePageComponent -> InjectionToken ng-toolkit-window]:
  StaticInjectorError(Platform: core)[HomePageComponent -> InjectionToken ng-toolkit-window]:
    NullInjectorError: No provider for InjectionToken ng-toolkit-window!
```

## Expected behavior

After importing `NgtUniversalModule` into AppModule, I should be able to inject the `window` into a component as the docs suggest:
```
import { WINDOW } from '@ng-toolkit/universal';
...
constructor(@Inject(WINDOW) private window: Window) { }
```

## Environment

<pre><code>
- Angular version: 7.1.0
- Node version: 9.11
- Platform:  Mac
-  "@ng-toolkit/universal": "^1.1.47",
-   "@nguniversal/express-engine": "^7.0.2",
 -  "@nguniversal/module-map-ngfactory-loader": "^7.0.2"
</code></pre>

**Comment by mattmeye** [comment]
@calbear47 Do you have a solution yet?

**Comment by harshasaha** [comment]
Got any solution ? @calbear47 @mattmeye

**Comment by mattmeye** [comment]
@harshasaha Not yet, but i find an interesting article which propose a solution. But i didnt tested it: https://blog.realworldfullstack.io/real-world-app-part-23-ssr-with-angular-universal-637ec8490c44

**Comment by rts-cwalker** [comment]
Getting the same error here. :/ Hopefully a fix will be coming soon.

**Comment by rts-cwalker** [comment]
Think I just figured out my issue for seeing this error during unit tests. Just add `@Optional()` before the `@Inject(WINDOW)` call in the constructors

**Comment by rts-cwalker** [comment]
Nevermind.. reporter shows passing, but logs show errors.

**Comment by rts-cwalker** [comment]
Seems like i fixed my latest issue by doing the following:
```
window: Window;
constructor(@Optional() @Inject(WINDOW) private window1: Window) {
        if (window1) {
            this.window = window1;
        } else {
            this.window = window;
        }
}
```

**Comment by KingDarBoja** [comment]
Closing now for housekeeping reason.
