### ISSUE TITLE
DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods inste ad.

### ISSUE THREAD

**Issue by ObadaDarwish** [maciejtreder/ng-toolkit#516]
## DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.

<pre><code>
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/universal
</code></pre>

## Current behavior
steps:
1- npm run build:prod
dist folder is create with two folders [server,browser] and one file [server.js]
2- npm run server (local test)
listens to port 8080 with the deprecation errors but still works i can see page source and the full html is there

when i run "node ./dist/server.js" or "pm2 start ./dist/server.js" it fails with  the same deprecation error.

Any help...

## Package.json
<pre>
<code>
{
 "build:server:prod": "ng run gbarena-frontend:server && webpack --config webpack.server.config.js --progress --colors",
    "build:browser:prod": "node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build",
    "build:prod": " npm run build:browser:prod && npm run build:server:prod",
    "server": "node local.js"
}
</code>
</pre>
## Environment

<pre><code>
Angular version: 7.0.3

- Node version: 11.2.0  
- Npm : 6.4.1
- Platform:  Windows
- @ng-toolkit/universal : "^1.1.47"
</code></pre>

## webpack.server.config.js
<pre><code>

    // Work around for https://github.com/angular/angular-cli/issues/7200

    const path = require('path');
    const webpack = require('webpack');

    module.exports = {
      entry: {
        server: './server.ts',
      },
      target: 'node',
      resolve: { extensions: ['.ts', '.js'] },
      externals: [/(node_modules|main\..*\.js)/,'utf-8-validate','bufferutil'],
      output: {
        libraryTarget: 'commonjs2',
        path: path.join(__dirname, 'dist'),
        filename: '[name].js'
      },
      module: {
        rules: [
          { test: /\.ts$/, loader: 'ts-loader' }
        ]
      },
      optimization: {
        minimize: false
      },
      plugins: [
        new webpack.ContextReplacementPlugin(
          // fixes WARNING Critical dependency: the request of a dependency is an expression
          /(.+)?angular(\\|\/)core(.+)?/,
          path.join(__dirname, 'src'), // location of your src
          {} // a map of your routes
        ),
        new webpack.ContextReplacementPlugin(
          // fixes WARNING Critical dependency: the request of a dependency is an expression
          /(.+)?express(\\|\/)(.+)?/,
          path.join(__dirname, 'src'),
          {}
        )
      ]
    }

</code></pre>

**Comment by smartHasmukh** [comment]
@ObadaDarwish @maciejtreder I am getting this error also


![universal](https://user-images.githubusercontent.com/8941195/54007936-6195a480-418a-11e9-80a8-50c1a38bfae2.png)

**Comment by rubinchyk** [comment]
The same situation, Linux. After restart system, site stop working...

**Comment by fakesamgregory** [comment]
Also getting this error and has completely taken my site down

**Comment by KingDarBoja** [comment]
Closing now for housekeeping purposes.
