### ISSUE TITLE
how to implement it at production server?

### ISSUE THREAD

**Issue by abhhaycompaddicts** [maciejtreder/ng-toolkit#528]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by abhhaycompaddicts** [comment]
It is working fine at local server but when I run ng build --prod & I upload the project on the server it is not going to work

**Comment by Sangarllo** [comment]
If you want to server it in localstorage in production mode:

`npm run build:prod && npm run server`

If you want to deploy it:

`npm run build:prod:deploy`

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
