### ISSUE TITLE
lambda.js

### ISSUE THREAD

**Issue by macorifice** [maciejtreder/ng-toolkit#546]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[x] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Minimal reproduction of the problem with instructions
ng add @ng-toolkit/serverless --provider aws

ERROR: Path "/lambda.js" does not exist.

## Environment

<pre><code>
Angular CLI: 7.1.2
Angular: 6.1.10

- Node version: v8.11.3
- Platform: Mac
- OS: darwin x64

Others:
Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        7.1.2
@angular/cdk                      7.1.1
@angular/cli                      7.1.2
@angular/fire                     5.1.1
@angular/material                 7.1.1
@ngtools/webpack                  6.0.8
@schematics/angular               7.1.2
@schematics/update                0.11.2
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.8.3

**Comment by ponsipi** [comment]
I'm facing the same issue but my OS is Windows

**Comment by mc-lovin** [comment]
Facing the same issue when trying to migrate from an already created universal project

**Comment by KingDarBoja** [comment]
Closed for housekeeping reasons.

A new version will arrive soon which should fix these issues.
