### ISSUE TITLE
TS2688: Cannot find type definition file for 'dist', 'node_modules', 'src', 'test'

### ISSUE THREAD

**Issue by nextlevelshit** [maciejtreder/ng-toolkit#551]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

I've added `ng-toolkit` to an existing Angular 6 web application. After running the install commands, I've run into errors while `yarn build:prod`.

## Expected behavior

Distribute application in `/dist` folder.

## Minimal reproduction of the problem with instructions

Run `yarn build:prod` or `npm run build:prod`

## Example repository

https://github.com/nextlevelshit/nls-ng6-donatello/tree/feature/seo (**Note:** Better do not clone that branch, it is full of images and other binary stuff).

## What is the motivation / use case for changing the behavior?

The error claims to have issues with `tsconfig.ts`, but I cannot find anything in the error trace helping me to fix the problem.

## Environment

<pre><code>
Angular CLI: 6.0.8
Node: 10.0.0
OS: linux x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@angular/platform-server          6.1.10
@ngtools/webpack                  6.0.8
@schematics/angular               7.0.7
@schematics/update                0.6.8
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.8.3

</code></pre>

## tsconfig.ts from stack trace

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es6",
    "typeRoots": [
      "node_modules/@types",
      "node_modules/ng2-slugify",
      "node_modules/nls-directree-searchonly",
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

## Full error message

```
WARNING in ./node_modules/@angular/core/fesm5/core.js
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./server.ts 4982:15-36 3:0-47 10:0-14

WARNING in ./node_modules/@angular/core/fesm5/core.js
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./server.ts 4994:15-102 3:0-47 10:0-14

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in /home/nextlevelshit/Coding/nls-ng6-donatello/tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'dist'.

ERROR in /home/nextlevelshit/Coding/nls-ng6-donatello/tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'node_modules'.

ERROR in /home/nextlevelshit/Coding/nls-ng6-donatello/tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'src'.

ERROR in /home/nextlevelshit/Coding/nls-ng6-donatello/tsconfig.json
[tsl] ERROR
      TS2688: Cannot find type definition file for 'test'.

```

**Comment by KingDarBoja** [comment]
Closing now as this is not related to the package.

You should check for StackOverflow for these kind of questions.

Cheers!
