### ISSUE TITLE
ERROR: Bootstrap not found in ./src/./app/app.browser.module.ts.

### ISSUE THREAD

**Issue by nolafs** [maciejtreder/ng-toolkit#556]
## I'm submitting a...

<pre><code>
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Cannot add angular universal. Running ng add @ng-toolkit/universal will result in the following error.

ERROR: Bootstrap not found in ./src/./app/app.browser.module.ts.

The file does exist and path is correct. 

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  -v10.13.0
- Platform:  Mac

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Closed for housekeeping reasons.
