### ISSUE TITLE
adding robots.txt and sitemap.xml 

### ISSUE THREAD

**Issue by gp187** [maciejtreder/ng-toolkit#559]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[x] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[x] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
adding robots.txt and sitemap.xml to the `/src` directory and adding them to `angular.json` `build.options.assets` works fine and on build they appear in the `dist` directory. They can also be fetched when running a local server

## Expected behavior
expecting the same behaviour remotely but instead I get the `404` set by the website. It's trying to go to a angular route

## What is the motivation / use case for changing the behavior?
We all need sitemap.xml and robots.txt

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: 10.9.1
- Platform:  Ubuntu 18

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
@gp187 Good idea, I do think it can be easily done by providing default configuration for both files.
