### ISSUE TITLE
Error while running : ng add @ng-toolkit/universal to existing project

### ISSUE THREAD

**Issue by neophyte1** [maciejtreder/ng-toolkit#566]
## In package
[ ] @ng-toolkit/universal

## Current behavior
Installing packages for tooling via npm.
~7.0.0
7
ERROR: Unexpected token ] in JSON at position 1486

## Environment
Angular version: Angular CLI version (7.3.1)

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
