### ISSUE TITLE
 Can't resolve all parameters when build using ng toolkit

### ISSUE THREAD

**Issue by bitcko** [maciejtreder/ng-toolkit#568]
I am trying to build my app using ng toolkit universal but errors are showing:

![screen shot 2019-02-18 at 10 01 05 pm](https://user-images.githubusercontent.com/38560105/52974058-e7fb6980-33c8-11e9-92bf-8e179a17a74c.png)
![screen shot 2019-02-18 at 10 01 37 pm](https://user-images.githubusercontent.com/38560105/52974059-e7fb6980-33c8-11e9-84d4-95e07ee88a08.png)

Using ng build --prod works fine.

**Comment by pankajhartron** [comment]
I am facing this issue too.
Have you found any solution yet?

**Comment by pankajhartron** [comment]
@maciejtreder Urgent help needed.

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
