### ISSUE TITLE
AWS Deployment Documentation

### ISSUE THREAD

**Issue by marcusingogo** [maciejtreder/ng-toolkit#569]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ x] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[x] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
Lack of documentation regarding aws config for deploy. 
**Instructions are as follows:**
AWS Lambda & Google Cloud Functions
ng add @ng-toolkit/serverless --provider aws
Deploy to "maintenance link" (non customized - ie: https://123456.execute-api.eu-central-1.amazonaws.com/production)

npm run build:serverless:deploy
Deploy to customized link (example.com):

npm run build:prod:deploy

--------
Obviously some AWS config needs to be performed somewhere:

If i just run
npm run build:serverless:deploy
I get an error:
 ServerlessError: AWS provider credentials not found. Learn how to set up AWS provider credentials in our docs here: http://bit.ly/aws-creds-setup.

The link for the docs is a 404.

Could you please help me with more detailed instructions on what steps need to be taken to ensure npm run build:serverless:deploy will successfully deploy to the correct aws account and lamda?

**Comment by KingDarBoja** [comment]
Please follow this [tutorial](https://www.youtube.com/watch?v=N-6LtzJezsk).

Closing now for housekeeping reasons.
