### ISSUE TITLE
Error while adding ng-toolkit

### ISSUE THREAD

**Issue by salmankaludi** [maciejtreder/ng-toolkit#570]
## I'm submitting a...

Angular CLI: 6.0.8
Node: 10.4.1
OS: win32 x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.6.8
@angular-devkit/build-optimizer   0.6.8
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@ngtools/webpack                  6.0.8
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.8.3

Error

ERROR: Bootstrap not found in ./src/.././src/app/app.browser.module.ts.
![error](https://user-images.githubusercontent.com/20137483/53166880-7ad01a00-35fc-11e9-84d7-148d1dc12a02.png)

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes
