### ISSUE TITLE
Could not install /var/www/project-dir/@ng-toolkit/_utils@1.1.51

### ISSUE THREAD

**Issue by SilverFoxA** [maciejtreder/ng-toolkit#571]
## I'm submitting a...

<pre><code>
[ x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ x ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

https://imgur.com/a/MS590Wt

## Expected behavior

`ng-toolkit` directory should be referenced from the `node_modules` directory.

## Minimal reproduction of the problem with instructions

Run `npm install` on live server with the following angular/cli versions

https://imgur.com/a/XOIaXvW

## Environment

<pre><code>
Angular version: 7.1.4

- Node version: 8.10.0  
- Platform: Linux x64 

Others:

</code></pre>

**Comment by nikhilthakur001** [comment]
Same issue.

**Comment by egiev** [comment]
Same issue.

**Comment by immport-devteam** [comment]
Running into the same issue. Please see below.  
17185 verbose node v10.15.3
17186 verbose npm  v6.4.1
17187 error code E500
17188 error 500 javax.servlet.ServletException: java.lang.IllegalArgumentException: Name starts with '.' or '_': _utils: @ng-toolkit/_utils@1.1.45

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
