### ISSUE TITLE
Unexpected token / in JSON at position 859

### ISSUE THREAD

**Issue by MehmetSert** [maciejtreder/ng-toolkit#572]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

Installed packages for tooling via npm.
^7.2.7
7
ERROR: Unexpected token / in JSON at position 859
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by MehmetSert** [comment]
I had a command that was in the comment line on my package.json file. I deleted it and fix.

**Comment by gaurav112** [comment]
Have the same issue
Installed packages for tooling via npm.
ERROR: Unexpected token / in JSON at position 1280
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
