### ISSUE TITLE
Convert existing project to  Angular Universal by @ng-toolkit/universal 

### ISSUE THREAD

**Issue by haticesebli** [maciejtreder/ng-toolkit#573]
I'm trying to convert my existing project to Angular Universal project.
When i run the "ng add @ng-toolkit/universal" command,it just creates "@ng-toolkit/universal": "^1.1.40" in the package.json not the other scripts like 

"build:server:prod": "ng run myApp:server && webpack --config webpack.server.config.js --progress --colors",
"build:browser:prod": "ng build --prod",
"build:prod": "npm run build:server:prod && npm run build:browser:prod",
"server": "node local.js"
OR main.server.ts.
And It gives
Skipping installation: Package already installed
INFO: Project property is set to 'AppName.
ERROR: Can't find decorator Component in ./src/app/module/app/AppRouting.ts
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new

**Comment by krishnakarthikeyan** [comment]
I'm trying to convert my existing project to Angular Universal project.
the error like this.. how to set up SEO friendly Angular7 website

-- INFO: Project property is set to 'wepop-digital'.
ERROR: Bootstrap not found in ./src/.././src/app/app.browser.module.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stack trace has been sent to the tracking system.
Nothing to be done.

**Comment by DivyaSaiBalakavi** [comment]
Even i am getting the similar issue while making angular application universal.
ERROR: project_1.project is not a project function.

**Comment by Suman96C** [comment]
when i am converting angular project to universal. webpack is installed automatically then when i'm trying to build for ssr it is showing message that webpack-cli and webpack-command both are installed. then i uninstalled one of then still it is not working.  also node dist/server command is not recognized by angular-cli.  

please help..

**Comment by KingDarBoja** [comment]
Closed for housekeeping reasons.

Also, you have a wrong `@ng-toolkit/universal` version installed. It is a known issue, so please run this instead `ng add @ng-toolkit/universal@7.1.2`.

Cheers!
