### ISSUE TITLE
Could not generate QR Code: external_canvas_default.a is not a constructor

### ISSUE THREAD

**Issue by smartHasmukh** [maciejtreder/ng-toolkit#575]
## I have used angular 6 and ng-toolkit for SEO. in angular project one package for QRCODE Generator. when I am run project with node server then getting error
 

<pre><code>
[x] Bug report  
</code></pre>

## In package
<pre><code>
[x] @ng-toolkit/universal
</code></pre>

## Current behavior

Getting error `Could not generate QR Code: external_canvas_default.a is not a constructor`

## Environment

<pre><code>
Angular version: ^7.2.7
Angular CLI: ~7.3.1

- Node version: 10.15.1  
- Platform: Linux  

Others: "angular2-qrcode": "^2.0.1", for qrcode generator

</code></pre>

**Comment by smartHasmukh** [comment]
@maciejtreder Can you help me please

**Comment by adskiremote** [comment]
You should consider removing from ssr pages using isPlatformBrowser as a quick solution.

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.

Also, looks like it is related to the `angular2-qrcode` itself since it does throw an error that's related to AOT builds.
