### ISSUE TITLE
ERROR: Cannot read property 'unshift' of undefined i'm getting this error when adding SSR to exist angular 6 project 

### ISSUE THREAD

**Issue by mohamedelmancy** [maciejtreder/ng-toolkit#578]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by servrox** [comment]
Just created a fresh angular project and tried running:
` ng add @ng-toolkit/universal` -> `ERROR: Cannot read property 'unshift' of undefined`

### ng --version
```
Angular CLI: 8.0.1
Node: 10.13.0
OS: win32 x64
Angular: 8.0.0
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
```

**Comment by fabian-parra** [comment]
Also fresh project using `ng create my-app`
When execute:
```
ng add @ng-toolkit/universal
ERROR: Cannot read property 'unshift' of undefined
```
More information:
```
$ ng --version

Angular CLI: 8.0.1
Node: 12.4.0
OS: linux x64
Angular: 8.0.0
... common, compiler, compiler-cli, core, language-service
... platform-browser, platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.1
@angular-devkit/build-angular     0.800.1
@angular-devkit/build-optimizer   0.800.1
@angular-devkit/build-webpack     0.800.1
@angular-devkit/core              8.0.1
@angular-devkit/schematics        8.0.1
@angular/cli                      8.0.1
@ngtools/webpack                  8.0.1
@schematics/angular               8.0.1
@schematics/update                0.800.1
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0
```

**Comment by pamuller** [comment]
Existing project :

When execute:
ng add @ng-toolkit/universal
ERROR: Cannot read property 'unshift' of undefined


$ ng --version
Angular CLI: 8.0.3
Node: 12.4.0
OS: win32 x64
Angular: 8.0.1
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@angular/http                     7.2.1
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.30.0

**Comment by camolift29** [comment]
I found a solution. After trying different ways for fixing this bug, I found that when you execute the command ng add @ng-toolkit/universal, in package.json appears the new dependency, but in 1.1.2 version (at least for me). Then I searched in official page of ng-toolkit-universal and the last version is 7.1.2. So I deleted the node_modules folder, then I've changed the version in package.json to 7.1.2, I executed the command npm install, then ng add @ng-toolkit/universal@7.1.2 and it worked!

I hope this option help you.

And sorry if a made a mistake in my english writting. I'm from Latin America.

**Comment by ultraMIND** [comment]
Same issue with an angular 8 project

**Comment by ultraMIND** [comment]
It seems ng add @ng-toolkit/universal@7.1.2 did the trick for me

**Comment by Selast** [comment]
> It seems ng add @ng-toolkit/universal@7.1.2 did the trick for me

Same for me.
Though it's using ng-universal for angular 7 and not 8.

**Comment by jpthirumalai** [comment]
Fixed the error "cannot read property 'unshift' of undefined" while executing ng add @ng-toolkit/universal using the steps:
Step 1:@ng-toolkit/universal, in package.json appears the new dependency, (might be with older version dependency but in 1.1.2 version "@ng-toolkit/universal": "1.1.21",)
Step 2:Delete universal folder in the location node_modules@ng-toolkit
Step 3: Change the line in package.json to 7.1.2:: "@ng-toolkit/universal": "7.1.2",
Step 4: now run the command ng add @ng-toolkit/universal@7.1.2

**Comment by KingDarBoja** [comment]
Closed for housekeeping reasons.
