### ISSUE TITLE
Error installing @ng-toolkit/universal: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by Snixells** [maciejtreder/ng-toolkit#585]
## I'm submitting a...

<pre><code>
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

When I am running  <code> ng add @ng-toolkit/universal </code> it says
<code> { build:
   { builder: '@angular-devkit/build-angular:browser',
     options:
      { outputPath: 'dist/wordcloud-website-angular',
        index: 'src/index.html',
        main: 'src/main.ts',
        polyfills: 'src/polyfills.ts',
        tsConfig: 'src/tsconfig.app.json',
        assets: [Array],
        styles: [Array],
        scripts: [Array] },
     configurations: { production: [Object] } },
  serve:
   { builder: '@angular-devkit/build-angular:dev-server',
     options: { browserTarget: 'wordcloud-website-angular:build' },
     configurations: { production: [Object] } },
  'extract-i18n':
   { builder: '@angular-devkit/build-angular:extract-i18n',
     options: { browserTarget: 'wordcloud-website-angular:build' } },
  test:
   { builder: '@angular-devkit/build-angular:karma',
     options:
      { main: 'src/test.ts',
        polyfills: 'src/polyfills.ts',
        tsConfig: 'src/tsconfig.spec.json',
        karmaConfig: 'src/karma.conf.js',
        styles: [Array],
        scripts: [],
        assets: [Array] } },
  lint:
   { builder: '@angular-devkit/build-angular:tslint',
     options: { tsConfig: [Array], exclude: [Array] } } }</code>

<code>ERROR: Cannot read property 'length' of undefined</code>

## Expected behavior

It should install ng-toolkit/universal

## Minimal reproduction of the problem with instructions

I am installing ng-toolkit on my angular project 

## Environment

<pre><code>
Angular version: 7.3.7

- Node version: 8.12.0 
- Platform:  Windows 

Others:

</code></pre>

**Comment by stevespectre** [comment]
Same issue here : / I haven't found any solution yet. 
Angular: CLI 7.3.5
Angular: 7.2.9

**Comment by helphin07** [comment]
Having the same issue. Any updates on this?

**Comment by KingDarBoja** [comment]
Closed as fixed within the next release which is gonna be launched soon.
