### ISSUE TITLE
No Errors in build or when running server but the Browser show nothing

### ISSUE THREAD

**Issue by immad-hamid** [maciejtreder/ng-toolkit#586]
## I am able to create the prod build with no errors plus I am able to run the server, again without any errors
- I did had some path issues which I had before but after fixing them, things were working fine with no issues at all

## Current behavior
As there's not much to say other then that it's just not working after creating the build and running it. 

## I tried to figure out things by doing these:
- I tried changing the port.
- I tried running the solution on a different machine
- I updated the packages
- and been searching on the Internet

## Expected behavior
- I should be working

## Here's the link to the repo page, if you would like to check
- https://github.com/immad-hamid/website-csn (development branch, master still work fine)

## In package
@angular-devkit/architect                0.13.0
@angular-devkit/build-angular        0.13.7
@angular-devkit/build-optimizer     0.13.7
@angular-devkit/build-webpack      0.13.7
@angular-devkit/core                       7.3.0
@angular-devkit/schematics            7.3.0
@angular/cdk                                   7.3.2
@angular/cli                                     7.3.0
@angular/compiler-cli                      7.2.11
@angular/material                            7.3.2
@angular/platform-browser             6.1.10
@angular/platform-server                6.1.10
@ngtools/webpack                           7.3.7
@schematics/angular                        7.3.0
@schematics/update                        0.13.0
rxjs                                                    6.3.3
typescript                                          3.2.4
webpack                                           4.29.0
</code></pre>

Angular version: 7.2.3
... animations, common, compiler, core, forms, http
... language-service, platform-browser-dynamic, router

- Node version: 8.12.0
- Platform:  win32 x64

Any help would be great. Thanks in advance

**Comment by HMubaireek** [comment]
I'm facing the same issue

**Comment by immad-hamid** [comment]
> I'm facing the same issue.
> 
> Edit: After spending sometime, the solution was:
> Go to tsconfig.server.json and put this in include property:
> "include": [
> "**/*.ts"
> ]

@HMubaireek I'll check and will get back here in any case. Thanks

**Comment by immad-hamid** [comment]
> I'm facing the same issue.
> 
> Edit: After spending sometime, the solution was:
> Go to tsconfig.server.json and put this in include property:
> "include": [
> "**/*.ts"
> ]

@HMubaireek It's not the issue here, I have checked. BTW thanks

**Comment by immad-hamid** [comment]
@HMubaireek can you please share your imports in these two files, i-e app.server.module.ts and app.browser.module.ts

Somehow changing the items sequence in imports array this started working but now server-side rendering is not working. :(

**Comment by HMubaireek** [comment]
This is my app.server.module.ts

`import {NgModule} from '@angular/core';
import {ServerModule, ServerTransferStateModule} from '@angular/platform-server';
import {ModuleMapLoaderModule} from '@nguniversal/module-map-ngfactory-loader';

import {AppModule} from './app.module';
import {AppComponent} from './app.component';
import { NoopAnimationsModule } from '@angular/platform-browser/animations';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
import * as fs from 'fs';
import { BrowserModule } from '@angular/platform-browser';
import { ServiceWorkerModuleMock } from './services/service-worker.mock.module';
import { Observable, Observer } from 'rxjs';
import { LazyUniversalModuleLoaderProvider } from 'localize-router-lazy-universal-module-loader';

export function universalLoader(): TranslateLoader {
    return {
        getTranslation: (lang: string) => {
            return Observable.create((observer: Observer<any>) => {
                observer.next(JSON.parse(fs.readFileSync(`./dist/assets/i18n/${lang}.json`, 'utf8')));
                observer.complete();
            });
        }
    } as TranslateLoader;
}

@NgModule({
    imports: [
        BrowserModule.withServerTransition({
            appId: 'app-root'
        }),
        AppModule,
        ServerModule,
        NoopAnimationsModule,
        ModuleMapLoaderModule,
        ServerTransferStateModule,
        TranslateModule.forRoot({
            loader: {provide: TranslateLoader, useFactory: universalLoader}
        }),
        ServiceWorkerModuleMock
    ],
    bootstrap: [AppComponent],
    providers: [LazyUniversalModuleLoaderProvider]
})
export class AppServerModule {}
`

And this is my app.browser.module.ts:

`import { NgModule } from '@angular/core';
import { BrowserModule, BrowserTransferStateModule } from '@angular/platform-browser';
import { AppComponent } from './app.component';
import { AppModule } from './app.module';
import { BrowserAnimationsModule } from '@angular/platform-browser/animations';
import { ServiceWorkerModule } from '@angular/service-worker';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { TranslateLoader, TranslateModule } from '@ngx-translate/core';
import {TransferHttpCacheModule} from '@nguniversal/common';

export function HttpLoaderFactory(http: HttpClient) {
    return new TranslateHttpLoader(http);
}

@NgModule({
    bootstrap: [ AppComponent ],
    imports: [
        BrowserAnimationsModule,
        BrowserModule.withServerTransition({
            appId: 'app-root'
        }),
        AppModule,
        ServiceWorkerModule.register('/ngsw-worker.js'),
        HttpClientModule,
        TranslateModule.forRoot({
            loader: {provide: TranslateLoader, useFactory: HttpLoaderFactory, deps: [HttpClient]}
        }),
        BrowserTransferStateModule,
        TransferHttpCacheModule,
    ]
})
export class AppBrowserModule {}
`
I have also updated the packages:

`{
  "name": "myapp",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "run-p build:watch credentials",
    "build": "ng build",
    "test": "ng test --code-coverage",
    "lint": "ng lint --fix",
    "e2e": "ng e2e",
    "build:browser:prod": "ng build --prod",
    "build:browser:serverless": "ng build --prod --base-href /production/",
    "build:serverless": "npm run build:browser:serverless && npm run build:server:serverless",
    "build:prod": "npm run build:client-and-server-bundles && npm run webpack:server",
    "server": "node local.js",
    "build:prod:deploy": "npm run build:prod && npm run deploy",
    "build:serverless:deploy": "npm run build:serverless && npm run deploy",
    "deploy": "serverless deploy",
    "build:server:prod": "ng run myapp:server && webpack --config webpack.server.config.js --progress --colors",
    "build:server:serverless": "ng run myapp:server:serverless && webpack --config webpack.server.config.js --progress --colors",
    "postinstall": "node credentials.js && opencollective postinstall",
    "credentials": "node credentials.js",
    "build:watch": "ng serve",
    "build:dev": "run-p test:watch start",
    "webpack:server": "webpack --config webpack.server.config.js --progress --colors",
    "build:client-and-server-bundles": "ng build --prod && ng run myapp:server",
    "test:watch": "ng test --watch --code-coverage"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~7.2.0",
    "@angular/cdk": "^7.3.6",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/forms": "~7.2.0",
    "@angular/http": "^7.2.11",
    "@angular/material": "^7.3.6",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/platform-server": "^7.2.11",
    "@angular/router": "~7.2.0",
    "@angular/service-worker": "^7.2.11",
    "@gilsdav/ngx-translate-router": "^1.0.2",
    "@nguniversal/common": "^7.1.1",
    "@nguniversal/express-engine": "^7.1.1",
    "@nguniversal/module-map-ngfactory-loader": "^7.1.1",
    "@ngx-translate/core": "^10.0.1",
    "@ngx-translate/http-loader": "^3.0.1",
    "@nicky-lenaers/ngx-scroll-to": "^2.0.0",
    "aws-serverless-express": "^3.2.0",
    "core-js": "^2.5.4",
    "cors": "~2.8.4",
    "cp-cli": "^1.1.0",
    "localize-router": "^2.0.0-RC.2",
    "localize-router-lazy-universal-module-loader": "^1.0.0-ntr",
    "ngx-toastr": "^10.0.2",
    "primeicons": "^1.0.0",
    "primeng": "^7.1.0",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "typescript-collections": "^1.3.2",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.7",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "cp-cli": "^1.1.0",
    "cpy-cli": "^1.0.1",
    "decompress": "^4.2.0",
    "decompress-targz": "^4.1.1",
    "express": "^4.15.2",
    "http-server": "^0.10.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "karma-phantomjs-launcher": "^1.0.4",
    "node-wget": "^0.4.2",
    "npm-run-all": "^4.1.2",
    "opencollective": "^1.0.3",
    "pre-commit": "^1.2.2",
    "protractor": "~5.4.0",
    "reflect-metadata": "^0.1.10",
    "serverless": "^1.39.1",
    "serverless-apigw-binary": "^0.4.4",
    "sinon": "^4.5.0",
    "ts-loader": "4.2.0",
    "ts-node": "~7.0.0",
    "tslint": "^5.7.0",
    "typescript": "~3.2.2",
    "webpack-cli": "^3.3.0"
  },
  "collective": {
    "type": "opencollective",
    "url": "https://opencollective.com/ng-toolkit"
  }
}
`

I would suggest you to try cloning the starter app and compare it with yours:
`git clone https://github.com/maciejtreder/ng-toolkit.git
cd ng-toolkit/application
ng serve`

**Comment by immad-hamid** [comment]
For anyone having any such issue please refer here:
https://stackoverflow.com/questions/55407541/exclude-component-that-breaks-angular-universal/55592745#55592745

Maciej personally came forward to resolve the issue and answered on stackoverflow. Great Guy
