### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by sandeepGhotra** [maciejtreder/ng-toolkit#588]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by sivadinesh1** [comment]
same error

**Comment by elefantelimpio** [comment]
Try tu upload "webpack-cli" in package.json to 
`    "webpack-cli": "^3.1.2"`

**Comment by KingDarBoja** [comment]
Closed as fixed at #606.
