### ISSUE TITLE
It is throwing error "Cannot find module '@schematics/angular/utility/project-targets' " while adding ng add @ng-toolkit/universal

### ISSUE THREAD

**Issue by nagendrapantham** [maciejtreder/ng-toolkit#589]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by nagendrapantham** [comment]
Angular Environment
Angular CLI: 6.1.5
Node: 8.12.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.7.5
@angular-devkit/build-angular     0.7.5
@angular-devkit/build-optimizer   0.7.5
@angular-devkit/build-webpack     0.7.5
@angular-devkit/core              0.7.5
@angular-devkit/schematics        0.7.5
@angular/cli                      6.1.5
@ngtools/webpack                  6.1.5
@schematics/angular               0.7.5
@schematics/update                0.7.5
rxjs                              6.3.3
typescript                        2.7.2
webpack                           4.9.2

**Comment by KingDarBoja** [comment]
Closing now for housekeeping purposes.
