### ISSUE TITLE
installing issue with ng add @ng-toolkit/universal

### ISSUE THREAD

**Issue by Data-Online** [maciejtreder/ng-toolkit#590]
## I'm submitting a...

<pre><code>
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Error during install:
Invalid regular expression flags
.\ClientApp\node_modules\@ng-toolkit\universal\schematics.js:162
            tree.overwrite(`/${options.serverFileName}`, test_1.getFileContent(tree, `/${options.serverFileName}`).replace(/\/\/ Start up the Node server.*/gs, '').replace('const app = express();', 'export const app = express();'));

## Environment

<pre><code>
Angular CLI: 7.3.3
Node: 8.9.3
OS: win32 x64
Angular: 7.2.6
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.3
@angular-devkit/build-angular     0.11.4
@angular-devkit/build-optimizer   0.11.4
@angular-devkit/build-webpack     0.11.4
@angular-devkit/core              7.3.3
@angular-devkit/schematics        7.3.3
@angular/cli                      7.3.3
@ngtools/webpack                  7.1.4
@schematics/angular               7.3.3
@schematics/update                0.13.3
rxjs                              6.4.0
typescript                        3.1.6
webpack                           4.23.1

Others:

</code></pre>

**Comment by thinkingmedia** [comment]
You have to run a version of NodeJS that supports JavaScript ES2018.

http://2ality.com/2017/07/regexp-dotall-flag.html

Upgrade your NodeJS to the latest LTS version.

https://nodejs.org/en/

**Comment by KingDarBoja** [comment]
Closing now for housekeeping reasons.
