### ISSUE TITLE
ERROR: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by todsapornm** [maciejtreder/ng-toolkit#591]
## I'm submitting problem about creating project with ng-toolkit/init
I have used command
$ng new --collection @ng-toolkit/init myapp

Then I got an error

<pre><code>
aotmaha:~/workspace (master) $ ng new --collection @ng-toolkit/init myapp
INFO: Project property is set to 'myapp'.
ERROR: Cannot read property 'length' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
ERROR: The file (myapp/package.json) does not exist.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Bugsnag:  Encountered an uncaught error, terminating…
Error: spawn /bin/sh ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:362:16)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickDomainCallback (internal/process/next_tick.js:219:9)
aotmaha:~/workspace (master) $ 
</code></pre>

I don't know what happen. I can not fix this problem by myself.
Help me pleaseeee. Thanks

**Comment by KingDarBoja** [comment]
This is a known bug on the `init` package, should be fixed in the next release.

Closing now for housekeeping reasons.
