### ISSUE TITLE
error

### ISSUE THREAD

**Issue by master-song** [maciejtreder/ng-toolkit#593]
Installing packages for tooling via npm.
{ build:
   { builder: '@angular-devkit/build-angular:browser',
     options:
      { outputPath: 'dist',
        index: 'src/index.html',
        main: 'src/main.ts',
        polyfills: 'src/polyfills.ts',
        tsConfig: 'src/tsconfig.app.json',
        assets: [Array],
        styles: [Array],
        scripts: [Array] },
     configurations: { production: [Object] } },
  serve:
   { builder: '@angular-devkit/build-angular:dev-server',
     options: { browserTarget: 'mdb-angular-pro:build' },
     configurations: { production: [Object] } },
  'extract-i18n':
   { builder: '@angular-devkit/build-angular:extract-i18n',
     options: { browserTarget: 'mdb-angular-pro:build' } },
  test:
   { builder: '@angular-devkit/build-angular:karma',
     options:
      { main: 'src/test.ts',
        polyfills: 'src/polyfills.ts',
        tsConfig: 'src/tsconfig.spec.json',
        karmaConfig: 'src/karma.conf.js',
        styles: [Array],
        scripts: [],
        assets: [Array] } },
  lint:
   { builder: '@angular-devkit/build-angular:tslint',
     options: { tsConfig: [Array], exclude: [Array] } } }
ERROR: Invalid rule result: Function().
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by KingDarBoja** [comment]
This bug among others are fixed within the next release.

Closing now for housekeeping purposes.
