### ISSUE TITLE
Fail installation

### ISSUE THREAD

**Issue by izquierdogalan** [maciejtreder/ng-toolkit#595]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[X] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: 7.0

- Node version: 8.11.4
- Platform:  Ubuntu

</code></pre>
<code>
➜  leadin_front git:(ci) ✗ ng add @ng-toolkit/pwa     
Skipping installation: Package already installed
ERROR: Cannot read property 'architect' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.
</code>

**Comment by mike-cao** [comment]
I'm experiencing the same on Windows 10 with Angular 7.2 and Node 10.15.3. Fresh project using ng new and after ng adding @ng-toolkit/universal and @angular/pwa. I had no problem when adding it just 2 weeks ago for a different project.

**Comment by mike-cao** [comment]
This issue appears to have been fixed in the latest release
