### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by mshzsh** [maciejtreder/ng-toolkit#598]
ERROR: Cannot read property 'length' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new

but my codes are true!

**Comment by olteanubogdan** [comment]
I just completed the angular tutorial Tour of Heroes (https://angular.io/tutorial). Then I tried to add the @ng-toolkit/universal and I got the same error.
Sad panda is sad.

**Comment by malyalavenu** [comment]
I have the same issue. The package.json doesn't have the scripts for deploy
`  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node local.js",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run website:server:production",
    "server": "node local.js",
    "build:prod": "npm run build:ssr",
    "serve:prerender": "node static.js",
    "build:prerender": "npm run build:prod && node dist/prerender.js"
  },`

**Comment by gaurav150493** [comment]
In my new project when i am trying to add angular universal with this command ng add @ng-toolkit/universal i am getting the same error

**Comment by pankajhartron** [comment]
Same here, any update on this ?

**Comment by Andrewshrtstp** [comment]
same issue for me

**Comment by shazvan275** [comment]
same issue for me

**Comment by pankajhartron** [comment]
Just a poll, Have you guys installed serverless?

I observed that when I try to install universal after installing serverless it gives me the above error.
But I was able to install universal after uninstalling serverless and clearing node-modules. Everything worked perfectly.

**Comment by vinilanzoni** [comment]
+1

**Comment by KingDarBoja** [comment]
This bug among others shall be fixed with the next release.

Closing now for housekeeping purposes.
