### ISSUE TITLE
Throwing error with  Invalid rule result: Function().

### ISSUE THREAD

**Issue by ymchandra** [maciejtreder/ng-toolkit#599]
## I'm submitting a...

<pre><code>
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular CLI: 6.0.5
Node: 8.11.2
OS: win32 x64
Angular: 6.0.3

Others:
Throwing error  as "Invalid rule result: Function()."
Initially it showed error at 'Cannot find module '@schematics/angular/utility/dependencies' and I have added 'npm i --save @schematics/angular'. And then I tried 'ng add @ng-toolkit/universal' which resulting in error 

ERROR: Invalid rule result: Function().
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new

</code></pre>

**Comment by B-PRAVEEN** [comment]
Same problem.

**Comment by KingDarBoja** [comment]
This bug among others shall be fixed with the next release.

Closing now for housekeeping purposes.
