### ISSUE TITLE
ERROR: Invalid rule result: Function().

### ISSUE THREAD

**Issue by Shashi0838** [maciejtreder/ng-toolkit#600]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by dm-grinko** [comment]
@Shashi0838 Did you find a solution. I have the same error

**Comment by KingDarBoja** [comment]
This bug among others shall be fixed with the next release.

Closing now for housekeeping purposes.
