### ISSUE TITLE
How to fix “ReferenceError: window is not defined” error in angular 6 universal server.js

### ISSUE THREAD

**Issue by gitulaga** [maciejtreder/ng-toolkit#601]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

I execute the following command on angular cli command line tool, to install universal package for angular6 'ng add @ng-toolkit/universal'. It installed good,after that i execute npm run build:prod and it also runs very well. Now finally I run 'npm run server'.But this throws me error without giving me launching url.
ReferenceError: window is not defined
    at Object.exports.__esModule (D:\ANGULAR2\dist\server.js:122614:14)
    at __webpack_require__ (D:\ANGULAR2\dist\server.js:122314:31)
    at Object.exports.__esModule (D:\ANGULAR2\dist\server.js:122359:19)
    at __webpack_require__ (D:\ANGULAR2\dist\server.js:122314:31)
    at Object.exports.__esModule (D:\ANGULAR2\dist\server.js:122343:21)
    at __webpack_require__ (D:\ANGULAR2\dist\server.js:122314:31)
    at D:\ANGULAR2\dist\server.js:122334:19
    at D:\ANGULAR2\dist\server.js:122337:11
    at webpackUniversalModuleDefinition (D:\ANGULAR2\dist\server.js:122292:21)
    at Object.exports.__esModule (D:\ANGULAR2\dist\server.js:122294:4)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! rssmtechwood@0.0.0 serverrl `node local.js`
npm ERR! Exit status 1

## Expected behavior

when I run this command npm run server, I expect the following lines
rssmtechwood@0.0.0 server:D:\ANGULAR2\rssmtechwood
node local.js
Listening on http://localhost:8080

## Minimal reproduction of the problem with instructions

Step 1: I execute ng add @ng-toolkit/universal in angular/cli command prompt. Note: It produces server.js file automatically in dist folder. 
Step 2: Executes npm run build:prod 
Step 3: Finally he executes npm run server.
## Environment

<pre><code>
Angular CLI: 6.2.9
Angular version: 6.1.0

- Node version: 8.12  
- Platform:  Windows 8.1

Others:

</code>IDE- Visual Studio Code</pre>

**Comment by vahidvdn** [comment]
@gitulaga `window` is not accessible on the server side. You must not use it directly.

**Comment by gitulaga** [comment]
Thanks for replying. I didn't write any code on server side. When in run this command 
ng add @ng-toolkit/universal on angular/cli, it automatically windows related code inside server.js file.
So what I have to do to achieve this,
when I run this command npm run server on angular/cli, I expect the following lines
rssmtechwood@0.0.0 server:D:\ANGULAR2\rssmtechwood
node local.js
Listening on http://localhost:8080

**Comment by vahidvdn** [comment]
@gitulaga 

>  I didn't write any code on server side.

You are not supposed to write any code on the server side. You may used `window` in your angular project. You must know that your angular codes run in server side.

And when you use `window` in your client side (or maybe in a 3rd party library that doesn't support Angular Universal) you get that error.

So, first of all, search about `window` to see where you used. Then I will tell you what to do. (If you are sure you didn't use `window`, there might be a library that uses it directly)

**Comment by gitulaga** [comment]
Ah, great answer, Thanks for your guidance, I searched my whole project and at last I found 'window' keyword in Index.html , I have included google tag manager and global site tag scripts, which uses window keyword.
**code snippet:-**
 ```
window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
```
Just to overcome this error, I have removed google tag manager and global site tag scripts from index.html page.
Again i repeat these 2 steps
**Step 1:** Executes npm run build:prod
output:This produces browser,server folders and server.js file automatically.
**Step 2:** Finally executes npm run server.

**so the same error shows in server.js:-**
ReferenceError: window is not defined
at Object.exports.__esModule (D:\ANGULAR2\dist\server.js:122614:14)

**Comment by vahidvdn** [comment]
@gitulaga That's obviously still there is somewhere you used `window` in your app. Or as I mentioned, maybe you installed a plugin or library that doesn't support Angular Universal.

**Comment by gitulaga** [comment]
how to find which plugin or library that doesn't support angular universal

**Comment by vahidvdn** [comment]
Can I see the full log of you errors after running `npm run server` ?

For a very basic step, just comment the components in your html that you use from an external library. Something like: `<slider></slider> `

**Comment by gitulaga** [comment]
Here is my error log after running npm run server:-

D:\ANGULAR2\USMTECHWORLD\dist\server.js:122610
                var work = window.document.createElement('div');
                           ^

ReferenceError: window is not defined
    at Object.exports.__esModule (D:\ANGULAR2\USMTECHWORLD\dist\server.js:122610:14)
    at __webpack_require__ (D:\ANGULAR2\USMTECHWORLD\dist\server.js:122310:31)
    at Object.exports.__esModule (D:\ANGULAR2\USMTECHWORLD\dist\server.js:122355:19)
    at __webpack_require__ (D:\ANGULAR2\USMTECHWORLD\dist\server.js:122310:31)
    at Object.exports.__esModule (D:\ANGULAR2\USMTECHWORLD\dist\server.js:122339:21)
    at __webpack_require__ (D:\ANGULAR2\USMTECHWORLD\dist\server.js:122310:31)
    at D:\ANGULAR2\USMTECHWORLD\dist\server.js:122330:19
    at D:\ANGULAR2\USMTECHWORLD\dist\server.js:122333:11
    at webpackUniversalModuleDefinition (D:\ANGULAR2\USMTECHWORLD\dist\server.js:122288:21)
    at Object.exports.__esModule (D:\ANGULAR2\USMTECHWORLD\dist\server.js:122290:4)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! usmtechworld@0.0.0 server: `node local.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usmtechworld@0.0.0 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\raj\AppData\Roaming\npm-cache\_logs\2019-04-22T11_57_59_904Z-debug.log

**Comment by vahidvdn** [comment]
This is not obvious where this line is: `window.document.createElement('div')`

As I mentioned, You have to test each library by commenting it's component in you own component. When you found it, you must check it with`*ngIf` to run it only in client side.

**Comment by gitulaga** [comment]
I am checking by creating sample or dummy angular app and installing the universal package for angular6 and hope will come back with good results.

**Comment by gitulaga** [comment]
Thanks, **Vahidvdn** so much...  Actually, it is amazon ads not working in my site, if I comment then angular universal is working.
Amazon ads are called by using postscribe package in my typescript code.
I don't know why it is not supporting for angular6 universal

**Comment by vahidvdn** [comment]
@gitulaga Ok, you don't have to run Amazon ads in server side.

The only benefit that server side rendering brings to you, is being SEO friendly. In this case, it's not important. Just skip it in server side and let Angular runs it in the client side.

For now you can close this issue.

**Comment by KamranTaghaddos** [comment]
@vahidvdn's strategy will work for code which we write ourselves, but what if we are using a third party library which accesses window, document or other DOM globals?

JavaScript within a third-party library may throw errors due to attempting to access these globals during our server render, but we have no control over the library’s code. In this case, we can install a library such as a **domino**, and then create a shim for the window and document objects in the server

**Comment by vahidvdn** [comment]
@KamranTaghaddos Of course, you can send a pull request to the 3rd party library. As I did [here](https://github.com/wittlock/ngx-image-zoom/pull/27).
