### ISSUE TITLE
webpack-cl Error

### ISSUE THREAD

**Issue by ferdipekcikmaz** [maciejtreder/ng-toolkit#604]
UPDATE ng-toolkit.json (228 bytes)
npm ERR! code ENOVERSIONS
**npm ERR! No valid versions available for webpack-cl**
npm ERR! A complete log of this run can be found in:

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
