### ISSUE TITLE
when installing error: build prop and similar tools do not work

### ISSUE THREAD

**Issue by frtlec** [maciejtreder/ng-toolkit#605]
Skipping installation: Package already installed
ERROR: Cannot read property 'length' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
npm WARN @angular/animations@7.2.12 requires a peer of @angular/core@7.2.12 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@7.2.14 requires a peer of @angular/animations@7.2.14 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@7.2.14 requires a peer of @angular/common@7.2.14 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@7.2.14 requires a peer of @angular/compiler@7.2.14 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@7.2.14 requires a peer of @angular/core@7.2.14 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@7.2.14 requires a peer of @angular/http@7.2.14 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@7.2.14 requires a peer of @angular/platform-browser@7.2.14 but none is installed. You must install peer dependencies yourself.
npm WARN @angular/platform-server@7.2.14 requires a peer of @angular/platform-browser-dynamic@7.2.14 but none is installed. You must install peer dependencies yourself.
npm WARN @ng-toolkit/pwa@7.1.1 requires a peer of @angular/service-worker@^7.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-jwt@0.2.3 requires a peer of @angular/core@^2.0.0||^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-jwt@0.2.3 requires a peer of @angular/http@^2.0.0||^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-jwt@0.2.3 requires a peer of rxjs@^5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.3.1 requires a peer of popper.js@^1.14.7 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

These issues are being fixed in the next release so stay sharp for the launch day.

Cheers!
