### ISSUE TITLE
npm run build:prod, hatası " TS2307: Cannot find module"

### ISSUE THREAD

**Issue by frtlec** [maciejtreder/ng-toolkit#608]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
npm run build: prod, I get the following error when I run the command

ERROR in src\app\app.module.ts(169,7): Error during template compile of 'AppModule'
  Could not resolve src/shared/confirm-equal-validator.directive relative to [object Object]..
src/app/home/stream-videos/stream-videos.component.ts(3,31): error TS2307: Cannot find module 'src/app/services/router.service'.
src/app/home/stream-videos/stream-videos.component.ts(5,27): error TS2307: Cannot find module 'src/app/models/Twchannel'.
src/app/admin/login/login.component.ts(2,32): error TS2307: Cannot find module 'src/app/app_classes/globalvariable'.
src/app/admin/login/login.component.ts(3,29): error TS2307: Cannot find module 'src/app/services/auth.service'.
src/app/admin/login/login.component.ts(4,27): error TS2307: Cannot find module 'src/app/models/loginUser'.
src/app/home/instagram/instagram.component.ts(2,34): error TS2307: Cannot find module 'src/app/services/instagram.service'.
src/app/home/instagram/instagram.component.ts(3,33): error TS2307: Cannot find module 'src/app/models/instagramPhotos'.
src/app/home/instagram/instagram.component.ts(5,30): error TS2307: Cannot find module 'src/app/app.component'.
src/app/home/instagram/instagram.component.ts(6,30): error TS2307: Cannot find module 'src/app/nav/nav.component'.
src/app/admin/streams-ctrl/streams-ctrl.component.ts(2,32): error TS2307: Cannot find module 'src/app/services/streams.service'.
src/app/admin/streams-ctrl/streams-ctrl.component.ts(3,25): error TS2307: Cannot find module 'src/app/models/streams'.
src/app/admin/videos-ctrl/videos-ctrl.component.ts(2,24): error TS2307: Cannot find module 'src/app/models/videos'.
src/app/admin/videos-ctrl/videos-ctrl.component.ts(3,31): error TS2307: Cannot find module 'src/app/services/videos.service'.
src/app/home/stream-videos/stream-details/stream-details.component.ts(3,32): error TS2307: Cannot find module 'src/app/services/streams.service'.
src/app/home/stream-videos/stream-details/stream-details.component.ts(4,25): error TS2307: Cannot find module 'src/app/models/streams'.
src/app/admin/modal/modal.component.ts(10,37): error TS2307: Cannot find module 'src/app/models/achievementsAddEdit'.
src/app/admin/modal/modal.component.ts(11,37): error TS2307: Cannot find module 'src/app/services/achievements.service'.
src/app/admin/modal/modal.component.ts(13,32): error TS2307: Cannot find module 'src/app/app_classes/globalvariable'.
src/app/admin/achievements-ctrl/achievements-ctrl.component.ts(2,37): error TS2307: Cannot find module 'src/app/services/achievements.service'.
src/app/admin/achievements-ctrl/achievements-ctrl.component.ts(3,30): error TS2307: Cannot find module 'src/app/services/games.service'.
src/app/admin/achievements-ctrl/achievements-ctrl.component.ts(4,23): error TS2307: Cannot find module 'src/app/models/games'.
src/app/admin/achievements-ctrl/achievements-ctrl.component.ts(5,57): error TS2307: Cannot find module 'src/app/models/achievements'.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unchained@0.0.0 build:client-and-server-bundles: `ng build --prod && ng run Unchained:server:production`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unchained@0.0.0 build:client-and-server-bundles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zafer.Kirik\AppData\Roaming\npm-cache\_logs\2019-04-24T12_47_29_290Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unchained@0.0.0 build:ssr: `npm run build:client-and-server-bundles && npm run compile:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unchained@0.0.0 build:ssr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zafer.Kirik\AppData\Roaming\npm-cache\_logs\2019-04-24T12_47_29_333Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! unchained@0.0.0 build:prod: `npm run build:ssr`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the unchained@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Zafer.Kirik\AppData\Roaming\npm-cache\_logs\2019-04-24T12_47_29_374Z-debug.log

## Example repository
https://github.com/frtlec/unchained.git
add
ng add @ ng-toolkit / universal --http false

## Environment

<pre><code>
Angular version:Angular 7

- Node version:v11.14.0
- Platform: Windows

Others:

</code></pre>
{
  "name": "unchained",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node local.js",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run Unchained:server:production",
    "server": "node local.js",
    "build:prod": "npm run build:ssr",
    "serve:prerender": "node static.js",
    "build:prerender": "npm run build:prod && node dist/prerender.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^7.2.14",
    "@angular/cdk": "^7.3.7",
    "@angular/common": "^7.2.14",
    "@angular/compiler": "^7.2.14",
    "@angular/core": "^7.2.14",
    "@angular/forms": "^7.2.14",
    "@angular/http": "^7.2.14",
    "@angular/material": "^7.3.7",
    "@angular/platform-browser": "^7.2.14",
    "@angular/platform-browser-dynamic": "^7.2.14",
    "@angular/platform-server": "~7.2.0",
    "@angular/router": "^7.2.14",
    "@auth0/angular-jwt": "^2.1.0",
    "@fortawesome/free-solid-svg-icons": "^5.7.2",
    "@ng-bootstrap/ng-bootstrap": "^4.1.1",
    "@ng-toolkit/universal": "^7.1.1",
    "@nguniversal/common": "0.0.0",
    "@nguniversal/express-engine": "0.0.0",
    "@nguniversal/module-map-ngfactory-loader": "0.0.0",
    "angular2-jwt": "^0.2.3",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.4",
    "domino": "^2.1.3",
    "enhanced-resolve": "^3.3.0",
    "express": "^4.15.2",
    "font-awesome": "^4.7.0",
    "jquery": "^3.4.0",
    "ng2-file-upload": "^1.3.0",
    "rxjs": "~6.3.3",
    "rxjs-compat": "^6.5.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "^0.13.8",
    "@angular/cli": "^7.3.8",
    "@angular/compiler-cli": "^7.2.14",
    "@angular/language-service": "^7.2.14",
    "@fortawesome/fontawesome-free": "^5.7.2",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.0.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.4.0",
    "ts-loader": "^5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2",
    "webpack-cli": "^3.1.0"
  }
}

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
