### ISSUE TITLE
troble with @ng-toolkit/pwa e @ng-toolkit/universal

### ISSUE THREAD

**Issue by Jeffrs123** [maciejtreder/ng-toolkit#609]
## I'm submitting a...

<pre><code>
[ x ] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ x ] @ng-toolkit/universal
[ x ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

The @ng-toolkit/universal stops working, after install the @ng-toolkit/pwa.

Or if the reverse is made. The SEO also stops of working.

## Expected behavior

Try to have the Service Worker and the SEO working.

## Minimal reproduction of the problem with instructions

Generate new angular app.
Run
ng add @angular/pwa
ng add @ng-toolkit/pwa

npm start

||  Everything goes ok.

Then run:

ng add @ng-toolkit/universal
npm run build:prod
npm run server

||  Everything goes. SEO don't work.

If made the reverse instalation:
The SEO works only if the @ng-toolkit/pwa it's not't added to the project.

## Environment

<pre><code>
Angular CLI: 7.0.7
Node: 8.12.0
OS: linux x64
Angular: 7.0.4
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, platform-server, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.10.7
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              7.0.7
@angular-devkit/schematics        7.0.7
@angular/cli                      7.0.7
@ngtools/webpack                  7.0.7
@schematics/angular               7.0.7
@schematics/update                0.10.7
rxjs                              6.3.3
typescript                        3.1.6
webpack                           4.19.1
</code></pre>

**Comment by KingDarBoja** [comment]
I am closing this now since those issues shall be fixed with the next release, hopefully it will be delivered soon.

Cheers!
