### ISSUE TITLE
Create new project - could not read package.json

### ISSUE THREAD

**Issue by call-me-adas** [maciejtreder/ng-toolkit#610]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Cant create new project ng new --collection @ng-toolkit/init myApp

could not read package.json

**Comment by KingDarBoja** [comment]
This bug is fixed on the next release which should be available soon.

Closing now for housekeeping purposes.
