### ISSUE TITLE
ERROR: The file (./src/app/app/app.component.ts) does not exist.

### ISSUE THREAD

**Issue by shijileshepr** [maciejtreder/ng-toolkit#614]
INFO: Project property is set to 'fuse'.
ERROR: The file (./src/app/app/app.component.ts) does not exist.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
