### ISSUE TITLE
i get this error, Please help

### ISSUE THREAD

**Issue by shijilesh** [maciejtreder/ng-toolkit#615]
ERROR in : Can't resolve all parameters for signinservice in C:/Projects/Final/Customer/Universal/src/app/pages/sign-in/sign-in.service.ts: (?, ?, [object Object], [object Object], [object Object], [object Object]).
src/app/app.module.ts(85,5): error TS1136: Property assignment expected.

## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Closed as this is not related to this package.

For these kind of issues, please take a look at StackOverflow or any programming forum to get help.
