### ISSUE TITLE
The file (/server.ts) does not exist.

### ISSUE THREAD

**Issue by DattatrayAbnawe** [maciejtreder/ng-toolkit#616]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

I have upgraded my existing project to angular 7 and trying to install angular universal package, but it giving me below error

![Capture](https://user-images.githubusercontent.com/50701923/57850344-55b60680-77fb-11e9-9198-e2bf64d9a6ff.JPG)

Please help!!

**Comment by EltonWhybrow** [comment]
Hi, I'm having trouble installing universal on my ng7 project, did you resolve your issue?
ERROR: Main file (/src/main.server.ts) not found

Thanks

**Comment by ricardosaracino** [comment]
https://github.com/angular/angular/issues/21516#issuecomment-357733501

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
