### ISSUE TITLE
Cannot find module '@schematics/angular/utility/project-targets

### ISSUE THREAD

**Issue by sandeep1k** [maciejtreder/ng-toolkit#620]
+ @ng-toolkit/universal@7.1.2
added 20 packages from 50 contributors and audited 34083 packages in 28.617s
found 82 vulnerabilities (12 low, 33 moderate, 37 high)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
ERROR: Cannot find module '@schematics/angular/utility/project-targets'
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
