### ISSUE TITLE
Amazon ads could not be added to my angular website, why?

### ISSUE THREAD

**Issue by gitulaga** [maciejtreder/ng-toolkit#621]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

when I add amazon affliate ads to my angular website , currently it is showing
error.

## Expected behavior

I need to put amazon ads to my angular6 website.

## Minimal reproduction of the problem with instructions

ngAfterViewInit()
{
 postscribe('#amaangadv', `<script type="text/javascript" language="javascript"> var aax_size='300x250'; var aax_pubname = 'rttstsre-72'; var aax_src='302';</script>
  <script type="text/javascript">amzn_assoc_ad_type ="responsive_search_widget"; amzn_assoc_tracking_id ="rttstsre-72"; amzn_assoc_marketplace ="amazon"; amzn_assoc_region ="IN"; amzn_assoc_placement =""; amzn_assoc_search_type = "search_widget";amzn_assoc_width ="260"; amzn_assoc_height ="600"; amzn_assoc_default_search_category =""; amzn_assoc_default_search_key ="Angular6";amzn_assoc_theme ="light"; amzn_assoc_bg_color ="FFFFFF"; </script><script src="//z-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&Operation=GetScript&ID=OneJS&WS=1&Marketplace=IN"></script>`);
}

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Sorry but this is not related to this package.

Closeing now for housekeeping purposes.
