### ISSUE TITLE
ERROR: Cannot read property 'unshift' of undefined --> ng add @ng-toolkit/universal to existing Angular 8 Project

### ISSUE THREAD

**Issue by Sagato** [maciejtreder/ng-toolkit#624]
<pre><code>
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
I updated to Angular 8 (update went fine). Then I decided to use Angular Universal SSR on AWS S3. 
I found this command to add all necessary dependencies --> ng add @ng-toolkit/universal

The terminal outputs following Error: (... is a placeholder for the project name)
**Installed packages for tooling via npm.
INFO: Project property is set to '...'.
Nothing to be done.
ERROR: Cannot read property 'unshift' of undefined**

## Expected behavior
That ng add @ng-toolkit/universal adds all the necessary dependencies and files to my project so I can use Angular Universal SSR

## Minimal reproduction of the problem with instructions
Type ng add @ng-toolkit/universal into the terminal in project root and hit enter
... is a placeholder for the project name

**my package.json:**
<pre>
<code>
{
  "name": "...",
  "version": "0.0.0",
  "bundlewatch": {
    "files": [
      {
        "path": "dist/*.js",
        "maxSize": "200kB"
      }
    ]
  },
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "test-size": "bundlewatch --max-size 200kb ./dist/*.js",
    "bundle-report": "webpack-bundle-analyzer dist/stats-es2015.json"
  },
  "private": true,
  "dependencies": {
    "@angular-devkit/build-optimizer": "^0.13.9",
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "^8.0.0",
    "@angular/compiler": "^8.0.0",
    "@angular/core": "^8.0.0",
    "@angular/forms": "^8.0.0",
    "@angular/platform-browser": "^8.0.0",
    "@angular/platform-browser-dynamic": "^8.0.0",
    "@angular/router": "^8.0.0",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.18",
    "@fortawesome/free-brands-svg-icons": "^5.8.2",
    "@fortawesome/free-regular-svg-icons": "^5.8.2",
    "@fortawesome/free-solid-svg-icons": "^5.8.2",
    "@ng-toolkit/universal": "^1.1.21",
    "@ngx-translate/core": "^10.0.2",
    "@ngx-translate/http-loader": "^3.0.1",
    "core-js": "^2.6.9",
    "date-fns": "^1.30.1",
    "highcharts": "^7.1.1",
    "highcharts-angular": "^2.4.0",
    "ngx-captcha": "^6.4.0",
    "ngx-clipboard": "^12.1.0",
    "ngx-matomo": "^0.1.4",
    "rxjs": "^6.5.2",
    "ts-ta": "^0.3.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.800.1",
    "@angular/cli": "^8.0.1",
    "@angular/compiler-cli": "^8.0.0",
    "@angular/language-service": "^8.0.0",
    "@types/jasmine": "2.8.9",
    "@types/node": "^10.14.8",
    "bundlewatch": "^0.2.1",
    "codelyzer": "^5.0.1",
    "jasmine-core": "~3.2.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^2.0.5",
    "karma-jasmine": "~1.1.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "^5.4.2",
    "ts-node": "^7.0.1",
    "tslint": "~5.11.0",
    "typescript": "3.4.5",
    "webpack-bundle-analyzer": "^3.3.2"
  }
}
</code>
</pre>

**my angular.json:**
<pre>
<code>
{
    "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
    "version": 1,
    "newProjectRoot": "projects",
    "projects": {
        "...": {
            "root": "",
            "sourceRoot": "src",
            "projectType": "application",
            "architect": {
                "build": {
                    "builder": "@angular-devkit/build-angular:browser",
                    "options": {
                        "outputPath": "dist",
                        "index": "src/index.html",
                        "main": "src/main.ts",
                        "tsConfig": "src/tsconfig.app.json",
                        "polyfills": "src/polyfills.ts",
                        "assets": [
                            "src/assets",
                            "src/favicon.png",
                            "src/.htaccess"
                        ],
                        "styles": [
                            "src/styles/app.scss"
                        ],
                        "scripts": []
                    },
                    "configurations": {
                        "production": {
                            "optimization": true,
                            "outputHashing": "all",
                            "sourceMap": false,
                            "extractCss": true,
                            "namedChunks": false,
                            "aot": true,
                            "extractLicenses": true,
                            "vendorChunk": false,
                            "buildOptimizer": true,
                            "fileReplacements": [
                                {
                                    "replace": "src/environments/environment.ts",
                                    "with": "src/environments/environment.prod.ts"
                                }
                            ]
                        }
                    }
                },
                "serve": {
                    "builder": "@angular-devkit/build-angular:dev-server",
                    "options": {
                        "browserTarget": "...:build"
                    },
                    "configurations": {
                        "production": {
                            "browserTarget": "...:build:production"
                        }
                    }
                },
                "extract-i18n": {
                    "builder": "@angular-devkit/build-angular:extract-i18n",
                    "options": {
                        "browserTarget": "...:build"
                    }
                },
                "test": {
                    "builder": "@angular-devkit/build-angular:karma",
                    "options": {
                        "main": "src/test.ts",
                        "karmaConfig": "./karma.conf.js",
                        "polyfills": "src/polyfills.ts",
                        "tsConfig": "src/tsconfig.spec.json",
                        "scripts": [],
                        "styles": [
                            "node_modules/font-awesome/css/font-awesome.css",
                            "node_modules/ng2-toastr/bundles/ng2-toastr.min.css",
                            "src/styles/app.scss"
                        ],
                        "assets": [
                            "src/assets",
                            "src/favicon.png",
                            "src/.htaccess"
                        ]
                    }
                },
                "lint": {
                    "builder": "@angular-devkit/build-angular:tslint",
                    "options": {
                        "tsConfig": [
                            "src/tsconfig.app.json",
                            "src/tsconfig.spec.json"
                        ],
                        "exclude": []
                    }
                }
            }
        },
        "...-e2e": {
            "root": "e2e",
            "sourceRoot": "e2e",
            "projectType": "application",
            "architect": {
                "e2e": {
                    "builder": "@angular-devkit/build-angular:protractor",
                    "options": {
                        "protractorConfig": "./protractor.conf.js",
                        "devServerTarget": "...:serve"
                    }
                },
                "lint": {
                    "builder": "@angular-devkit/build-angular:tslint",
                    "options": {
                        "tsConfig": [
                            "e2e/tsconfig.e2e.json"
                        ],
                        "exclude": []
                    }
                }
            }
        }
    },
    "defaultProject": "...",
    "schematics": {
        "@schematics/angular:component": {
            "prefix": "app",
            "styleext": "scss"
        },
        "@schematics/angular:directive": {
            "prefix": "app"
        }
    }
}
</code>
</pre>

## Example repository
Don't have one cause its closed source

## Environment
<pre><code>
- Angular version: 8.0.0
- Node version: v12.3.1 
- Platform:  MacOS Mojave 10.14 (18A391)
</code></pre>

**Comment by notalk0** [comment]
I just follow Gary Simons's tutorial and get the same result with you

<pre><code>// My package.json
"dependencies": {
    "@angular/animations": "~8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "@ng-toolkit/universal": "^1.1.21",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },</pre></code>

![Capture](https://user-images.githubusercontent.com/9769260/59548167-7352c900-8f7d-11e9-85a9-98a131995c74.JPG)

After added package, app.browser.module and app.server.module was not created and when check page source the html content remain unrevealed.


## Example repository
https://github.com/notalk0/ng-seo-demo

**Comment by Princekumar13** [comment]
I face same problem.

**Comment by velikGeorgiev** [comment]
same here ...

**Comment by netomarchiori** [comment]
check this [https://github.com/maciejtreder/ng-toolkit/issues/578](url)

**Comment by KingDarBoja** [comment]
Closed for housekeeping reasons.
