### ISSUE TITLE
Error adding toolkit on new project

### ISSUE THREAD

**Issue by ehogeweg** [maciejtreder/ng-toolkit#625]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/paw
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: v11.4.0  
- Platform:  

Others:

</code></pre>

**Comment by QuentinPetel** [comment]
Duplicates of https://github.com/maciejtreder/ng-toolkit/issues/624

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
