### ISSUE TITLE
question about rendering

### ISSUE THREAD

**Issue by nico281** [maciejtreder/ng-toolkit#627]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[x ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

Hi, how are you? 
I'm trying to use angular universal. I managed to install it but my problem is on making changes on html templates. 
The only way to refelct changes was rebuilding the app.
That is correct or there is another way to reflect template changes without rebuilding the app?
Cheers

**Comment by KingDarBoja** [comment]
Hi @nico281,

You can serve the app locally without building it to faster reload in order to notice the template changes. That's one of the basic stuff on the Angular development, so take a look at the Angular documentation in order to do it.

Cheers!
