### ISSUE TITLE
Entry module not found in ./src/main.ts.

### ISSUE THREAD

**Issue by nikneem** [maciejtreder/ng-toolkit#628]
## I'm submitting a...

<pre><code>
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
INFO: Project property is set to 'blog'.
ERROR: Entry module not found in ./src/main.ts.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.

## Expected behavior
I'd expect the error to not occur

## Minimal reproduction of the problem with instructions
Create a new project with angular 8
  "dependencies": {
    "@angular/animations": "^8.0.0",
    "@angular/cdk": "^8.0.0",
    "@angular/common": "~8.0.0",
    "@angular/compiler": "~8.0.0",
    "@angular/core": "~8.0.0",
    "@angular/forms": "~8.0.0",
    "@angular/material": "^8.0.0",
    "@angular/platform-browser": "~8.0.0",
    "@angular/platform-browser-dynamic": "~8.0.0",
    "@angular/router": "~8.0.0",
    "@ng-toolkit/universal": "^1.1.21",
    "hammerjs": "^2.0.8",
    "lodash": "^4.17.11",
    "ngx-disqus": "^2.4.3",
    "ngx-markdown": "^8.0.1",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },

## Example repository
https://github.com/nikneem/nikneem-blog

## Environment

<pre><code>
Angular version: 8
</code></pre>

**Comment by KingDarBoja** [comment]
Closed for housekeeping purposes.
