### ISSUE TITLE
Face problem in installation @ng-toolkit/universal in Angular 8

### ISSUE THREAD

**Issue by Princekumar13** [maciejtreder/ng-toolkit#630]
ERROR: Cannot read property 'unshift' of undefined (got this error when I run 'ng add @ng-toolkit/universal' command in angular 8) . AnyOne can help me, how it will be solve?

Thanks

**Comment by danieljausovec** [comment]
Yeah, I had the same problem. I installed it with "npm install --save @ng-toolkit/universal" before I use "add" command and it's work, but I get the another error when I run "ng add @ng-toolkit/universal"

`No matching version found for @nguniversal/module-map-ngfactory-loader@~8.0.0`

**Comment by mryuvn** [comment]
You have to installed "npm install @nguniversal/module-map-ngfactory-loader --save" before "npm install --save @ng-toolkit/universal" and then run "ng add @ng-toolkit/universal"

**Comment by KingDarBoja** [comment]
Please check #695
