### ISSUE TITLE
Error While installing the package ng toolkit. 

### ISSUE THREAD

**Issue by vinaynan1** [maciejtreder/ng-toolkit#631]
C:\Users\vinayn\my-appnew>ng add @ng-toolkit/universal
Installing packages for tooling via npm.
npm WARN deprecated bugsnag@2.4.3: All projects should upgrade to our universal JS notifier: "@bugsnag/js". See https://github.com/bugsnag/bugsnag-js/blob/master/UPGRADING.md for more details.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.

> @ng-toolkit/universal@1.1.21 postinstall C:\Users\vinayn\my-appnew\node_modules\@ng-toolkit\universal
> node postinstall.js

Do you ❤️ @ng-toolkit?

Star it on GitHub!
https://github.com/maciejtreder/ng-toolkit

Become a donor:
 > https://www.angular-universal-pwa.maciejtreder.com/donors

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.9 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.9: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @ng-toolkit/universal@1.1.21
added 27 packages from 56 contributors and audited 37154 packages in 27.272s
found 0 vulnerabilities

Installed packages for tooling via npm.
INFO: Project property is set to 'my-appnew'.
ERROR: Cannot read property 'unshift' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

Also i am not able to run below command 

npm run build:prod

**Comment by VamshiDooreddy** [comment]
i am also getting same error.

**Comment by KingDarBoja** [comment]
Closed for housekeeping reason.

Please check #695.

Cheers!
