### ISSUE TITLE
error adding @ng-toolkit/universal

### ISSUE THREAD

**Issue by Kevinoh47** [maciejtreder/ng-toolkit#632]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

when i type ng add @ng-toolkit/universal, the console reports this error: "Cannot read property 'unshift' of undefined" and the tutorial's project files that were supposed to be updated are not.

## Expected behavior

@ng-toolkit/universal should be added with no errors, and the ap.module.ts file should be updated as described in the tutorial, and new angular universal files added to the project.

## Minimal reproduction of the problem with instructions

STEPS TO REPRODUCE
1. Follow tutorial https://www.twilio.com/blog/angular-universal-javascript-node-js-aws-lambda to the point where the universal toolkit is added.
2. add the toolkit.
3. notice the error reported in the console.
4. notice that the mods to app.module.ts were not completed.
5. notice that src/app/app.server.module.ts was not added to the project.

## Example repository

https://github.com/Kevinoh47/angularSeo

## What is the motivation / use case for changing the behavior?

I would like to complete the tutorial and deploy to my AWS account.

## Environment

<pre><code>
Angular version: X.Y.Z

Angular CLI: 8.0.3
Angular: 8.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

- Node version: XX  
Node: 10.16.0
- Platform:  
OS: darwin x64

Others:

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.3
@angular-devkit/build-angular     0.800.3
@angular-devkit/build-optimizer   0.800.3
@angular-devkit/build-webpack     0.800.3
@angular-devkit/core              8.0.3
@angular-devkit/schematics        8.0.3
@angular/cli                      8.0.3
@ngtools/webpack                  8.0.3
@schematics/angular               8.0.3
@schematics/update                0.800.3
rxjs                              6.4.0
typescript                        3.4.5
webpack                           4.30.0

</code></pre>

**Comment by KingDarBoja** [comment]
Please check #695.

This is a known issue, a bugfix is coming in the next version.

Cheers!
