### ISSUE TITLE
ng add @ng-toolkit/universal,  ERROR-> : Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by jithinTechjini** [maciejtreder/ng-toolkit#638]
## I'm submitting a...

<pre><code>
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
when running ng add @ng-toolkit/universal, getting ERROR-> : Cannot read property 'kind' of undefined

## Environment
<pre><code>
Angular version: 6

- Node version: 11
- Platform:  linux

</code></pre>

**Comment by KingDarBoja** [comment]
🏷  Closed as this is a know issue.

Cheers!
