### ISSUE TITLE
Cannot read property 'unshift' of undefined on installing @ng-toolkit/universal package

### ISSUE THREAD

**Issue by NubulMachary** [maciejtreder/ng-toolkit#642]
ng add @ng-toolkit/universal

i ran this  **ng add @ng-toolkit/universal**  on a  new angular project without even writing a single line of code..

But its throwing an error as below:
`INFO: Project property is set to 'prerender'.
ERROR: Cannot read property 'unshift' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.`

What to do ??
Where i am wrong here ??

![Untitled](https://user-images.githubusercontent.com/29141761/61290817-64fd0480-a7ea-11e9-9e2f-920446fe0312.png)

**Comment by jontrost** [comment]
I'm having the same issue

**Comment by KingDarBoja** [comment]
Please see #683.
