### ISSUE TITLE
Assets (icon font and .mp3) 403 forbidden when deploying an Angular App 

### ISSUE THREAD

**Issue by jessemoon0** [maciejtreder/ng-toolkit#643]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[X] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[X] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

I have an Angular app that has as assets: A video file (.mp4 and .webm) and also custom fonts (.woff, .ttf, .eot, .svg) and it gets an error when I deploy the site. 

The link to the app is: https://khynq5qtbd.execute-api.us-east-2.amazonaws.com/production 

If we go to the Chrome dev tools network tab, we can see a 502 error with those assets. All other assets are being shown correctly.

## Expected behavior

Show the video and fonts correctly.

## Minimal reproduction of the problem with instructions

The link to the app is: https://khynq5qtbd.execute-api.us-east-2.amazonaws.com/production

- Check the Chrome dev tools console (cmd + opt + i or right click inspect).
- Check the Chrome dev tools network tab and see the asset failing with Cloudfront 502 error

## Example repository

Github repo: https://github.com/jessemoon0/nature-landing
Deployed App:  https://khynq5qtbd.execute-api.us-east-2.amazonaws.com/production

## What is the motivation/use case for changing the behavior?

All assets types should be shown correctly. "It works on my machine" (lol), so I'm trying to make the deployed version to work correctly with all asset types.

## Environment

<pre><code>
Angular version: X.Y.Z

Versioning doesn't have anything to do, but I'm running 8.1.0

- Node version: XX  

12.4.0

- Platform:  

Mac

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Same issue here. I found #134 being the same question but the provided [tutorial](https://medium.com/@maciejtreder/custom-domain-in-aws-api-gateway-a2b7feaf9c74) says that you must config a CNAME in aws api gateway.

It is my first time trying to deploy an angular app using serverless with this toolkit, which was successful but the assets is the only thing left to test on maintenance link.

Cheers!

**Comment by KingDarBoja** [comment]
Need to provide some kind of tutorial for these cases. Closing now for housekeeping reasons.
