### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by oantonov** [maciejtreder/ng-toolkit#646]
## I'm submitting a...

<pre><code>
[x] Bug report  
</code></pre>

## In package
<pre><code>
[x] @ng-toolkit/universal
</code></pre>

## Current behavior
Installed packages for tooling via npm.
INFO: Project property is set to 'headless-app'.
ERROR: Browser build not found (lack of entry with build-angular:browser builder) in angular.json
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

## Expected behavior

Not to get that error

## Minimal reproduction of the problem with instructions

1. ng add @ng-toolkit/universal
2.  error
3.  ng add @ng-toolkit/universal --project headless-app
4. same error

## Example repository

Repository is private, so I can provide you only my angular.json

<pre><code>
{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "locales",
  "projects": {
    "headless-app": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "",
      "sourceRoot": "src",
      "prefix": "hdls",
      "architect": {
        "build": {
          "builder": "nyan-builder:browser",
          "options": {
            "outputPath": "dist/headless-app",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.app.json",
            "aot": true,
            "i18nFile": "translations/default.xlf",
            "i18nFormat": "xlf",
            "i18nLocale": "en-US",
            "i18nMissingTranslation": "error",
            "assets": [
              "src/favicon.ico",
              "src/.htaccess",
              "src/robots.txt",
              "src/assets",
              "src/manifest.webmanifest"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ],
              "serviceWorker": true,
              "ngswConfigPath": "ngsw-config.json"
            }
          }
        },
        "serve": {
          "builder": "nyan-builder:dev-server",
          "options": {
            "browserTarget": "headless-app:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "headless-app:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "headless-app:build"
          }
        },
        "test": {
          "builder": "nyan-builder:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "tsconfig.spec.json",
            "karmaConfig": "karma.conf.js",
            "assets": [
              "src/favicon.ico",
              "src/.htaccess",
              "src/robots.txt",
              "src/assets",
              "src/manifest.webmanifest"
            ],
            "styles": [
              "src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "tsconfig.app.json",
              "tsconfig.spec.json",
              "e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "headless-app:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "headless-app:serve:production"
            }
          }
        }
      }
    },
    "en-US": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "locales/en-US",
      "sourceRoot": "locales/en-US/src",
      "prefix": "us",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/en-US",
            "index": "locales/en-US/src/index.html",
            "main": "locales/en-US/src/main.ts",
            "polyfills": "locales/en-US/src/polyfills.ts",
            "tsConfig": "locales/en-US/tsconfig.app.json",
            "aot": true,
            "assets": [
              "locales/en-US/src/favicon.ico",
              "locales/en-US/src/.htaccess",
              "locales/en-US/src/robots.txt",
              "locales/en-US/src/assets"
            ],
            "styles": [
              "locales/en-US/src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "locales/en-US/src/environments/environment.ts",
                  "with": "locales/en-US/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            },
            "en-US": {
              "aot": true,
              "outputPath": "dist/en-US/"
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "en-US:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "en-US:build:production"
            },
            "en-US": {
              "browserTarget": "en-US:build:en-US"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "en-US:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "locales/en-US/src/test.ts",
            "polyfills": "locales/en-US/src/polyfills.ts",
            "tsConfig": "locales/en-US/tsconfig.spec.json",
            "karmaConfig": "locales/en-US/karma.conf.js",
            "assets": [
              "locales/en-US/src/favicon.ico",
              "locales/en-US/src/.htaccess",
              "locales/en-US/src/robots.txt",
              "locales/en-US/src/assets"
            ],
            "styles": [
              "locales/en-US/src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "locales/en-US/tsconfig.app.json",
              "locales/en-US/tsconfig.spec.json",
              "locales/en-US/e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "locales/en-US/e2e/protractor.conf.js",
            "devServerTarget": "en-US:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "en-US:serve:production"
            }
          }
        }
      }
    },
    "es-ES": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "locales/es-ES",
      "sourceRoot": "locales/es-ES/src",
      "prefix": "es",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/es-ES",
            "index": "locales/es-ES/src/index.html",
            "main": "locales/es-ES/src/main.ts",
            "polyfills": "locales/es-ES/src/polyfills.ts",
            "tsConfig": "locales/es-ES/tsconfig.app.json",
            "aot": true,
            "assets": [
              "locales/es-ES/src/favicon.ico",
              "locales/es-ES/src/.htaccess",
              "locales/es-ES/src/robots.txt",
              "locales/es-ES/src/assets"
            ],
            "styles": [
              "locales/es-ES/src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "locales/es-ES/src/environments/environment.ts",
                  "with": "locales/es-ES/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            },
            "es-ES": {
              "aot": true,
              "outputPath": "dist/es-ES/",
              "i18nFile": "translations/es-ES.xlf",
              "i18nFormat": "xlf",
              "i18nLocale": "es-ES",
              "i18nMissingTranslation": "error"
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "es-ES:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "es-ES:build:production"
            },
            "es-ES": {
              "browserTarget": "es-ES:build:es-ES"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "es-ES:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "locales/es-ES/src/test.ts",
            "polyfills": "locales/es-ES/src/polyfills.ts",
            "tsConfig": "locales/es-ES/tsconfig.spec.json",
            "karmaConfig": "locales/es-ES/karma.conf.js",
            "assets": [
              "locales/es-ES/src/favicon.ico",
              "locales/es-ES/src/.htaccess",
              "locales/es-ES/src/robots.txt",
              "locales/es-ES/src/assets"
            ],
            "styles": [
              "locales/es-ES/src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "locales/es-ES/tsconfig.app.json",
              "locales/es-ES/tsconfig.spec.json",
              "locales/es-ES/e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "locales/es-ES/e2e/protractor.conf.js",
            "devServerTarget": "es-ES:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "es-ES:serve:production"
            }
          }
        }
      }
    },
    "de-DE": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "style": "scss"
        }
      },
      "root": "locales/de-DE",
      "sourceRoot": "locales/de-DE/src",
      "prefix": "de",
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/de-DE",
            "index": "locales/de-DE/src/index.html",
            "main": "locales/de-DE/src/main.ts",
            "polyfills": "locales/de-DE/src/polyfills.ts",
            "tsConfig": "locales/de-DE/tsconfig.app.json",
            "aot": true,
            "assets": [
              "locales/de-DE/src/favicon.ico",
              "locales/de-DE/src/.htaccess",
              "locales/de-DE/src/robots.txt",
              "locales/de-DE/src/assets"
            ],
            "styles": [
              "locales/de-DE/src/styles.scss"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "locales/de-DE/src/environments/environment.ts",
                  "with": "locales/de-DE/src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true,
              "budgets": [
                {
                  "type": "initial",
                  "maximumWarning": "2mb",
                  "maximumError": "5mb"
                }
              ]
            },
            "de-DE": {
              "aot": true,
              "outputPath": "dist/de-DE/",
              "i18nFile": "translations/de-DE.xlf",
              "i18nFormat": "xlf",
              "i18nLocale": "de-DE",
              "i18nMissingTranslation": "error"
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "de-DE:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "de-DE:build:production"
            },
            "de-DE": {
              "browserTarget": "de-DE:build:de-DE"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "de-DE:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "locales/de-DE/src/test.ts",
            "polyfills": "locales/de-DE/src/polyfills.ts",
            "tsConfig": "locales/de-DE/tsconfig.spec.json",
            "karmaConfig": "locales/de-DE/karma.conf.js",
            "assets": [
              "locales/de-DE/src/favicon.ico",
              "locales/de-DE/src/.htaccess",
              "locales/de-DE/src/robots.txt",
              "locales/de-DE/src/assets"
            ],
            "styles": [
              "locales/de-DE/src/styles.scss"
            ],
            "scripts": []
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "locales/de-DE/tsconfig.app.json",
              "locales/de-DE/tsconfig.spec.json",
              "locales/de-DE/e2e/tsconfig.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        },
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "locales/de-DE/e2e/protractor.conf.js",
            "devServerTarget": "de-DE:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "de-DE:serve:production"
            }
          }
        }
      }
    }
  },
  "defaultProject": "headless-app"
}
</code></pre>
and my package.json
<pre><code>
{
  "name": "headless-app",
  "version": "0.0.4",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --aot --open --port 1111",
    "start:us": "ng serve en-US --aot --open --port 2222",
    "start:es": "ng serve es-ES --aot --open --port 3333",
    "start:de": "ng serve de-DE --aot --open --port 4444",
    "dev": "ng serve -c=all-ALL --aot --open --port 1111",
    "dev:us": "ng serve en-US --aot --open --port 2222",
    "dev:es": "ng serve es-ES -c=es-ES --aot --open --port 3333",
    "dev:de": "ng serve de-DE -c=de-DE --aot --open --port 4444",
    "build": "ng build --prod --aot --build-optimizer --vendor-chunk --output-hashing all --extract-css=true --named-chunks=false --lazyModules",
    "build:us": "ng build en-US --base-href /en-US/ --prod --aot --build-optimizer --vendor-chunk --output-hashing all --extract-css=true --named-chunks=false --lazyModules",
    "build:es": "ng build es-ES --base-href /es-ES/ -c=es-ES --prod --aot --build-optimizer --vendor-chunk --output-hashing all --extract-css=true --named-chunks=false --lazyModules",
    "build:de": "ng build de-DE --base-href /de-DE/ -c=de-DE --prod --aot --build-optimizer --vendor-chunk --output-hashing all --extract-css=true --named-chunks=false --lazyModules",
    "build:all": "npm run build && npm run build:us && npm run build:es && npm run build:de",
    "extract": "ng xi18n --output-path extracted --progress=true --i18nLocale=es-ES --outFile=all-ALL.xlf",
    "extract:es": "ng xi18n es-ES --output-path ../../extracted --progress=true --i18nLocale=es-ES --outFile=es-ES.xlf",
    "extract:de": "ng xi18n de-DE --output-path ../../extracted --progress=true --i18nLocale=de-DE --outFile=de-DE.xlf",
    "extract:all": "npm run extract:es && npm run extract:de",
    "test": "ng test",
    "test:us": "ng test en-US",
    "test:es": "ng test es-ES",
    "test:de": "ng test de-DE",
    "lint": "ng lint",
    "lint:us": "ng lint en-US",
    "lint:es": "ng lint es-ES",
    "lint:de": "ng lint de-DE",
    "lint:all": "npm run lint && npm run lint:us && npm run lint:es && npm run lint:de",
    "slint": "stylelint src/**/*.scss || true",
    "slint:us": "stylelint locales/en-US/src/**/*.scss || true",
    "slint:es": "stylelint locales/es-ES/src/**/*.scss || true",
    "slint:de": "stylelint locales/de-DE/src/**/*.scss || true",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.1.0",
    "@angular/common": "~8.1.0",
    "@angular/compiler": "~8.1.0",
    "@angular/core": "~8.1.0",
    "@angular/forms": "~8.1.0",
    "@angular/platform-browser": "~8.1.0",
    "@angular/platform-browser-dynamic": "~8.1.0",
    "@angular/pwa": "^0.801.1",
    "@angular/router": "~8.1.0",
    "@angular/service-worker": "~8.1.0",
    "@ng-toolkit/universal": "^1.1.21",
    "rxjs": "~6.5.2",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.0",
    "@angular/cdk": "^8.1.1",
    "@angular/cli": "~8.1.0",
    "@angular/compiler-cli": "~8.1.0",
    "@angular/language-service": "~8.1.0",
    "@schematics/angular": "~8.0.0",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~12.6.2",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.2.0",
    "karma-chrome-launcher": "~3.0.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "nyan-builder": "^1.0.4",
    "protractor": "~5.4.0",
    "stylelint": "^10.1.0",
    "stylelint-config-standard": "^18.3.0",
    "stylelint-scss": "^3.9.0",
    "ts-node": "~8.3.0",
    "tslint": "~5.18.0",
    "typescript": "~3.4.5"
  }
}
</code></pre>

## Environment

<pre><code>
- Angular version: 8.1.0
- Node version: 10.16.0  
- Platform:  Windows 10
</code></pre>

**Comment by KingDarBoja** [comment]
This should be fixed on latest version, please update.

Closing now for housekeeping purposes.
