### ISSUE TITLE
Unable to install ng add @ng-toolkit/universal

### ISSUE THREAD

**Issue by andola-dev** [maciejtreder/ng-toolkit#647]
Getting error

 Installing packages for tooling via npm.
ERROR: Invalid rule result: Function().
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by ahadiwasti** [comment]
i am getting the same error

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

Cheers!
