### ISSUE TITLE
Error while creating app > ng new --collection @ng-toolkit/init mytoolkit

### ISSUE THREAD

**Issue by kolibhagyashree** [maciejtreder/ng-toolkit#653]
D:\Projects>ng new --collection @ng-toolkit/init mytoolkit
ERROR: Cannot read property 'architect' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Bugsnag:  Encountered an uncaught error, terminating…
Error: spawn C:\Windows\system32\cmd.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by cb03037** [comment]
Getting the same with angular 8.2.0

**Comment by KingDarBoja** [comment]
Same here with Angular v8.

**Comment by KingDarBoja** [comment]
**UPDATE**

Next version will solve this issue, please don't panic!

Cheers!
