### ISSUE TITLE
Is there a way to exclude certain components during build:prerender?

### ISSUE THREAD

**Issue by AndrewMcShane** [maciejtreder/ng-toolkit#654]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[] Feature request
[x] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Currently when running the prerender build, everything works splendid; it awaits the api calls and populates the pages, then when deployed, the static html is loaded first and then once the page finishes loading in the JS, the page is rehydrated as expected. However, I'm looking to implement AdSense to the site and it occurred to me that if the ad display code is included in that initial page load, then loaded again once the app JS loads, it'll call the api twice and inflate the numbers and might violate terms, looking like I'm attempting to illegitimately boost ad views.
The site will be at max 250 pages, so I could manually remove the code from every static file that would have the ad render code, but that'd be fairly tedious.

## Expected behavior

Is there a way to express `if(isPrerendering){ /*Do stuff..*/ }` or `if(appIsLoaded && isProd){/*...*/}` so that certain things are able to be excluded (or included) from the resulting static html files?

## Environment

<pre><code>
Angular version: 8.0
</code></pre>

**Comment by KingDarBoja** [comment]
As far as I know... No, you can't exclude components on prerendering. However, you could explicity set the **routes** of those components that you want to load on prerendering on the `static.paths.ts` file if using latest version of this package.
