### ISSUE TITLE
npm run build:prerender failed to copy assets directory

### ISSUE THREAD

**Issue by asurinsaka** [maciejtreder/ng-toolkit#655]
## I'm submitting a...

<pre><code>
[X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Ran `npm run build:prerender`
Got following static routes: `/`

And following found in the application:
```console
fs.js:126
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, copyfile './dist/browser/assets' -> './dist/static/assets'
    at Object.copyFileSync (fs.js:1731:3)
    at /home/asurin/develop/sothaispa-angular/dist/prerender.js:131871:12
    at Array.forEach (<anonymous>)
    at Module.<anonymous> (/home/asurin/develop/sothaispa-angular/dist/prerender.js:131869:14)
    at __webpack_require__ (/home/asurin/develop/sothaispa-angular/dist/prerender.js:21:30)
    at /home/asurin/develop/sothaispa-angular/dist/prerender.js:85:18
    at Object.<anonymous> (/home/asurin/develop/sothaispa-angular/dist/prerender.js:88:10)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32) {
  errno: -21,
  syscall: 'copyfile',
  code: 'EISDIR',
  path: './dist/browser/assets',
  dest: './dist/static/assets'
}
npm ERR! code ELIFECYCLE
```

## Expected behavior

It should be able to copy directories.

## Minimal reproduction of the problem with instructions

create an angular project with some files in the assets directory and it will fail.

## Environment

<pre><code>
Angular version: 8.2.0

- Node version: 12.7.0  
- Platform: ubuntu 

Others:

</code></pre>

**Comment by asurinsaka** [comment]
I used ncp package it seems to work for me.
```
const ncp = require('ncp').ncp;
// copy static files
filesBrowser.forEach(file => {
    if (file !== 'index.html') {
        // fs.copyFileSync(`./dist/browser/${file}`, `./dist/static/${file}`);
      ncp(`./dist/browser/${file}`, `./dist/static/${file}`, err => {
        if (err) {
          return console.error(err);
        }
        console.log(`Copied file ${file}`);
      });
    }
});
```

**Comment by JohnGallego** [comment]
@asurinsaka Your solution worked for me as well. Any clue as to why fs.copyFileSync wasn't working?

**Comment by KingDarBoja** [comment]
> @asurinsaka Your solution worked for me as well. Any clue as to why `fs.copyFileSync` wasn't working?

It is because `copyFileSync` copies src **filename** to **destination** path. In this case, the destination path probably does not exist at the time the copy was being made.

Anyway, it is getting fixed in next releases. 

Cheers!
