### ISSUE TITLE
Cant install @ng-toolkit/universal cant read property unshift of undefined

### ISSUE THREAD

**Issue by itsUnsmart** [maciejtreder/ng-toolkit#656]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ x ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Installed packages for tooling via npm.
INFO: Project property is set to 'smarthost'.
ERROR: Cannot read property 'unshift' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

## Expected behavior

To work

## Minimal reproduction of the problem with instructions

Try installing it

## Example repository

dont have public one 

## What is the motivation / use case for changing the behavior?

because i wanna install it

## Environment

<pre><code>
Angular version: 8.1.1

- Node version: 10.16.0  
- Platform:   Windows

Others:

</code></pre>
Windows 10 EDU License
VS Code
Used ng add @ng-toolkit/universal
Running on express server

I tried to follow https://www.youtube.com/watch?v=hxG9nuvnh-A but couldnt get it installed

**Comment by AndrewMcShane** [comment]
#626
