### ISSUE TITLE
Universal: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by velikGeorgiev** [maciejtreder/ng-toolkit#665]
## I'm submitting a...

<pre><code>
[ X ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Running ng add @ng-toolkit/universal

Log:
ERROR: Cannot read property 'kind' of undefined

## Environment

<pre><code>
Angular version: 8.2.2

- Node version: v10.16.0  
- Platform:  Windows 10 Pro

</code></pre>

**Comment by KingDarBoja** [comment]
Please check #695.

**Comment by Jerome2606** [comment]
I checked the #695 and downgrade the version of the toolkit universal to 7.1.2 but I'm keeping to have this issue.

Impossible for me to use this "magic" tool to implement universal in my applicaiton :(

**Comment by Jerome2606** [comment]
This commandline is working for me, not ng-toolkit:
https://github.com/angular/angular-cli/issues/15575
```
ng add @nguniversal/express-engine@next --clientProject Moovy
```
