### ISSUE TITLE
Couldn't able to deploy app to serverless environment

### ISSUE THREAD

**Issue by HenonoaH** [maciejtreder/ng-toolkit#671]
## I'm submitting a...

<pre><code>
[ ] Bug report  
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
</code></pre>

## Current behavior

Getting npm ERR! code ELIFECYCLE. For more info refer snap,
![image](https://user-images.githubusercontent.com/32451863/63793855-26488700-c91e-11e9-9635-173a8f26cd9c.png)

## Expected behavior

Able to deploy an app without any interruption

## Minimal reproduction of the problem with instructions

I got the above error while running this command <code>npm run build:serverless:deploy</code> I followed deployment steps from this source https://coursetro.com/posts/code/165/Deploying-your-Angular-App-to-a-Serverless-Environment-

## Environment

<pre><code>
Angular version: 8.1.1

- Node version: v10.16.0  
- Platform:  Linux 

</code></pre>

**Comment by KingDarBoja** [comment]
Hello @HenonoaH,

I can't really tell what caused the error while deploying to the serverless enviroment.

Can you provide more info, like as `package.json` and the generated log file?

Cheers!

**Comment by HenonoaH** [comment]
Hi @KingDarBoja Please find my `package.json` Sorry, I missed the log file! Hope this `package.json` will help.

```json
{
  "name": "man-ng",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node local.js",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run mmr-ng:server:production",
    "server": "node local.js",
    "build:prod": "npm run build:browser:prod && npm run build:server:prod",
    "serve:prerender": "node static.js",
    "build:prerender": "npm run build:prod && node dist/prerender.js",
    "build:browser:prod": "ng build --prod",
    "build:browser:serverless": "ng build --prod --base-href /production/",
    "build:serverless": "npm run build:browser:serverless && npm run build:server:serverless",
    "build:prod:deploy": "npm run build:prod && npm run deploy",
    "build:serverless:deploy": "npm run build:serverless && npm run deploy",
    "deploy": "serverless deploy",
    "build:server:prod": "ng run mmr-ng:server && webpack --config webpack.server.config.js --progress --colors",
    "build:server:serverless": "ng run mmr-ng:server:serverless && webpack --config webpack.server.config.js --progress --colors"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "^8.1.2",
    "@angular/cdk": "^8.1.1",
    "@angular/common": "~8.1.1",
    "@angular/compiler": "~8.1.1",
    "@angular/core": "~8.1.1",
    "@angular/forms": "~8.1.1",
    "@angular/material": "^8.1.1",
    "@angular/platform-browser": "~8.1.1",
    "@angular/platform-browser-dynamic": "~8.1.1",
    "@angular/platform-server": "~8.1.1",
    "@angular/router": "~8.1.1",
    "@ng-bootstrap/ng-bootstrap": "^5.0.0",
    "@ng-toolkit/serverless": "^7.1.2",
    "@ng-toolkit/universal": "^7.1.2",
    "@nguniversal/common": "0.0.0",
    "@nguniversal/express-engine": "0.0.0",
    "@nguniversal/module-map-ngfactory-loader": "0.0.0",
    "aws-serverless-express": "^3.2.0",
    "cors": "~2.8.4",
    "cp-cli": "^1.1.0",
    "domino": "^2.1.3",
    "express": "^4.15.2",
    "rxjs": "~6.4.0",
    "tslib": "^1.9.0",
    "zone.js": "~0.9.1"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.801.1",
    "@angular/cli": "~8.1.1",
    "@angular/compiler-cli": "~8.1.1",
    "@angular/language-service": "~8.1.1",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "opencollective": "^1.0.3",
    "protractor": "~5.4.0",
    "serverless": "1.40.0",
    "serverless-apigw-binary": "^0.4.4",
    "ts-loader": "^5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.4.3",
    "webpack-cli": "^3.1.0"
  }
}
```

**Comment by KingDarBoja** [comment]
@HenonoaH Everything seems okay to me, the only thing that looks suspicious is the `build:server:serverless` script, you are trying to run this:

`ng run mmr-ng:server:serverless && webpack --config webpack.server.config.js --progress --colors`

But your project name doesn't match! It should be `man-ng` instead of `mmr-ng` 🤔

**Comment by KingDarBoja** [comment]
@HenonoaH Hard to tell what's going on as everything seems okay to me, maybe the AWS wasn't properly set on the serverless step.

Can you provide the error log file? That's the only thing left to check.

**Comment by HenonoaH** [comment]
@KingDarBoja As said earlier I missed the log file let me try to deploy once again and share you with the log file.

**Comment by HenonoaH** [comment]
@KingDarBoja Hey thanks, might be the issue in AWS. I could have tried this earlier :upside_down_face:

I'm closing this issue.

![image](https://user-images.githubusercontent.com/32451863/67741659-e5fda600-fa3f-11e9-90b7-77eef0f2b5dd.png)

**Comment by KingDarBoja** [comment]
@HenonoaH 🎉 Glad it works now! And yeah, probably something on the AWS side.
