### ISSUE TITLE
Error during pre-rendering

### ISSUE THREAD

**Issue by eddyghabachi3s** [maciejtreder/ng-toolkit#673]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

I am getting this error when I use pre-rendering command:

ERROR in ../@ng-toolkit/universal/ng-toolkit-universal.ts(27,2): Error during template compile of 'NgtUniversalModule'
  Function calls are not supported in decorators but 'ɵmakeDecorator' was called in 'NgModule'
    'NgModule' calls 'ɵmakeDecorator'
node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.
../../../../../node_modules/@angular/core/src/linker/query_list.d.ts(36,22): error TS1039: Initializers are not allowed in ambient contexts.
../../../../../node_modules/@angular/core/src/application_init.d.ts(26,21): error TS1039: Initializers are not allowed in ambient contexts.
../../../../../node_modules/@angular/core/src/ivy_switch.d.ts(8,54): error TS1254: A 'const' initializer in an ambient context must be a string or numeric literal.
../../../../../node_modules/@angular/core/src/ivy_switch.d.ts(9,35): error TS1254: A 'const' initializer in an ambient context must be a string or numeric literal.
../../../../../node_modules/@angular/core/src/render3/ng_dev_mode.d.ts(9,11): error TS2451: Cannot redeclare block-scoped variable 'ngDevMode'.

## Environment

<pre><code>
Angular version: 6.2

- Node version: 6.9  
- Platform: Mac  

</code></pre>

**Comment by KingDarBoja** [comment]
This looks like a Angular issue, please take a look at [this comment](https://github.com/angular/angular/issues/23609#issuecomment-386876693) and see if it works.

Closing now for housekeeping purposes.
