### ISSUE TITLE
Is this project alive? Problems recap (with solutions);

### ISSUE THREAD

**Issue by mtabaj** [maciejtreder/ng-toolkit#674]
I tried to add ngtoolkit/universal to an existing project, and a lot of problems arises:

1 Versions: I had to manually install  
    @ng-toolkit/universal@latest
   webpack-cli: latests

2. The window.helper module is FULL of errors.  I still trying to get it working (sorry, no solution by now)

3. tsconfig.server.json has an error.  The correct path is:

"files": [
    "main.server.ts"
  ],

I hope it helps others.

I made a (small) monthly donation to you guys, because I'm not sure this is maintained.  If yes, I will raise my donation to a reasonable amount, and if not I'll close it.  Please, answer.
 
Marcos

**Comment by amannguptaggg** [comment]
I also used the same command you did. The package is installed but no file is generated.
Can Anyone help? Please

**Comment by KingDarBoja** [comment]
Hello @mtabaj,

It is still alive, I recently made a huge PR to fix tons of issues, most of them related to `universal` and `init` packages. It is gonna be released in a new version as long as the author get some free time to properly deploy it.

Hopefully, it will fix most of the issues around here so don't fall into despair.

Cheers!

**Comment by mtabaj** [comment]
Hello King,
This is really nice !  I'll take a look tomorrow.
Best,
Marcos

**Comment by KingDarBoja** [comment]
@mtabaj We just published the new version but one of the packages isn't properly published 😆 We are fixing it.
