### ISSUE TITLE
Angular Universal Not Working

### ISSUE THREAD

**Issue by amannguptaggg** [maciejtreder/ng-toolkit#675]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[* ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

I added the angular universal toolkit. It is installed using npm package. But no file is generated and updated. 
Why files like local.js , server.js ...etc are not creating itself.

## Expected behavior
On successfull installed package.. there should be created some files and updated some file.
nothing happed>

## Environment

<pre><code>
Angular version: latest (v8)

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Please check [#694](https://github.com/maciejtreder/ng-toolkit/issues/694#issuecomment-538754801) comment.

Closing it for housekeeping.
