### ISSUE TITLE
Running the server does not load the Angular 8 webapp

### ISSUE THREAD

**Issue by jcjp** [maciejtreder/ng-toolkit#677]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Listening on: http://localhost:4000 but the app never loads, no error is logged as well. However `ng serve` is still working.

## Expected behavior

Be able to run using `npm run server`.

## Minimal reproduction of the problem with instructions

1. Create an Angular 8 webapp
2. Add ng-toolkit
3. Run the build command
4. Run the server

## Environment
```
Angular CLI: 8.2.2
Node: 10.16.0
OS: linux x64
Angular: 8.2.2
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.802.2
@angular-devkit/build-angular              0.802.2
@angular-devkit/build-optimizer            0.802.2
@angular-devkit/build-webpack              0.802.2
@angular-devkit/core                       8.2.2
@angular-devkit/schematics                 8.2.2
@angular/platform-server                   8.2.4
@ngtools/webpack                           8.2.2
@nguniversal/common                        0.0.0
@nguniversal/express-engine                0.0.0
@nguniversal/module-map-ngfactory-loader   0.0.0
@schematics/angular                        8.2.2
@schematics/update                         0.802.2
rxjs                                       6.4.0
typescript                                 3.5.3
webpack                                    4.38.0
```

Others:

1. Running `ng serve` still works
</code></pre>

**Comment by KingDarBoja** [comment]
Hello @jcjp,

Can you share your `package.json` file in order to see which `@ng-toolkit` version you using?

Cheers!

**Comment by jcjp** [comment]
> Hello @jcjp,
> 
> Can you share your `package.json` file in order to see which `@ng-toolkit` version you using?
> 
> Cheers!

I actually could not remember, we could have this ticket close as I will not be able to provide the required information/reproduction.
