### ISSUE TITLE
ReferenceError: window is not defined

### ISSUE THREAD

**Issue by sureshdeepal** [maciejtreder/ng-toolkit#681]
## I'm submitting a...

<pre><code>
PS E:\fynd-phase-2-with-ssr\fynd-phase-2> npm run server

> fynd@0.0.7 server E:\fynd-phase-2-with-ssr\fynd-phase-2
> node local.js

It looks like you're using the development build of the Firebase JS SDK.
When deploying Firebase apps to production, it is advisable to only import
the individual SDK components you intend to use.

For the module builds, these are available in the following manner
(replace <PACKAGE> with the name of a component - i.e. auth, database, etc):

CommonJS Modules:
const firebase = require('firebase/app');
require('firebase/<PACKAGE>');

ES Modules:
import firebase from 'firebase/app';
import 'firebase/<PACKAGE>';

Typescript:
import * as firebase from 'firebase/app';
import 'firebase/<PACKAGE>';

E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:160247
Y=$.API,K=J=X="",Y.addMetadata=function(t,e){return J=e||"http://jspdf.default.namespaceuri/",X=t,this.internal.events.subscribe("postPutResources",function(){if(X){var t='<rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"><rdf:Description rdf:about="" xmlns:jspdf="'+J+'"><jspdf:metadata>',e=unescape(encodeURIComponent('<x:xmpmeta xmlns:x="adobe:ns:meta/">')),n=unescape(encodeURIComponent(t)),r=unescape(encodeURIComponent(X)),i=unescape(encodeURIComponent("</jspdf:metadata></rdf:Description></rdf:RDF>")),o=unescape(encodeURIComponent("</x:xmpmeta>")),a=n.length+r.length+i.length+e.length+o.length;K=this.internal.newObject(),this.internal.write("<< /Type /Metadata /Subtype /XML /Length "+a+" >>"),this.internal.write("stream"),this.internal.write(e+n+r+i+o),this.internal.write("endstream"),this.internal.write("endobj")}else K=""}),this.internal.events.subscribe("putCatalog",function(){K&&this.internal.write("/Metadata "+K+" 0 R")}),this

ReferenceError: window is not defined
    at E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:160247:8032
    at E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:160076:163
    at Object.<anonymous> (E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:160076:177)
    at __webpack_require__ (E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:21:30)
    at Module.<anonymous> (E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:333126:63)
    at __webpack_require__ (E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:21:30)
    at Object.html2pdf.js (E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:307920:18)
    at __webpack_require__ (E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:240795:30)
    at Object../src/app/admin-panel/cash-flow/invoice/invoice.component.ts (E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:280003:21)
    at __webpack_require__ (E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:240795:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fynd@0.0.7 server: `node local.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fynd@0.0.7 server script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ef\AppData\Roaming\npm-cache\_logs\2019-09-03T08_26_47_611Z-debug.log

</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/universal
</code></pre>

## Expected behavior

**Any solution for this?
I tried by those method,** 
https://github.com/hellosign/hellosign-embedded/issues/107#issuecomment-468015714
https://github.com/angular/universal/issues/830#issuecomment-338359090
https://github.com/angular/universal/issues/830#issuecomment-345228799

**_but not working_**

**Comment by Pirateoncrew** [comment]
const DIST_FOLDER = join(process.cwd(), 'dist/deploy/dist');//location to you build directory
const domino = require("domino");
const fs = require("fs");
const path = require("path");
const template = fs
  .readFileSync(path.join(DIST_FOLDER, ".", "index.html"))
  .toString();
const win = domino.createWindow(template);

global["window"] = win;

try to add these code in server.ts/local.ts and run again

**Comment by sureshdeepalh** [comment]
Hay,
**I solved this myself.**  
Im my case I try to implement `global["window"] = win;.` But its not worked for me. 
I found the error from my code. This is the code error 
`E:\fynd-phase-2-with-ssr\fynd-phase-2\dist\server.js:160247
Y=$.API,K=J=X="",Y.addMetadata=function(t,e){return J=e||"http://jspdf.default.namespaceuri/",X=t,this.internal.events.subscribe("postPutResources",function(){if(X){var t='',e=unescape(encodeURIComponent('')),n=unescape(encodeURIComponent(t)),r=unescape(encodeURIComponent(X)),i=unescape(encodeURIComponent("")),o=unescape(encodeURIComponent("")),a=n.length+r.length+i.length+e.length+o.length;K=this.internal.newObject(),this.internal.write("<< /Type /Metadata /Subtype /XML /Length "+a+" >>"),this.internal.write("stream"),this.internal.write(e+n+r+i+o),this.internal.write("endstream"),this.internal.write("endobj")}else K=""}),this.internal.events.subscribe("putCatalog",function(){K&&this.internal.write("/Metadata "+K+" 0 R")}),this`

It is coming from the PDF library what I installed. I remove all the code related to this. Now its working for me. 
I try to find this library. But I didn't install it. But some other library use this service **jspdf** inside there library. 
May be its not the good solution. But this window global not worked for me. 
**My opinion, Read the code error. Some time you may have different plugin error.**

**Comment by KingDarBoja** [comment]
Good to know you solved it 🍰
