### ISSUE TITLE
@ng-toolkit/universal adding problem

### ISSUE THREAD

**Issue by anantksingh** [maciejtreder/ng-toolkit#686]
I am getting error when adding ng add @ng-toolkit/universal
Error:
Invalid regular expression flags
/var/www/html/altabookingangular/frontend/node_modules/@ng-toolkit/universal/schematics.js:199
            tree.overwrite(`/${options.serverFileName}`, test_1.getFileContent(tree, `/${options.serverFileName}`).replace(/\/\/ Start up the Node server.*/gs, '').replace('const app = express();', 'export const app = express();'));
                                                                                                                           ^

SyntaxError: Invalid regular expression flags
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at new ExportStringRef (/var/www/html/project/frontend/node_modules/@angular-devkit/schematics/tools/export-ref.js:18:25)

Angular CLI: 6.0.8
Node: 8.9.0
OS: linux x64
Angular: 6.1.10
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.6.8
@angular-devkit/build-angular     0.10.7
@angular-devkit/build-optimizer   0.10.7
@angular-devkit/build-webpack     0.10.7
@angular-devkit/core              0.6.8
@angular-devkit/schematics        0.6.8
@angular/cli                      6.0.8
@angular/fire                     5.2.1
@ngtools/webpack                  7.0.7
@schematics/angular               0.6.8
@schematics/update                0.6.8
rxjs                              6.0.0
typescript                        2.7.2
webpack                           4.19.1

**Comment by KingDarBoja** [comment]
Hello @anantksingh,

Please checkout #578, there is a proper way of adding ng-toolkit/universal to your project.

Cheers!
