### ISSUE TITLE
ng-toolkit/universal implementation issue 

### ISSUE THREAD

**Issue by anantksingh** [maciejtreder/ng-toolkit#687]
I installed the ng-toolkit/universal  but when i use npm run build:prod i am getting error
anant@anant:/var/www/html/angular8$ sudo npm run build:prod

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 0x353aeedbe1d]
Security context: 0x1706a6c1e6e9 <JSObject>
    1: new Node [0x2cfbb80aa799] [/var/www/html/angular8/node_modules/acorn/dist/acorn.js:~2929] [pc=0x353b35c9d73](this=0x0a22ecd68db9 <Node map = 0x3b3f59492531>,parser=0x0a22ecd23ed9 <Parser map = 0x32c0a7b7eb11>,pos=7083,loc=0x0a22ecd68a49 <Position map = 0x21b56345cc49>)
    2: ConstructFrame [pc: 0x353aee8d02f]
    3: /* anonymous */ [0x3d78f6a70dd9] [/...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0x8fa0c0 node::Abort() [ng build --prod]
 2: 0x8fa10c  [ng build --prod]
 3: 0xb0026e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [ng build --prod]
 4: 0xb004a4 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [ng build --prod]
 5: 0xef49b2  [ng build --prod]
 6: 0xef4ab8 v8::internal::Heap::CheckIneffectiveMarkCompact(unsigned long, double) [ng build --prod]
 7: 0xf00b92 v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags) [ng build --prod]
 8: 0xf014c4 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [ng build --prod]
 9: 0xf04131 v8::internal::Heap::AllocateRawWithRetryOrFail(int, v8::internal::AllocationSpace, v8::internal::AllocationAlignment) [ng build --prod]
10: 0xecd5b4 v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [ng build --prod]
11: 0x116d73e v8::internal::Runtime_AllocateInNewSpace(int, v8::internal::Object**, v8::internal::Isolate*) [ng build --prod]
12: 0x353aeedbe1d 
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! altabooking@0.0.0 build:client-and-server-bundles: `ng build --prod && ng run angular.io-example:server`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the altabooking@0.0.0 build:client-and-server-bundles script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anant/.npm/_logs/2019-09-13T04_59_33_887Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! altabooking@0.0.0 build:prod: `npm run build:client-and-server-bundles && npm run webpack:server`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the altabooking@0.0.0 build:prod script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/anant/.npm/_logs/2019-09-13T04_59_33_931Z-debug.log

**Comment by KingDarBoja** [comment]
I don't think it is related to this package, since it is a [known Angular issue](https://github.com/angular/angular-cli/issues/13734).
