### ISSUE TITLE
ERROR: Cannot read property 'unshift' of undefined

### ISSUE THREAD

**Issue by ribomation** [maciejtreder/ng-toolkit#688]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

ERROR: Cannot read property 'unshift' of undefined
No files added nor updated.

## Expected behavior

install/edit files for @ng-toolkit/universal

## Minimal reproduction of the problem with instructions

npx ng new myproj
cd myproj
npx ng add @ng-toolkit/universal

## Environment

<pre><code>
Angular version: 8.2.6

- Node version: 10.16.2  
- Platform: Ubuntu 18.04 @ WLS @ Windows 10 

Others:

</code></pre>

**Comment by rand42studios** [comment]
FYI, if you run into this error (ERROR: Cannot read property ‘unshift’ of undefined) when running the ng add @ng-toolkit/universal command, use ng add @ng-toolkit/universal@7.1.2 command.

https://medium.com/@verde.mateo.a/fyi-if-you-run-into-this-error-error-cannot-read-property-unshift-of-undefined-when-running-a8e06a520d6b

**Comment by KingDarBoja** [comment]
@rand42studios Nice finding, although seems weird that the installed version from the linked github issue (at medium post) is not the same that latest one.

**Comment by jpthirumalai** [comment]
Fixed the error "cannot read property 'unshift' of undefined" while executing ng add @ng-toolkit/universal using the steps:
Step 1:@ng-toolkit/universal, in package.json appears the new dependency, (might be with older version dependency but in 1.1.2 version "@ng-toolkit/universal": "1.1.21",)
Step 2:Delete universal folder in the location node_modules\@ng-toolkit
Step 3: Change the line in package.json to 7.1.2:: "@ng-toolkit/universal": "7.1.2",
Step 4: now run the command ng add @ng-toolkit/universal@7.1.2

**Comment by KingDarBoja** [comment]
Closed for housekeeping reasons.
