### ISSUE TITLE
Main file (/src/main.server.ts) not found

### ISSUE THREAD

**Issue by ehsaaan** [maciejtreder/ng-toolkit#692]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Hello @ehsaaan,

Probably the `tsconfig` files are not pointing to the proper path of `main.server.ts` file.

Please provide the entire error description to see if it is cause by that.

Cheers!
