### ISSUE TITLE
isn't install @ng-toolkit/universal

### ISSUE THREAD

**Issue by thrahul6396** [maciejtreder/ng-toolkit#697]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by stefan-karlsson** [comment]
Really bad issue explanation, but yes i can confirm that there is a issue when trying to run ng add on angular 8

**Comment by KingDarBoja** [comment]
⚠️ Closed as invalid issue. Please, fill the issue template when opening new issues in order to help us track the bug.

@stefan-karlsson Check out [this comment](https://github.com/maciejtreder/ng-toolkit/issues/695#issuecomment-538754705).

Cheers!
