### ISSUE TITLE
Can't add ng-toolkit/universal to existing Angular 8 project.

### ISSUE THREAD

**Issue by mmiedzianyy** [maciejtreder/ng-toolkit#699]
## In package
<pre><code>
@ng-toolkit/universal
</code></pre>

## Current behavior
I can't add ng-toolkit/universal to my angular 8 project.
running <code>ng add @ng-toolkit/universal</code> fails with this error:
ERROR: Cannot read property 'architect' of undefined

## Environment
<pre><code>
- Angular version: 8.0.0
- Node version: 10.15.0
- Platform:  Windows

</code></pre>

**Comment by mmiedzianyy** [comment]
I managed to fix the issue when ussing <code>ng add @ng-toolkit/universal@7.1.2</code>.

**Comment by mmiedzianyy** [comment]
I managed to fix this by using <code>ng add @ng-toolkit/universal@7.1.2</code>

**Comment by nachbarshund** [comment]
Same here 😑

**Comment by Roman-Molchanov** [comment]
+1

**Comment by SwapnilSoni1999** [comment]
same

**Comment by KingDarBoja** [comment]
Please check [this comment](https://github.com/maciejtreder/ng-toolkit/issues/683#issuecomment-540507947) in order to get rid of that error.

Also, hopefully a new version is gonna be released soon which should fix those error messages.

Cheers!

**Comment by mmiedzianyy** [comment]
@KingDarBoja I've tried your suggested solution but it didn't work.
Still getting the same error.

**Comment by mmiedzianyy** [comment]
So I found the workarround.
`ng add @nguniversal/express-engine --clientProject {projectName}`
`npm install @nguniversal/common --save`
`ng add @ng-toolkit/universal@7.1.2`

**Comment by KingDarBoja** [comment]
@mmiedzianyy So looks like you used the latest version of `ng-toolkit/universal` (`8.0.3`) which was released a few days ago. You shouldn't need to install any of those stuff, only run `ng add @ng-toolkit/universal` and that's it!

**Comment by mmiedzianyy** [comment]
Thanks for the reply @KingDarBoja, but the problem persists. This is why I had to install all this packages.
`ng add @ng-toolkit/universal@8.0.3` still produces the same error
**ERROR: Cannot read property 'architect' of undefined**.

**Comment by KingDarBoja** [comment]
@mmiedzianyy Can you open a new issue and share a repo to look at it? If not, provide `package.json` and `angular.json` to checkout if something is missing please?
