### ISSUE TITLE
Path "/local.js" does not exist

### ISSUE THREAD

**Issue by wishalGawande** [maciejtreder/ng-toolkit#700]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Closed as no information being provided according to the issue template.

Also a new version is arriving these days, it should fix those errors among others.

Cheers!
