### ISSUE TITLE
while installing ng-toolkit/universal i am getting the following errors

### ISSUE THREAD

**Issue by himanshupatni** [maciejtreder/ng-toolkit#703]
INFO: Project property is set to 'seo'.
ERROR: Cannot read property 'unshift' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done.

**Comment by KingDarBoja** [comment]
Please take a look at #695.
