### ISSUE TITLE
Problem with @ng-toolkit/_utils

### ISSUE THREAD

**Issue by maciejtreder** [maciejtreder/ng-toolkit#708]
I really don't know what's the issue. Probably `@ng-toolkit/_utils` it's not published in the proper way. Unfortunately, all the packages which depend on those, are unable to properly consume this package, which leads to:

```
Error: Cannot find module '@ng-toolkit/_utils/testing
```

The problem doesn't occur on my local environment (by running ./scripts/deploy_verdaccio.sh), it occurs only on the Travis CI.

**Comment by KingDarBoja** [comment]
What if you publish the `@ng-toolkit/_utils` only by using travis in order to see what's being published on npm?

**Comment by maciejtreder** [comment]
I am not sure if I got your point. I checked also publication from the master branch (that goes directly to the npm, not to Verdaccio). From Travis it is not working (the `npm test` fails, because it can't load `@ng-toolkit/_utils`

I run the publish script from my machine - worked without any problem...

**Comment by maciejtreder** [comment]
Looks like Travis is using some strange way of installing dependencies, or we have bad setup for node... No idea...
