### ISSUE TITLE
ERROR: project_1.getProject is not a function

### ISSUE THREAD

**Issue by Rahul0023** [maciejtreder/ng-toolkit#712]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
"@ng-toolkit/_utils": "^8.0.1",
    "@ng-toolkit/init": "^7.1.0",
    "@ng-toolkit/pwa": "^8.0.1",
    "@ng-toolkit/universal": "^7.1.2",
</code></pre>

## Environment

<pre><code>
Angular CLI : 6.2.5
Angular version: 6.1.10

- Node version: 10.17.0 
- Platform:  linux x64

Others:
@angular-devkit/architect         0.8.9
@angular-devkit/build-angular     0.8.9
@angular-devkit/build-optimizer   0.8.9
@angular-devkit/build-webpack     0.8.9
@angular-devkit/core              0.8.9
@angular-devkit/schematics        0.8.5
@angular/animations               9.0.0-next.14
@angular/cdk                      6.4.7
@angular/cli                      6.2.5
@angular/compiler-cli             6.1.3
@angular/flex-layout              7.0.0-beta.24
@angular/material                 6.4.7
@ngtools/webpack                  6.2.9
@schematics/angular               0.8.5
@schematics/update                0.8.5
rxjs                              6.2.2
typescript                        2.7.2
webpack                           4.16.4

**Comment by KingDarBoja** [comment]
@maciejtreder We forgot to update `ng-toolkit/init`? Because at the npm, it is still at `7.1.2`. Maybe this is the reason of the above issue.

**Comment by KingDarBoja** [comment]
Closing now for housekeeping purposes.

The `@ng-toolkit/init` package has been updated to `8.0.3` today, so everything should be working as intended.
