### ISSUE TITLE
i had an error 

### ISSUE THREAD

**Issue by mstfch2020** [maciejtreder/ng-toolkit#714]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
⚠️ Closing as no information being provided following the issue template.

Please fill the tempalte with everything we ask for, so we can pinpoint what's causing the bug.

Cheers!
