### ISSUE TITLE
Cannot read property 'architect' of undefined: ArchLinux

### ISSUE THREAD

**Issue by SwapnilSoni1999** [maciejtreder/ng-toolkit#716]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[x] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
I have installed `@ng-toolkit/init` as global package then I tried to start a new project with `ng new --collection @ng-toolkit/init myApp` and it thrown an error

## Expected behavior
It says `ERROR: Cannot read property 'architect' of undefined` instead it should detect linux and proceed further steps

## Minimal reproduction of the problem with instructions
I have tried this in ArchLinux with KDE Plasma(tho this shouldn't matter)

## Environment

<pre><code>
Angular version: 8.3.14

- Node version: 12.12.0  
- Platform: Linux (ArchLinux to be precise) 

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
@SwapnilSoni1999 We are aware of the bug and it should be fixed in the next version.

For some reason, the deployment wasn't successful for this package in the past few days, so we are working on delivering it as quick as possible.

**Comment by SwapnilSoni1999** [comment]
sure will test whenever you release

**Comment by KingDarBoja** [comment]
@SwapnilSoni1999 Can you update to latest version and try again? 🍰

**Comment by KingDarBoja** [comment]
Closing as this should be fixed already.
