### ISSUE TITLE
Universal render using Curl but not on View Source

### ISSUE THREAD

**Issue by jigneshInd** [maciejtreder/ng-toolkit#720]
## I'm submitting a...

<pre><code>
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
I have used universal tookit version 7.1.2 for server-side rendering, when i check view source of it its not showing, but when i refresh whole page its showing.

## Expected behavior
Using CURL commands its also showing rendered HTML but not in view source, can you please advise why this happens?

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

</code></pre>

**Comment by KingDarBoja** [comment]
Hello @jigneshInd,

What do you mean by *View Source*? Are you refering to the Chrome Inspector?

If you are trying to look at the source code, you should be aware that any Typescript code is going to be transpiled into Javascript one and also Angular has its own mechanism to render HTML along with the generated Javascript files.

In fact, you should be able to checkout the generated template by using *curl*  or using Chrome Dev Tools as _Inspect_ and such things. Also, you have to be aware of running the app on either `development` or `production` as both stages differ on how the code is being generated and hence optimized.

So not sure what's going on unless you provide more information about the problem you are trying to describe, maybe a screenshot showing what you wanna achieve, uh?

Cheers!

**Comment by jigneshInd** [comment]
Hello @KingDarBoja,

As when Server Side Rendering works properly we able to view the Dyanamic rendered page source by Right-click on the page then View page Source, right? but sometimes it is not showing,
but the same URL we do use Curl like: curl <website url> on the terminal generates the complete source code with a dynamic view also, so does this behavior is ok?

Is there any other way so we can check Server Side Rendering works perfectly?


Thanks!

**Comment by KingDarBoja** [comment]
@jigneshInd Yeah, it is the expected behaviour while using curl, to get a render HTML from our webpage.

About the `View page Source`, it should display the HTML with all your dynamic stuff **everytime**. Maybe it isn't showing everytime due to a server issue 🤔
