### ISSUE TITLE
SyntaxError: Cannot use import statement outside a module

### ISSUE THREAD

**Issue by jginorio** [maciejtreder/ng-toolkit#721]
## I'm submitting a...

<pre><code>
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

When I run "npm run server" after running "npm run build:prod"(everything compiles successfully) I get the following error:
<pre><code>
`/Users/wayne/Documents/NodeJS/finditv1/dist/server.js:259666
import { CommonModule } from '@angular/common';
^^^^^^

SyntaxError: Cannot use import statement outside a module`
</code></pre>

I have tried the following:
- uninstalling and installing again @ng-toolkit/universal
- erasing the dist and running "npm run build:prod" again
- removing node_modules and installing them again

## package.json
<pre><code>
{
  "name": "find-itv1",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve --proxy-config proxy-conf.json",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node local.js",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run find-itv1:server:production",
    "server": "node local.js",
    "build:prod": "npm run build:ssr",
    "serve:prerender": "node static.js",
    "build:prerender": "npm run build:prod && node dist/prerender.js"
  },
  "private": true,
  "dependencies": {
    "@agm/core": "^1.0.0-beta.5",
    "@angular-material-extensions/google-maps-autocomplete": "^1.5.0",
    "@angular-material-extensions/password-strength": "^4.0.0",
    "@angular/animations": "^7.2.4",
    "@angular/cdk": "^7.3.2",
    "@angular/common": "~7.2.0",
    "@angular/compiler": "~7.2.0",
    "@angular/core": "~7.2.0",
    "@angular/flex-layout": "^7.0.0-beta.24",
    "@angular/forms": "~7.2.0",
    "@angular/http": "~7.2.0",
    "@angular/material": "^7.3.2",
    "@angular/platform-browser": "~7.2.0",
    "@angular/platform-browser-dynamic": "~7.2.0",
    "@angular/platform-server": "~7.2.0",
    "@angular/router": "~7.2.0",
    "@fortawesome/angular-fontawesome": "^0.3.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.25",
    "@fortawesome/free-brands-svg-icons": "^5.11.2",
    "@fortawesome/free-solid-svg-icons": "^5.11.2",
    "@mapbox/mapbox-gl-directions": "^4.0.0",
    "@mapbox/mapbox-gl-geocoder": "^3.1.1",
    "@ng-toolkit/universal": "^7.1.2",
    "@ngui/map": "^0.30.3",
    "@nguniversal/common": "0.0.0",
    "@nguniversal/express-engine": "0.0.0",
    "@nguniversal/module-map-ngfactory-loader": "0.0.0",
    "@types/geojson": "^7946.0.7",
    "@types/googlemaps": "^3.30.19",
    "@types/mapbox-gl": "^0.51.7",
    "angular-font-awesome": "^3.1.2",
    "angularfire2": "^5.1.1",
    "aws-serverless-express": "^3.2.0",
    "bootstrap": "^4.3.1",
    "core-js": "^2.5.4",
    "cors": "~2.8.4",
    "cp-cli": "^1.1.0",
    "domino": "^2.1.3",
    "express": "^4.15.2",
    "hammerjs": "^2.0.8",
    "jquery": "^3.4.1",
    "libphonenumber-js": "^1.7.21",
    "mapbox-gl": "^1.0.0",
    "mapbox-gl-directions": "^3.0.3",
    "ng-lazyload-image": "^7.0.1",
    "ng2-file-upload": "^1.3.0",
    "ng4-loading-spinner": "^1.2.3",
    "ngx-device-detector": "^1.3.5",
    "ngx-loader-indicator": "^7.1.2",
    "ngx-mapbox-gl": "^3.0.1",
    "ngx-mask": "^8.0.1",
    "ngx-mat-intl-tel-input": "^2.0.2",
    "ngx-quicklink": "^0.1.5",
    "ngx-slick-carousel": "^0.4.6",
    "popper.js": "^1.14.7",
    "rxjs": "~6.3.3",
    "slick-carousel": "^1.8.1",
    "tslib": "^1.9.0",
    "zone.js": "~0.8.26"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.13.0",
    "@angular/cli": "~7.3.0",
    "@angular/compiler-cli": "~7.2.0",
    "@angular/language-service": "~7.2.0",
    "@types/jasmine": "~2.8.8",
    "@types/jasminewd2": "~2.0.3",
    "@types/node": "~8.9.4",
    "codelyzer": "~4.5.0",
    "jasmine-core": "~2.99.1",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "^4.4.1",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~1.1.2",
    "karma-jasmine-html-reporter": "^0.2.2",
    "node-sass": "^4.13.0",
    "protractor": "~5.4.0",
    "ts-loader": "^5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.11.0",
    "typescript": "~3.2.2",
    "webpack-cli": "^3.1.0"
  }
}

</code></pre>

**I also want to mention that I am doing lazy loading, don't know if that has to do with that but just in case.** 
## Environment

<pre><code>
Angular version: 7.3.9

- Node version: v10.16.3
- Platform:  Mac

**Comment by jginorio** [comment]
Is a 'mapbox-gl' issue, as soon as I remove the package everything was working again.

**Comment by KingDarBoja** [comment]
> Is a 'mapbox-gl' issue, as soon as I removed the package everything was working again.

Glad to know you found the issue cause. 🚀
