### ISSUE TITLE
ERROR ReferenceError: alert is not defined

### ISSUE THREAD

**Issue by ARoshanZamir** [maciejtreder/ng-toolkit#725]
I want to use  `windows.location.href`

```
import { Component, OnInit, Inject } from "@angular/core";
import { WINDOW, LOCAL_STORAGE } from "@ng-toolkit/universal";

export class AppComponent implements OnInit {
  constructor(
    @Inject(WINDOW) private window: Window,
    @Inject(LOCAL_STORAGE) private localStorage: any
  ) {}

  ngOnInit(): void {
    alert(this.window.location.href);
  }
}
```

the problem is I get the following error in the terminal of vscode:

> ERROR ReferenceError: alert is not defined
    at AppComponent.ngOnInit (K:\univerpro\dist\server.js:119317:9)
    at checkAndUpdateDirectiveInline (K:\univerpro\dist\server.js:90736:19)
    at checkAndUpdateNodeInline (K:\univerpro\dist\server.js:102070:20)
    at checkAndUpdateNode (K:\univerpro\dist\server.js:102009:16)
    at prodCheckAndUpdateNode (K:\univerpro\dist\server.js:102863:5)
    at Object.updateDirectives (K:\univerpro\dist\server.js:158381:291)
    at Object.updateDirectives (K:\univerpro\dist\server.js:102483:39)
    at Object.checkAndUpdateView (K:\univerpro\dist\server.js:101974:14)
    at ViewRef_.detectChanges (K:\univerpro\dist\server.js:90035:22)
    at core_ApplicationRef.tick (K:\univerpro\dist\server.js:98936:22)

But when I alert the ` windows.location.href `  everything works great.

Where is my problem?

## My Package.Json
<pre><code>
{
  "name": "univerpro",
  "version": "0.0.0",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e",
    "compile:server": "webpack --config webpack.server.config.js --progress --colors",
    "serve:ssr": "node local.js",
    "build:ssr": "npm run build:client-and-server-bundles && npm run compile:server",
    "build:client-and-server-bundles": "ng build --prod && ng run univerpro:server:production --bundleDependencies all",
    "server": "node local.js",
    "build:prod": "npm run build:ssr",
    "serve:prerender": "node static.js",
    "build:prerender": "npm run build:prod && node dist/prerender.js"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "~8.2.13",
    "@angular/common": "~8.2.13",
    "@angular/compiler": "~8.2.13",
    "@angular/core": "~8.2.13",
    "@angular/forms": "~8.2.13",
    "@angular/platform-browser": "~8.2.13",
    "@angular/platform-browser-dynamic": "~8.2.13",
    "@angular/platform-server": "~8.2.13",
    "@angular/router": "~8.2.13",
    "@ng-toolkit/universal": "^8.0.3",
    "@nguniversal/express-engine": "8.1.1",
    "@nguniversal/module-map-ngfactory-loader": "8.1.1",
    "express": "^4.15.2",
    "rxjs": "~6.4.0",
    "tslib": "^1.10.0",
    "zone.js": "~0.9.1",
    "@nguniversal/common": "8.1.0",
    "domino": "^2.1.3"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.803.18",
    "@angular/cli": "~8.3.18",
    "@angular/compiler-cli": "~8.2.13",
    "@angular/language-service": "~8.2.13",
    "@types/node": "~8.9.4",
    "@types/jasmine": "~3.3.8",
    "@types/jasminewd2": "~2.0.3",
    "codelyzer": "^5.0.0",
    "jasmine-core": "~3.4.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.1.0",
    "karma-chrome-launcher": "~2.2.0",
    "karma-coverage-istanbul-reporter": "~2.0.1",
    "karma-jasmine": "~2.0.1",
    "karma-jasmine-html-reporter": "^1.4.0",
    "protractor": "~5.4.0",
    "ts-loader": "^5.2.0",
    "ts-node": "~7.0.0",
    "tslint": "~5.15.0",
    "typescript": "~3.5.3",
    "webpack-cli": "^3.1.0"
  }
}

</code></pre>

**Comment by KingDarBoja** [comment]
Hello @ARoshanZamir, you should be aware that any DOM related object like `alert` or `window` is not defined on server side as Node.js doesn't have such definitions.

What I should recommend is wrapping your alert line inside a **if** statement which checks if the platform is browser.

```ts
import { PLATFORM_ID } from '@angular/core';
import { isPlatformBrowser, isPlatformServer } from '@angular/common';

constructor(@Inject(PLATFORM_ID) platformId: Object) {
  this.isBrowser = isPlatformBrowser(platformId);
}

ngOnInit() {
   if (this.isBrowser) { 
       alert('we're in the browser!');
    }
}
```
