### ISSUE TITLE
Cannot read property 'statements' of undefined

### ISSUE THREAD

**Issue by mhmdbahja** [maciejtreder/ng-toolkit#727]
## I'm submitting a...

<pre><code>
[x ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
Installing packages for tooling via npm.
npm WARN deprecated bugsnag@2.4.3: All projects should upgrade to our universal JS notifier: "@bugsnag/js". See https://github.com/bugsnag/bugsnag-js/blob/master/UPGRADING.md for more details.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN @alyle/ui@2.7.0 requires a peer of chroma-js@^1.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/common@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/core@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/express-engine@7.1.1 requires a peer of @angular/platform-server@^7.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @ng-toolkit/universal@7.1.2
added 2 packages from 1 contributor and audited 58429 packages in 10.792s
found 851 vulnerabilities (1 moderate, 849 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
ERROR: Cannot read property 'statements' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
npm WARN @alyle/ui@2.7.0 requires a peer of chroma-js@^1.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/express-engine@7.1.1 requires a peer of @angular/platform-server@^7.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/common@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/core@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 58429 packages in 5.013s
found 851 vulnerabilities (1 moderate, 849 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN @alyle/ui@2.7.0 requires a peer of chroma-js@^1.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/express-engine@7.1.1 requires a peer of @angular/platform-server@^7.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/common@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/core@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 58429 packages in 5.159s
found 851 vulnerabilities (1 moderate, 849 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Nothing to be done.

## Expected behavior
Installing packages for tooling via npm.
npm WARN deprecated bugsnag@2.4.3: All projects should upgrade to our universal JS notifier: "@bugsnag/js". See https://github.com/bugsnag/bugsnag-js/blob/master/UPGRADING.md for more details.
npm WARN deprecated core-js@1.2.7: core-js@<2.6.8 is no longer maintained. Please, upgrade to core-js@3 or at least to actual version of core-js@2.
npm WARN @alyle/ui@2.7.0 requires a peer of chroma-js@^1.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/common@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/core@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/express-engine@7.1.1 requires a peer of @angular/platform-server@^7.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

+ @ng-toolkit/universal@7.1.2
added 2 packages from 1 contributor and audited 58429 packages in 10.792s
found 851 vulnerabilities (1 moderate, 849 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Installed packages for tooling via npm.
ERROR: Cannot read property 'statements' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
npm WARN @alyle/ui@2.7.0 requires a peer of chroma-js@^1.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/express-engine@7.1.1 requires a peer of @angular/platform-server@^7.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/common@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/core@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 58429 packages in 5.013s
found 851 vulnerabilities (1 moderate, 849 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
npm WARN @alyle/ui@2.7.0 requires a peer of chroma-js@^1.3.6 but none is installed. You must install peer dependencies yourself.
npm WARN @nguniversal/express-engine@7.1.1 requires a peer of @angular/platform-server@^7.1.4 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-file-uploader@5.0.2 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/common@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular-notifier@4.1.1 requires a peer of @angular/core@>= 6.0.0 < 7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

audited 58429 packages in 5.159s
found 851 vulnerabilities (1 moderate, 849 high, 1 critical)
  run `npm audit fix` to fix them, or `npm audit` for details
Nothing to be done.

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
@mhmdbahja Can you share a repo in order to check out what's going on? Cheers!
