### ISSUE TITLE
Cannot find module '@schematics/angular/utility/workspace'

### ISSUE THREAD

**Issue by akashakki** [maciejtreder/ng-toolkit#728]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
⚠️ Closing now as didn't filled the issue template with relevant information for us.

Please edit this issue with the info in order to reopen this.
