### ISSUE TITLE
Use serverless with custom webpack builder

### ISSUE THREAD

**Issue by cubitworx** [maciejtreder/ng-toolkit#732]
## I'm submitting a...
```
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
```

## In package
```
[ ] @ng-toolkit/init
[X] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
```

## Current behavior
Running `ng add @ng-toolkit/serverless  —-provider aws` on an angular app where you are using `@angular-builders/custom-webpack:browser` for the `architect > build > builder ` configuration produces an error as follows:
```
Browser build not found (lack of entry with build-angular:browser builder) in angular.json
```

Updating `angular.json` to use the default builder `@angular-devkit/build-angular:browser` and then running `ng add @ng-toolkit/serverless  —-provider aws` solves the immediate problem.

I have not yet determined if this has unforeseen consequences given that I then revert the builder back to `@angular-builders/custom-webpack:browser` after the script as completed.

Configuration that does produce error
```
{
  "projects": {
    "xxx": {
      "architect": {
        "build": {
          "builder": "@angular-builders/custom-webpack:browser",
```

Configuration that does not produce error
```
{
  "projects": {
    "xxx": {
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
```

## Expected behavior
Should successfully configure the serverless functionality regardless of what builder is used

## Minimal reproduction of the problem with instructions
1. Create default angular-cli installation
2. Replace `@angular-devkit/build-angular:browser` with `@angular-builders/custom-webpack:browser` (the custom configuration is irrelevant for reproduction purposes)
3. Run `ng add @ng-toolkit/serverless  —-provider aws`

## What is the motivation / use case for changing the behavior?
Fix to allow ng-toolkit/serverless to update an angular project which is not using `@angular-devkit/build-angular:browser` as the builder

## Environment

<pre><code>
Angular version: 8.2.14

- Node version: 10.15.3
- Platform: Windows
</code></pre>

**Comment by KingDarBoja** [comment]
Upcoming version should support Angular 10 and not need any changes to the browser builder at `angular.json` file.
