### ISSUE TITLE
Unable to fetch package metadata: Only absolute URLs are supported

### ISSUE THREAD

**Issue by eliavmaman** [maciejtreder/ng-toolkit#735]
## I'm submitting a...

 Bug report  

## In package

[ ] @ng-toolkit/serverless

## Current behavior
when i try to run the command " ng add @ng-toolkit/universal"
I get Unable to fetch package metadata: Only absolute URLs are supported"

"@angular/cli": "8.0.4",`
node :v10.16.0

**Comment by KingDarBoja** [comment]
Hello @eliavmaman 

This error is not related to the package but rather npm issue. Maybe you have something that is not properly configured on your project.

It is better to post the question on StackOverflow and provide more info like as sample repository to look at.

Cheers!
