### ISSUE TITLE
ng add @ng-toolkit/universal not creating

### ISSUE THREAD

**Issue by RodjFlores** [maciejtreder/ng-toolkit#740]
## I'm submitting a...

<pre><code>
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

Does not create any of the files.
## Expected behavior

Outputs 
src/
  index.html                 app web page
  main.ts                    bootstrapper for client app
  main.server.ts             * bootstrapper for server app
  style.css                  styles for the app
  app/ ...                   application code
    app.server.module.ts     * server-side application module
server.ts                    * express web server
tsconfig.json                TypeScript client configuration
tsconfig.app.json            TypeScript client configuration
tsconfig.server.json         * TypeScript server configuration
tsconfig.spec.json           TypeScript spec configuration
package.json                 npm configuration
webpack.server.config.js     * webpack server configuration

## Minimal reproduction of the problem with instructions

download example file from https://angular.io/tutorial
npm i
ng add @ng-toolkit/universal
results in "ERROR: Cannot read property 'kind' of undefined" & no files created

also tried ng add @nguniversal/express-engine --clientProject angular.io-example
results in "Cannot read property 'kind' of undefined" & no files created

## Environment

<pre><code>
Angular CLI: 8.3.20
Node: 10.15.3
OS: darwin x64
Angular: 8.2.14
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, platform-server
... router, upgrade

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.800.0
@angular-devkit/build-angular     0.800.0
@angular-devkit/build-optimizer   0.800.0
@angular-devkit/build-webpack     0.800.0
@angular-devkit/core              8.0.0
@angular-devkit/schematics        8.3.20
@angular/cli                      8.3.20
@ngtools/webpack                  8.0.0
@nguniversal/express-engine       8.2.6
@schematics/angular               8.3.20
@schematics/update                0.803.20
rxjs                              6.5.3
typescript                        3.4.5
webpack                           4.30.0
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Hello @RodjFlores 

Please take a look at [this comment](https://github.com/angular/universal/issues/1329#issuecomment-564320999).
