### ISSUE TITLE
Universal tool kit not showing the Render HTML source code after updates

### ISSUE THREAD

**Issue by inextsol** [maciejtreder/ng-toolkit#742]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior
I have a website/application already build in Angular.

## Expected behavior
I have installed the Angular Universal Toolkit in my already working application/website. After installation there were many errors, warning and issues but that have solved and application started working but still the HTML source code is not showing. So basically the Universal toolkit functionality is still missing.

## Environment

<pre><code>
Angular version: 8.3.21 (Global)
Angular version: 7.3.8 (Local)

- Node version: 10.16.3  
- Platform:  Linux

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Duplicated of #743.
