### ISSUE TITLE
 ENOENT: no such file or directory, open 'node_modules\@ng-toolkit\init\@ng-toolkit\_utils@8.0.3'

### ISSUE THREAD

**Issue by AmaelN** [maciejtreder/ng-toolkit#746]
## I'm submitting a...

<pre><code>
[ x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ X] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

ng-toolkit/_utils get located correctly and not based on the current file location.

see log error 
375 silly mapToRegistry uri https://registry.npmjs.org/@ng-toolkit%2ffirebug
376 verbose addNameVersion registry:https://registry.npmjs.org/@ng-toolkit%2ffirebug not in flight; fetching
377 verbose get https://registry.npmjs.org/@ng-toolkit%2ffirebug not expired, no request
378 silly cache afterAdd @ng-toolkit/firebug@8.0.3
379 verbose afterAdd C:\Users\Amael\AppData\Roaming\npm-cache\@ng-toolkit\firebug\8.0.3\package\package.json not in flight; writing
380 verbose correctMkdir C:\Users\Amael\AppData\Roaming\npm-cache correctMkdir not in flight; initializing
381 verbose afterAdd C:\Users\Amael\AppData\Roaming\npm-cache\@ng-toolkit\firebug\8.0.3\package\package.json written
382 silly rollbackFailedOptional Starting
383 silly rollbackFailedOptional Finishing
384 silly runTopLevelLifecycles Finishing
385 silly install printInstalled
386 verbose stack Error: ENOENT: no such file or directory, open 'C:\dev\test\node_modules\@ng-toolkit\init\@ng-toolkit\_utils@8.0.3'
387 verbose cwd C:\dev\test
388 verbose Windows_NT 10.0.18362
389 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Amael\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "@ng-toolkit/init"
390 verbose node v10.16.0
391 verbose npm  v4.4.1
392 error path C:\dev\test\node_modules\@ng-toolkit\init\@ng-toolkit\_utils@8.0.3
393 error code ENOENT
394 error errno -4058
395 error syscall open
396 error enoent ENOENT: no such file or directory, open 'C:\dev\test\node_modules\@ng-toolkit\init\@ng-toolkit\_utils@8.0.3'
397 error enoent ENOENT: no such file or directory, open 'C:\dev\test\node_modules\@ng-toolkit\init\@ng-toolkit\_utils@8.0.3'
397 error enoent This is most likely not a problem with npm itself
397 error enoent and is related to npm not being able to find a file.
398 verbose exit [ -4058, true ]

## Expected behavior

The _utils get placed correctly

## Minimal reproduction of the problem with instructions

npm install --save @ng-toolkit/pwa

## Environment

<pre><code>
Angular version: X.Y.Z

Package                                    Version
--------------------------------------------------------------------
@angular-devkit/architect                  0.803.20
@angular-devkit/build-angular              0.803.20
@angular-devkit/build-optimizer            0.803.20
@angular-devkit/build-webpack              0.803.20
@angular-devkit/core                       8.3.20
@angular-devkit/schematics                 8.3.20
@angular/cli                               8.3.20
@angular/pwa                               0.803.21
@ngtools/webpack                           8.3.20
@nguniversal/common                        8.2.6
@nguniversal/express-engine                8.2.6
@nguniversal/module-map-ngfactory-loader   8.2.6
@schematics/angular                        8.3.20
@schematics/update                         0.803.20
rxjs                                       6.5.3
typescript                                 3.5.3
webpack                                    4.39.2

- Node version: 10.16.0  
- Platform:  Windows  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Hi @AmaelN 

Can you provide how you ran the `ng add` command? Looks like you are trying to setup the `@ng-toolkit/firebug` schematic on your project but now sure what is causing the above error to show up.

Also, sharing the entire `package.json` could help too.
