### ISSUE TITLE
Error in npm run server with @ng-toolkit/universal

### ISSUE THREAD

**Issue by anandrajaram21** [maciejtreder/ng-toolkit#751]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

I am able to say "ng add @ng-toolkit/universal" and "npm run build:prod", but when I say "npm run server" it throws the following error.
Error: Cannot find module 'require("./server/main")'                                                                    Require stack:                                                                                                          - C:\Users\aarti\hlloworld\dist\server.js                                                                               - C:\Users\aarti\hlloworld\local.js                                                                                         at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)                                             at Function.Module._load (internal/modules/cjs/loader.js:690:27)                                                        at Module.require (internal/modules/cjs/loader.js:852:19)                                                               at require (internal/modules/cjs/helpers.js:74:18)                                                                      at Object.<anonymous> (C:\Users\aarti\hlloworld\dist\server.js:25581:18)                                                at __webpack_require__ (C:\Users\aarti\hlloworld\dist\server.js:21:30)                                                  at Module.<anonymous> (C:\Users\aarti\hlloworld\dist\server.js:125:90)                                                  at __webpack_require__ (C:\Users\aarti\hlloworld\dist\server.js:21:30)                                                  at C:\Users\aarti\hlloworld\dist\server.js:85:18                                                                        at Object.<anonymous> (C:\Users\aarti\hlloworld\dist\server.js:88:10) {                                               code: 'MODULE_NOT_FOUND',                                                                                               requireStack: [                                                                                                           'C:\\Users\\aarti\\hlloworld\\dist\\server.js',                                                                         'C:\\Users\\aarti\\hlloworld\\local.js'                                                                               ]                                                                                                                     }                                                                                                                       npm ERR! code ELIFECYCLE                                                                                                npm ERR! errno 1                                                                                                        npm ERR! hlloworld@0.0.0 server: `node local.js`                                                                        npm ERR! Exit status 1                                                                                                  npm ERR!                                                                                                                npm ERR! Failed at the hlloworld@0.0.0 server script.                                                                   npm ERR! This is probably not a problem with npm. There is likely additional logging output above.                                                                                                                                              npm ERR! A complete log of this run can be found in:                                                                    npm ERR!     C:\Users\aarti\AppData\Roaming\npm-cache\_logs\2020-01-04T15_00_59_573Z-debug.log
## Expected behavior

I should get a localhost development server on port 8080.

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Can you provide more information like a sample repo or sharing your `package.json`, `server.ts` and `local.js` files?

**Comment by jagathks** [comment]
I am getting same error,Attaching above requested file for your ref.

[local.zip](https://github.com/maciejtreder/ng-toolkit/files/4077213/local.zip)
