### ISSUE TITLE
Installing ng-toolkit app on IIS

### ISSUE THREAD

**Issue by ingluca888** [maciejtreder/ng-toolkit#752]
I created an Angular 8 app using ng add new and immediately converted with ng-toolkit. The shared hosting has iisnode and url rewrite installed . I did npm run build:prod which created the dist folder, I upladed dist/browser folder, server folder and server.js file. In the root I also uploaded this web config file:

<?xml version="1.0" encoding="UTF-8" ?>
<configuration>
    <system.webServer>
        <handlers>
            <add name="iisnode" path="server.js" verb="*" modules="iisnode" />
        </handlers>
        <rewrite>
            <rules>
                <rule name="mysite">
                    <match url="/*" />
                    <action type="Rewrite" url="server.js" />
                </rule>
            </rules>
        </rewrite>
    </system.webServer>
</configuration>

I get this error:

iisnode encountered an error when processing the request.

HRESULT: 0x2
HTTP status: 500
HTTP subStatus: 1002
HTTP reason: Internal Server Error
You are receiving this HTTP 200 response because system.webServer/iisnode/@devErrorsEnabled configuration setting is 'true'.

In addition to the log of stdout and stderr of the node.exe process, consider using debugging and ETW traces to further diagnose the problem.

The node.exe process has not written any information to stderr or iisnode was unable to capture this information. Frequent reason is that the iisnode module is unable to create a log file to capture stdout and stderr output from node.exe. Please check that the identity of the IIS application pool running the node.js application has read and write access permissions to the directory on the server where the node.js application is located. Alternatively you can disable logging by setting system.webServer/iisnode/@loggingEnabled element of web.config to 'false'.

**Comment by KingDarBoja** [comment]
Hello @ingluca888 

We can't help you with this question as this package doesn't handle such deployment target. Also, this is something which belongs to StackOverflow as this is related to DevOps stuff and not bug on the Angular packages.

Maybe [this](https://stackoverflow.com/questions/56993102/angular-and-node-api-in-iisnode-directory-structure-in-iisnode-not-working) StackOverflow question can help you.

Cheers!
