### ISSUE TITLE
The file (undefined/angular.json) does not exist.

### ISSUE THREAD

**Issue by sdeepak69** [maciejtreder/ng-toolkit#758]
## I'm submitting a...

<pre><code>
[*] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[*] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

[bugsnag] Loaded!
ERROR: The file (undefined/angular.json) does not exist.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
ERROR: The file (//angular.json) does not exist.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
ERROR: Could not read package.json.
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.

## Environment

<pre><code>
Angular CLI: 7.3.9
Node: 12.9.1
OS: linux x64
Angular: 7.2.15

Others:

... animations, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router, service-worker

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.13.9
@angular-devkit/build-angular     0.803.21
@angular-devkit/build-optimizer   0.803.21
@angular-devkit/build-webpack     0.803.21
@angular-devkit/core              7.3.9
@angular-devkit/schematics        7.3.9
@angular/cli                      7.3.9
@angular/fire                     5.2.1
@angular/pwa                      0.12.4
@ngtools/webpack                  8.3.21
@schematics/angular               7.3.9
@schematics/update                0.13.9
rxjs                              6.3.3
typescript                        3.2.4
webpack                           4.39.2
</code></pre>

**Comment by KingDarBoja** [comment]
Please update to latest `@ng-toolkit/universal` version and you should update to Angular 8 too.
