### ISSUE TITLE
Path "/local.js" does not exist.

### ISSUE THREAD

**Issue by alfredho07** [maciejtreder/ng-toolkit#759]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Closed as author doesn't provide any useful information on the issue template.
