### ISSUE TITLE
 Project property is set to 'ngx-admin-demo'. ERROR: Cannot read property 'unshift' of undefined

### ISSUE THREAD

**Issue by ashok9730** [maciejtreder/ng-toolkit#764]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Closed as the author didn't provide enough information according to the issue template.
