### ISSUE TITLE
I want to make SEO friendly to my angular ver. 8 project

### ISSUE THREAD

**Issue by Anikesh23** [maciejtreder/ng-toolkit#765]
## I'm submitting an issue regarding npm package of

<pre><code>
ng add @ng-toolkit/universal
</code></pre>

## Current behavior
<pre><code>ERROR: Cannot read property 'unshift' of undefined
ERROR: If you think that this error shouldn't occur, please fill up bug report here: https://github.com/maciejtreder/ng-toolkit/issues/new
INFO: stacktrace has been sent to tracking system.
Nothing to be done</code></pre>

## Expected behavior
_It should have successfully installed._

## Minimal reproduction of the problem with instruction

<pre><code>
Angular version: 8.1.3

- Node version: 10.16.3  
- Platform:  Windows 10 

Others:
IDE: Visual Studio Code

</code></pre>

**Comment by KingDarBoja** [comment]
Can you provide a repository to look at? If you can't, I recommend checking my [example angular serverless repo](https://github.com/KingDarBoja/example-angular-ng-toolkit)
