### ISSUE TITLE
Cannot find BrowserModul

### ISSUE THREAD

**Issue by SetsunaFSei** [maciejtreder/ng-toolkit#770]
## I'm submitting a...

<pre><code>
[ ] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
Closing now as author didn't fill the issue template.
