### ISSUE TITLE
ERROR: newTree.optimize is not a function

### ISSUE THREAD

**Issue by Olaiz** [maciejtreder/ng-toolkit#786]
## I'm submitting a...

<pre><code>
[X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[X] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Environment

<pre><code>
Angular version: 9.0.6

- Node version: 13.7.0  
- Platform:  Linux

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
The package doesn't support Angular 9 hence the error.

Closing as duplicated. Please read #788.
