### ISSUE TITLE
ERROR: newTree.optimize is not a function

### ISSUE THREAD

**Issue by ajay-arya** [maciejtreder/ng-toolkit#787]
## I'm submitting a...
[x] Bug report 
[ ] Feature request
[ ] Documentation issue or request

## In the package
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug

Angular version: 9.0.6

- Node version: 12.14.1
- Platform:  Windows

**Comment by KingDarBoja** [comment]
The package doesn't support Angular 9, this is why the error shows up.

Closing as duplicated. Please read #788.
