### ISSUE TITLE
Angular 9 Support

### ISSUE THREAD

**Issue by KingDarBoja** [maciejtreder/ng-toolkit#788]
I just released a new minor version (8.1.0) for all packages which handles several issues and provides some bugfixes and experimental features for Angular v8. Please take a look at #745 to see what's new.

However, the new Angular version (v9.0.0) was released on February and it has several changes which must be addressed on this toolkit in order to provide proper support for end users.

This will require some time as my time is very limited due to real life stuff and also, being the only active maintainer so far. This work will not cover migration schematics as those are another headache for only one developer and the Angular schematics aren't well documented 😢 

### Universal
- [ ] Remove the prerendering script as Angular Universal now support its own prerendering script (with lazy loading support too! 🎉 ).

### Serverless
- [ ] Complete experimental features like integration with `serverless-offline` and `serverless-plugin-typescript`.

**Comment by Robinl2018** [comment]
Hi, I have the same issue, i solved it with this version
ng add @ng-toolkit/universal@8.0.3

**Comment by tspicer** [comment]
@Robinl2018 what are you saying is solved, Angular 9 support? You are able to deploy Angular 9 using 8.0.3?

**Comment by Robinl2018** [comment]
Hi, I'm using angular 8

**Comment by KingDarBoja** [comment]
I am looking into the new Angular 9 and checking what needs to be changed, thinking on using Nx Workspaces to handle all schematic stuff as monorepo but will take a while while testing and all that stuff.

**Comment by pasevin** [comment]
@KingDarBoja thanks for maintaining this library! Eagerly awaiting for Angular 9 support!

**Comment by geetika-kathuria** [comment]
@KingDarBoja Any update for angular 9 support?
