### ISSUE TITLE
NullInjectorError: No provider for Compiler!

### ISSUE THREAD

**Issue by JakaRua** [maciejtreder/ng-toolkit#795]
## I'm submitting a...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[ ] @ng-toolkit/serverless
[x] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Expected behavior
Compilation is successful and the project is going, but the site is down
![image](https://user-images.githubusercontent.com/10262515/79157489-57a69200-7ddd-11ea-8516-e53b5583e7e3.png)

## Minimal reproduction of the problem with instructions
```
ng new project
cd project
npm i @ng-toolkit/universal
ng serve
```

## Environment
<pre><code>
Angular version: 9.1.1

- Node version: 12.16.1 
- Platform:  Windows

Others:

Default settings of the angular

</code></pre>

**Comment by KingDarBoja** [comment]
Probably a side effect of updating to Angular 9 while this library isn't ready to handle those changes. By looking at the error, it is hard to tell what's going on. if you can provide some sample repo to look at, I could check what's wrong.

**Comment by JakaRua** [comment]
To reproduce the error, install clean Angular 9.1.0 then libraries and start the server. This is enough to reproduce the error. I set everything from scratch a couple of times to make sure of this. I did not do any additional manipulations. During installation, I just chose scss and routing.

**Comment by JakaRua** [comment]
Hello. I wanted to ask if there is progress on my ticket?

**Comment by KingDarBoja** [comment]
Sorry mate, I haven't tested it yet, very busy with job in real life and getting tired to keep coding after all. I will try to check this on the weekend.

**Comment by IamDeshRaj** [comment]
@JakaRua @KingDarBoja have a look here on [this reply](https://github.com/maciejtreder/ng-toolkit/issues/800#issuecomment-625701819) if it helps you out.
