### ISSUE TITLE
Serverless plugin "serverless-api-compression" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

### ISSUE THREAD

**Issue by leongrin** [maciejtreder/ng-toolkit#801]
## I'm submitting a...

<pre><code>
[ X] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[X ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

When running the command `npm run build:serverless:deploy`, I am getting this error: 

> Serverless plugin "serverless-api-compression" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

Does anyone know how to fix this?

## Environment

<pre><code>
Angular version: X.Y.Z

- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by KingDarBoja** [comment]
You need to add to your `serverless.yml` file the `serverless-api-compression` plugin and also install it.

Not sure why it is not installed on your case as the toolkit should do that for you 🤔

**Comment by leongrin** [comment]
@KingDarBoja Thank you. I did what you suggested, and I was able to complete the deployment. But my endpoint is showing this message: 
`{
message: "Internal server error"
}`

**Comment by KingDarBoja** [comment]
@leongrin hard to tell you what's wrong as this is probably related to your setup.

Closing as resolved.
