### ISSUE TITLE
Cannot set property 'esModuleInterop' of undefined

### ISSUE THREAD

**Issue by Vee75** [maciejtreder/ng-toolkit#814]
## I'm submitting an issue...

<pre><code>
[x] Bug report  
[ ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[ ] @ng-toolkit/init
[x ] @ng-toolkit/serverless
[ ] @ng-toolkit/universal
[ ] @ng-toolkit/pwa
[ ] @ng-toolkit/firebug
</code></pre>

## Current behavior

ng add @ng-toolkit/serverless --provider aws gives this error
![err1](https://user-images.githubusercontent.com/67883298/86547552-634eb400-bf07-11ea-9594-1ae105292593.jpg)
After removing comment from all json files , the error changes to this
![err2](https://user-images.githubusercontent.com/67883298/86547754-04d60580-bf08-11ea-8345-46003413e274.jpg)
adding the following to tsconfig does not help
    "esModuleInterop": true,
    "importHelpers": true,
## Expected behavior

No Error

## Minimal reproduction of the problem with instructions

I tried with my app, then a new app, just basic one right after it was created.....same behavior for both.

## Environment

<pre><code>
Angular version: X.Y.Z
10.0.1

- Node version: XX  
12.18.1
- Platform:  
Windows 10 
Others:
Angular CLI: 10.0.1
Node: 12.18.1
OS: win32 x64

Angular: 10.0.2
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.1000.1
@angular-devkit/build-angular     0.1000.1
@angular-devkit/build-optimizer   0.1000.1
@angular-devkit/build-webpack     0.1000.1
@angular-devkit/core              10.0.1
@angular-devkit/schematics        10.0.1
@angular/cli                      10.0.1
@ngtools/webpack                  10.0.1
@schematics/angular               10.0.1
@schematics/update                0.1000.1
rxjs                              6.5.5
typescript                        3.9.6
webpack                           4.43.0

</code></pre>

**Comment by KingDarBoja** [comment]
Working on a fix at #826
