### ISSUE TITLE
Pipeline error in ng-toolkit in during migration to angular-14

### ISSUE THREAD

**Issue by maniashokkumar** [maciejtreder/ng-toolkit#904]
## I'm submitting a...
Pipeline error in ng-toolkit in during migration to angular-14 peer depedency conflicts

## In package
 @ng-toolkit/universal

## Current behavior
npm ERR! While resolving: @ng-toolkit/universal@8.0.3
npm ERR! Found: @angular/common@14.1.0
npm ERR! node_modules/@angular/common
npm ERR! @angular/common@"^14.1.0" from the root project
npm ERR! peer @angular/common@"^14.0.0 || ^15.0.0" from @angular/cdk@14.1.0
npm ERR! node_modules/@angular/cdk
npm ERR! @angular/cdk@"^14.1.0" from the root project
npm ERR! peer @angular/cdk@"14.1.0" from @angular/material@14.1.0
npm ERR! node_modules/@angular/material
npm ERR! @angular/material@"^14.1.0" from the root project
npm ERR! 13 more (@angular/forms, @angular/material, ...)
npm ERR! npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"^8.2.6" from @ng-toolkit/universal@8.0.3
npm ERR! node_modules/@ng-toolkit/universal
npm ERR! @ng-toolkit/universal@"^8.0.3" from the root project npm ERR!
npm ERR! Conflicting peer dependency: @angular/common@8.2.14
npm ERR! node_modules/@angular/common
npm ERR! peer @angular/common@"^8.2.6" from @ng-toolkit/universal@8.0.3
npm ERR! node_modules/@ng-toolkit/universal
npm ERR! @ng-toolkit/universal@"^8.0.3" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! npm ERR! See /root/.npm/eresolve-report.txt for a full report.
npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2022-09-11T07_44_47_296Z-debug-0.l

## Environment

<pre><code>
Angular version: 14.1.0

- Node version: 16
- Platform:  windows

Others:

</code></pre>

**Comment by mohammadim48** [comment]
I changed my project version from 14 to 12 and it worked!
