### ISSUE TITLE
Angular 16 SUPPORT

### ISSUE THREAD

**Issue by maniashokkumar** [maciejtreder/ng-toolkit#917]
This likely means that the library (@ng-toolkit/universal) which declares NgtUniversalModule is not compatible with Angular Ivy. Check if a newer version of the library is available, and update if so. Also consider checking with the library's authors to see if the library is expected to be compatible with Ivy.

[ANGULAR 16 IVY Support request ] Feature request
[ ] Documentation issue or request
</code></pre>

## In package
<pre><code>
[https://www.npmjs.com/package/@ng-toolkit/serverless ] @ng-toolkit/serverless
[ https://www.npmjs.com/package/@ng-toolkit/universal] @ng-toolkit/universal
</code></pre>

## Current behavior
ng-toolkit is not current support for ivy (ivy enabled)

## Expected behavior
need support for ivy Angular 16

## Environment

<pre><code>
Angular version: 16.0.3

- Node version: 16

**Comment by DimitriTsikaridze** [comment]
looks like this project hasn't been receiving any updates and I don't think they'll add v16 support

**Comment by maniashokkumar** [comment]
After changing my node version the issue is resolved [reference](https://angular.io/guide/versions)
